// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/benidevo/vega/internal/ai/models"
	mock "github.com/stretchr/testify/mock"
)

// MockLetterGeneratorServiceInterface is an autogenerated mock type for the LetterGeneratorServiceInterface type
type MockLetterGeneratorServiceInterface struct {
	mock.Mock
}

type MockLetterGeneratorServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLetterGeneratorServiceInterface) EXPECT() *MockLetterGeneratorServiceInterface_Expecter {
	return &MockLetterGeneratorServiceInterface_Expecter{mock: &_m.Mock}
}

// GenerateCoverLetter provides a mock function with given fields: ctx, req
func (_m *MockLetterGeneratorServiceInterface) GenerateCoverLetter(ctx context.Context, req models.Request) (*models.CoverLetter, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GenerateCoverLetter")
	}

	var r0 *models.CoverLetter
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Request) (*models.CoverLetter, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.Request) *models.CoverLetter); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.CoverLetter)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.Request) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLetterGeneratorServiceInterface_GenerateCoverLetter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateCoverLetter'
type MockLetterGeneratorServiceInterface_GenerateCoverLetter_Call struct {
	*mock.Call
}

// GenerateCoverLetter is a helper method to define mock.On call
//   - ctx context.Context
//   - req models.Request
func (_e *MockLetterGeneratorServiceInterface_Expecter) GenerateCoverLetter(ctx interface{}, req interface{}) *MockLetterGeneratorServiceInterface_GenerateCoverLetter_Call {
	return &MockLetterGeneratorServiceInterface_GenerateCoverLetter_Call{Call: _e.mock.On("GenerateCoverLetter", ctx, req)}
}

func (_c *MockLetterGeneratorServiceInterface_GenerateCoverLetter_Call) Run(run func(ctx context.Context, req models.Request)) *MockLetterGeneratorServiceInterface_GenerateCoverLetter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.Request))
	})
	return _c
}

func (_c *MockLetterGeneratorServiceInterface_GenerateCoverLetter_Call) Return(_a0 *models.CoverLetter, _a1 error) *MockLetterGeneratorServiceInterface_GenerateCoverLetter_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLetterGeneratorServiceInterface_GenerateCoverLetter_Call) RunAndReturn(run func(context.Context, models.Request) (*models.CoverLetter, error)) *MockLetterGeneratorServiceInterface_GenerateCoverLetter_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLetterGeneratorServiceInterface creates a new instance of MockLetterGeneratorServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLetterGeneratorServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLetterGeneratorServiceInterface {
	mock := &MockLetterGeneratorServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
