// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/benidevo/vega/internal/ai/models"
	mock "github.com/stretchr/testify/mock"
)

// MockCVGeneratorServiceInterface is an autogenerated mock type for the CVGeneratorServiceInterface type
type MockCVGeneratorServiceInterface struct {
	mock.Mock
}

type MockCVGeneratorServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCVGeneratorServiceInterface) EXPECT() *MockCVGeneratorServiceInterface_Expecter {
	return &MockCVGeneratorServiceInterface_Expecter{mock: &_m.Mock}
}

// GenerateCV provides a mock function with given fields: ctx, req, jobID, jobTitle
func (_m *MockCVGeneratorServiceInterface) GenerateCV(ctx context.Context, req models.Request, jobID int, jobTitle string) (*models.GeneratedCV, error) {
	ret := _m.Called(ctx, req, jobID, jobTitle)

	if len(ret) == 0 {
		panic("no return value specified for GenerateCV")
	}

	var r0 *models.GeneratedCV
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Request, int, string) (*models.GeneratedCV, error)); ok {
		return rf(ctx, req, jobID, jobTitle)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.Request, int, string) *models.GeneratedCV); ok {
		r0 = rf(ctx, req, jobID, jobTitle)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.GeneratedCV)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.Request, int, string) error); ok {
		r1 = rf(ctx, req, jobID, jobTitle)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCVGeneratorServiceInterface_GenerateCV_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateCV'
type MockCVGeneratorServiceInterface_GenerateCV_Call struct {
	*mock.Call
}

// GenerateCV is a helper method to define mock.On call
//   - ctx context.Context
//   - req models.Request
//   - jobID int
//   - jobTitle string
func (_e *MockCVGeneratorServiceInterface_Expecter) GenerateCV(ctx interface{}, req interface{}, jobID interface{}, jobTitle interface{}) *MockCVGeneratorServiceInterface_GenerateCV_Call {
	return &MockCVGeneratorServiceInterface_GenerateCV_Call{Call: _e.mock.On("GenerateCV", ctx, req, jobID, jobTitle)}
}

func (_c *MockCVGeneratorServiceInterface_GenerateCV_Call) Run(run func(ctx context.Context, req models.Request, jobID int, jobTitle string)) *MockCVGeneratorServiceInterface_GenerateCV_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.Request), args[2].(int), args[3].(string))
	})
	return _c
}

func (_c *MockCVGeneratorServiceInterface_GenerateCV_Call) Return(_a0 *models.GeneratedCV, _a1 error) *MockCVGeneratorServiceInterface_GenerateCV_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCVGeneratorServiceInterface_GenerateCV_Call) RunAndReturn(run func(context.Context, models.Request, int, string) (*models.GeneratedCV, error)) *MockCVGeneratorServiceInterface_GenerateCV_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCVGeneratorServiceInterface creates a new instance of MockCVGeneratorServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCVGeneratorServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCVGeneratorServiceInterface {
	mock := &MockCVGeneratorServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
