// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/benidevo/vega/internal/ai/models"
	mock "github.com/stretchr/testify/mock"
)

// MockCVParserServiceInterface is an autogenerated mock type for the CVParserServiceInterface type
type MockCVParserServiceInterface struct {
	mock.Mock
}

type MockCVParserServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCVParserServiceInterface) EXPECT() *MockCVParserServiceInterface_Expecter {
	return &MockCVParserServiceInterface_Expecter{mock: &_m.Mock}
}

// ParseCV provides a mock function with given fields: ctx, cvContent
func (_m *MockCVParserServiceInterface) ParseCV(ctx context.Context, cvContent string) (*models.CVParsingResult, error) {
	ret := _m.Called(ctx, cvContent)

	if len(ret) == 0 {
		panic("no return value specified for ParseCV")
	}

	var r0 *models.CVParsingResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.CVParsingResult, error)); ok {
		return rf(ctx, cvContent)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.CVParsingResult); ok {
		r0 = rf(ctx, cvContent)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.CVParsingResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, cvContent)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCVParserServiceInterface_ParseCV_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseCV'
type MockCVParserServiceInterface_ParseCV_Call struct {
	*mock.Call
}

// ParseCV is a helper method to define mock.On call
//   - ctx context.Context
//   - cvContent string
func (_e *MockCVParserServiceInterface_Expecter) ParseCV(ctx interface{}, cvContent interface{}) *MockCVParserServiceInterface_ParseCV_Call {
	return &MockCVParserServiceInterface_ParseCV_Call{Call: _e.mock.On("ParseCV", ctx, cvContent)}
}

func (_c *MockCVParserServiceInterface_ParseCV_Call) Run(run func(ctx context.Context, cvContent string)) *MockCVParserServiceInterface_ParseCV_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCVParserServiceInterface_ParseCV_Call) Return(_a0 *models.CVParsingResult, _a1 error) *MockCVParserServiceInterface_ParseCV_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCVParserServiceInterface_ParseCV_Call) RunAndReturn(run func(context.Context, string) (*models.CVParsingResult, error)) *MockCVParserServiceInterface_ParseCV_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCVParserServiceInterface creates a new instance of MockCVParserServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCVParserServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCVParserServiceInterface {
	mock := &MockCVParserServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
