// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	llm "github.com/benidevo/vega/internal/ai/llm"
	mock "github.com/stretchr/testify/mock"
)

// MockLetterGenerator is an autogenerated mock type for the LetterGenerator type
type MockLetterGenerator struct {
	mock.Mock
}

type MockLetterGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLetterGenerator) EXPECT() *MockLetterGenerator_Expecter {
	return &MockLetterGenerator_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function with given fields: ctx, request
func (_m *MockLetterGenerator) Generate(ctx context.Context, request llm.GenerateRequest) (llm.GenerateResponse, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 llm.GenerateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, llm.GenerateRequest) (llm.GenerateResponse, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, llm.GenerateRequest) llm.GenerateResponse); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(llm.GenerateResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, llm.GenerateRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLetterGenerator_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type MockLetterGenerator_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
//   - ctx context.Context
//   - request llm.GenerateRequest
func (_e *MockLetterGenerator_Expecter) Generate(ctx interface{}, request interface{}) *MockLetterGenerator_Generate_Call {
	return &MockLetterGenerator_Generate_Call{Call: _e.mock.On("Generate", ctx, request)}
}

func (_c *MockLetterGenerator_Generate_Call) Run(run func(ctx context.Context, request llm.GenerateRequest)) *MockLetterGenerator_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(llm.GenerateRequest))
	})
	return _c
}

func (_c *MockLetterGenerator_Generate_Call) Return(_a0 llm.GenerateResponse, _a1 error) *MockLetterGenerator_Generate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLetterGenerator_Generate_Call) RunAndReturn(run func(context.Context, llm.GenerateRequest) (llm.GenerateResponse, error)) *MockLetterGenerator_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLetterGenerator creates a new instance of MockLetterGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLetterGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLetterGenerator {
	mock := &MockLetterGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
