// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/benidevo/vega/internal/ai/models"
	mock "github.com/stretchr/testify/mock"
)

// MockJobMatcherServiceInterface is an autogenerated mock type for the JobMatcherServiceInterface type
type MockJobMatcherServiceInterface struct {
	mock.Mock
}

type MockJobMatcherServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJobMatcherServiceInterface) EXPECT() *MockJobMatcherServiceInterface_Expecter {
	return &MockJobMatcherServiceInterface_Expecter{mock: &_m.Mock}
}

// AnalyzeMatch provides a mock function with given fields: ctx, req
func (_m *MockJobMatcherServiceInterface) AnalyzeMatch(ctx context.Context, req models.Request) (*models.MatchResult, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for AnalyzeMatch")
	}

	var r0 *models.MatchResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Request) (*models.MatchResult, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.Request) *models.MatchResult); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.MatchResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.Request) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockJobMatcherServiceInterface_AnalyzeMatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AnalyzeMatch'
type MockJobMatcherServiceInterface_AnalyzeMatch_Call struct {
	*mock.Call
}

// AnalyzeMatch is a helper method to define mock.On call
//   - ctx context.Context
//   - req models.Request
func (_e *MockJobMatcherServiceInterface_Expecter) AnalyzeMatch(ctx interface{}, req interface{}) *MockJobMatcherServiceInterface_AnalyzeMatch_Call {
	return &MockJobMatcherServiceInterface_AnalyzeMatch_Call{Call: _e.mock.On("AnalyzeMatch", ctx, req)}
}

func (_c *MockJobMatcherServiceInterface_AnalyzeMatch_Call) Run(run func(ctx context.Context, req models.Request)) *MockJobMatcherServiceInterface_AnalyzeMatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.Request))
	})
	return _c
}

func (_c *MockJobMatcherServiceInterface_AnalyzeMatch_Call) Return(_a0 *models.MatchResult, _a1 error) *MockJobMatcherServiceInterface_AnalyzeMatch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockJobMatcherServiceInterface_AnalyzeMatch_Call) RunAndReturn(run func(context.Context, models.Request) (*models.MatchResult, error)) *MockJobMatcherServiceInterface_AnalyzeMatch_Call {
	_c.Call.Return(run)
	return _c
}

// GetMatchCategories provides a mock function with given fields: score
func (_m *MockJobMatcherServiceInterface) GetMatchCategories(score int) (string, string) {
	ret := _m.Called(score)

	if len(ret) == 0 {
		panic("no return value specified for GetMatchCategories")
	}

	var r0 string
	var r1 string
	if rf, ok := ret.Get(0).(func(int) (string, string)); ok {
		return rf(score)
	}
	if rf, ok := ret.Get(0).(func(int) string); ok {
		r0 = rf(score)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(int) string); ok {
		r1 = rf(score)
	} else {
		r1 = ret.Get(1).(string)
	}

	return r0, r1
}

// MockJobMatcherServiceInterface_GetMatchCategories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMatchCategories'
type MockJobMatcherServiceInterface_GetMatchCategories_Call struct {
	*mock.Call
}

// GetMatchCategories is a helper method to define mock.On call
//   - score int
func (_e *MockJobMatcherServiceInterface_Expecter) GetMatchCategories(score interface{}) *MockJobMatcherServiceInterface_GetMatchCategories_Call {
	return &MockJobMatcherServiceInterface_GetMatchCategories_Call{Call: _e.mock.On("GetMatchCategories", score)}
}

func (_c *MockJobMatcherServiceInterface_GetMatchCategories_Call) Run(run func(score int)) *MockJobMatcherServiceInterface_GetMatchCategories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockJobMatcherServiceInterface_GetMatchCategories_Call) Return(_a0 string, _a1 string) *MockJobMatcherServiceInterface_GetMatchCategories_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockJobMatcherServiceInterface_GetMatchCategories_Call) RunAndReturn(run func(int) (string, string)) *MockJobMatcherServiceInterface_GetMatchCategories_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJobMatcherServiceInterface creates a new instance of MockJobMatcherServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJobMatcherServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJobMatcherServiceInterface {
	mock := &MockJobMatcherServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
