// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockOAuthService is an autogenerated mock type for the OAuthService type
type MockOAuthService struct {
	mock.Mock
}

type MockOAuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOAuthService) EXPECT() *MockOAuthService_Expecter {
	return &MockOAuthService_Expecter{mock: &_m.Mock}
}

// Authenticate provides a mock function with given fields: ctx, code, redirectURI
func (_m *MockOAuthService) Authenticate(ctx context.Context, code string, redirectURI string) (string, string, error) {
	ret := _m.Called(ctx, code, redirectURI)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, string, error)); ok {
		return rf(ctx, code, redirectURI)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, code, redirectURI)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) string); ok {
		r1 = rf(ctx, code, redirectURI)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = rf(ctx, code, redirectURI)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockOAuthService_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type MockOAuthService_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
//   - redirectURI string
func (_e *MockOAuthService_Expecter) Authenticate(ctx interface{}, code interface{}, redirectURI interface{}) *MockOAuthService_Authenticate_Call {
	return &MockOAuthService_Authenticate_Call{Call: _e.mock.On("Authenticate", ctx, code, redirectURI)}
}

func (_c *MockOAuthService_Authenticate_Call) Run(run func(ctx context.Context, code string, redirectURI string)) *MockOAuthService_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockOAuthService_Authenticate_Call) Return(accessToken string, refreshToken string, err error) *MockOAuthService_Authenticate_Call {
	_c.Call.Return(accessToken, refreshToken, err)
	return _c
}

func (_c *MockOAuthService_Authenticate_Call) RunAndReturn(run func(context.Context, string, string) (string, string, error)) *MockOAuthService_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOAuthService creates a new instance of MockOAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOAuthService {
	mock := &MockOAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
