// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockLoginService is an autogenerated mock type for the LoginService type
type MockLoginService struct {
	mock.Mock
}

type MockLoginService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLoginService) EXPECT() *MockLoginService_Expecter {
	return &MockLoginService_Expecter{mock: &_m.Mock}
}

// LogError provides a mock function with given fields: err
func (_m *MockLoginService) LogError(err error) {
	_m.Called(err)
}

// MockLoginService_LogError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogError'
type MockLoginService_LogError_Call struct {
	*mock.Call
}

// LogError is a helper method to define mock.On call
//   - err error
func (_e *MockLoginService_Expecter) LogError(err interface{}) *MockLoginService_LogError_Call {
	return &MockLoginService_LogError_Call{Call: _e.mock.On("LogError", err)}
}

func (_c *MockLoginService_LogError_Call) Run(run func(err error)) *MockLoginService_LogError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(error))
	})
	return _c
}

func (_c *MockLoginService_LogError_Call) Return() *MockLoginService_LogError_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLoginService_LogError_Call) RunAndReturn(run func(error)) *MockLoginService_LogError_Call {
	_c.Run(run)
	return _c
}

// Login provides a mock function with given fields: ctx, username, password
func (_m *MockLoginService) Login(ctx context.Context, username string, password string) (string, string, error) {
	ret := _m.Called(ctx, username, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, string, error)); ok {
		return rf(ctx, username, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, username, password)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) string); ok {
		r1 = rf(ctx, username, password)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = rf(ctx, username, password)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockLoginService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockLoginService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - password string
func (_e *MockLoginService_Expecter) Login(ctx interface{}, username interface{}, password interface{}) *MockLoginService_Login_Call {
	return &MockLoginService_Login_Call{Call: _e.mock.On("Login", ctx, username, password)}
}

func (_c *MockLoginService_Login_Call) Run(run func(ctx context.Context, username string, password string)) *MockLoginService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockLoginService_Login_Call) Return(accessToken string, refreshToken string, err error) *MockLoginService_Login_Call {
	_c.Call.Return(accessToken, refreshToken, err)
	return _c
}

func (_c *MockLoginService_Login_Call) RunAndReturn(run func(context.Context, string, string) (string, string, error)) *MockLoginService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLoginService creates a new instance of MockLoginService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLoginService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLoginService {
	mock := &MockLoginService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
