// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/benidevo/vega/internal/auth/models"
	mock "github.com/stretchr/testify/mock"

	services "github.com/benidevo/vega/internal/auth/services"
)

// MockFullAuthService is an autogenerated mock type for the FullAuthService type
type MockFullAuthService struct {
	mock.Mock
}

type MockFullAuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFullAuthService) EXPECT() *MockFullAuthService_Expecter {
	return &MockFullAuthService_Expecter{mock: &_m.Mock}
}

// ChangePassword provides a mock function with given fields: ctx, userID, newPassword
func (_m *MockFullAuthService) ChangePassword(ctx context.Context, userID int, newPassword string) error {
	ret := _m.Called(ctx, userID, newPassword)

	if len(ret) == 0 {
		panic("no return value specified for ChangePassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string) error); ok {
		r0 = rf(ctx, userID, newPassword)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFullAuthService_ChangePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangePassword'
type MockFullAuthService_ChangePassword_Call struct {
	*mock.Call
}

// ChangePassword is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - newPassword string
func (_e *MockFullAuthService_Expecter) ChangePassword(ctx interface{}, userID interface{}, newPassword interface{}) *MockFullAuthService_ChangePassword_Call {
	return &MockFullAuthService_ChangePassword_Call{Call: _e.mock.On("ChangePassword", ctx, userID, newPassword)}
}

func (_c *MockFullAuthService_ChangePassword_Call) Run(run func(ctx context.Context, userID int, newPassword string)) *MockFullAuthService_ChangePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(string))
	})
	return _c
}

func (_c *MockFullAuthService_ChangePassword_Call) Return(_a0 error) *MockFullAuthService_ChangePassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFullAuthService_ChangePassword_Call) RunAndReturn(run func(context.Context, int, string) error) *MockFullAuthService_ChangePassword_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function with given fields: ctx, id
func (_m *MockFullAuthService) GetUserByID(ctx context.Context, id int) (*models.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*models.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *models.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFullAuthService_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockFullAuthService_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockFullAuthService_Expecter) GetUserByID(ctx interface{}, id interface{}) *MockFullAuthService_GetUserByID_Call {
	return &MockFullAuthService_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, id)}
}

func (_c *MockFullAuthService_GetUserByID_Call) Run(run func(ctx context.Context, id int)) *MockFullAuthService_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockFullAuthService_GetUserByID_Call) Return(_a0 *models.User, _a1 error) *MockFullAuthService_GetUserByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFullAuthService_GetUserByID_Call) RunAndReturn(run func(context.Context, int) (*models.User, error)) *MockFullAuthService_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// LogError provides a mock function with given fields: err
func (_m *MockFullAuthService) LogError(err error) {
	_m.Called(err)
}

// MockFullAuthService_LogError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogError'
type MockFullAuthService_LogError_Call struct {
	*mock.Call
}

// LogError is a helper method to define mock.On call
//   - err error
func (_e *MockFullAuthService_Expecter) LogError(err interface{}) *MockFullAuthService_LogError_Call {
	return &MockFullAuthService_LogError_Call{Call: _e.mock.On("LogError", err)}
}

func (_c *MockFullAuthService_LogError_Call) Run(run func(err error)) *MockFullAuthService_LogError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(error))
	})
	return _c
}

func (_c *MockFullAuthService_LogError_Call) Return() *MockFullAuthService_LogError_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockFullAuthService_LogError_Call) RunAndReturn(run func(error)) *MockFullAuthService_LogError_Call {
	_c.Run(run)
	return _c
}

// Login provides a mock function with given fields: ctx, username, password
func (_m *MockFullAuthService) Login(ctx context.Context, username string, password string) (string, string, error) {
	ret := _m.Called(ctx, username, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, string, error)); ok {
		return rf(ctx, username, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, username, password)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) string); ok {
		r1 = rf(ctx, username, password)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = rf(ctx, username, password)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockFullAuthService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockFullAuthService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - password string
func (_e *MockFullAuthService_Expecter) Login(ctx interface{}, username interface{}, password interface{}) *MockFullAuthService_Login_Call {
	return &MockFullAuthService_Login_Call{Call: _e.mock.On("Login", ctx, username, password)}
}

func (_c *MockFullAuthService_Login_Call) Run(run func(ctx context.Context, username string, password string)) *MockFullAuthService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockFullAuthService_Login_Call) Return(accessToken string, refreshToken string, err error) *MockFullAuthService_Login_Call {
	_c.Call.Return(accessToken, refreshToken, err)
	return _c
}

func (_c *MockFullAuthService_Login_Call) RunAndReturn(run func(context.Context, string, string) (string, string, error)) *MockFullAuthService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshAccessToken provides a mock function with given fields: ctx, refreshToken
func (_m *MockFullAuthService) RefreshAccessToken(ctx context.Context, refreshToken string) (string, error) {
	ret := _m.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for RefreshAccessToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, refreshToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, refreshToken)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, refreshToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFullAuthService_RefreshAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshAccessToken'
type MockFullAuthService_RefreshAccessToken_Call struct {
	*mock.Call
}

// RefreshAccessToken is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *MockFullAuthService_Expecter) RefreshAccessToken(ctx interface{}, refreshToken interface{}) *MockFullAuthService_RefreshAccessToken_Call {
	return &MockFullAuthService_RefreshAccessToken_Call{Call: _e.mock.On("RefreshAccessToken", ctx, refreshToken)}
}

func (_c *MockFullAuthService_RefreshAccessToken_Call) Run(run func(ctx context.Context, refreshToken string)) *MockFullAuthService_RefreshAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockFullAuthService_RefreshAccessToken_Call) Return(_a0 string, _a1 error) *MockFullAuthService_RefreshAccessToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFullAuthService_RefreshAccessToken_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockFullAuthService_RefreshAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: ctx, username, password, role
func (_m *MockFullAuthService) Register(ctx context.Context, username string, password string, role string) (*models.User, error) {
	ret := _m.Called(ctx, username, password, role)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*models.User, error)); ok {
		return rf(ctx, username, password, role)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *models.User); ok {
		r0 = rf(ctx, username, password, role)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, username, password, role)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFullAuthService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockFullAuthService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - password string
//   - role string
func (_e *MockFullAuthService_Expecter) Register(ctx interface{}, username interface{}, password interface{}, role interface{}) *MockFullAuthService_Register_Call {
	return &MockFullAuthService_Register_Call{Call: _e.mock.On("Register", ctx, username, password, role)}
}

func (_c *MockFullAuthService_Register_Call) Run(run func(ctx context.Context, username string, password string, role string)) *MockFullAuthService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockFullAuthService_Register_Call) Return(_a0 *models.User, _a1 error) *MockFullAuthService_Register_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFullAuthService_Register_Call) RunAndReturn(run func(context.Context, string, string, string) (*models.User, error)) *MockFullAuthService_Register_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyToken provides a mock function with given fields: token
func (_m *MockFullAuthService) VerifyToken(token string) (*services.Claims, error) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for VerifyToken")
	}

	var r0 *services.Claims
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*services.Claims, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) *services.Claims); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.Claims)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFullAuthService_VerifyToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyToken'
type MockFullAuthService_VerifyToken_Call struct {
	*mock.Call
}

// VerifyToken is a helper method to define mock.On call
//   - token string
func (_e *MockFullAuthService_Expecter) VerifyToken(token interface{}) *MockFullAuthService_VerifyToken_Call {
	return &MockFullAuthService_VerifyToken_Call{Call: _e.mock.On("VerifyToken", token)}
}

func (_c *MockFullAuthService_VerifyToken_Call) Run(run func(token string)) *MockFullAuthService_VerifyToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockFullAuthService_VerifyToken_Call) Return(_a0 *services.Claims, _a1 error) *MockFullAuthService_VerifyToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFullAuthService_VerifyToken_Call) RunAndReturn(run func(string) (*services.Claims, error)) *MockFullAuthService_VerifyToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFullAuthService creates a new instance of MockFullAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFullAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFullAuthService {
	mock := &MockFullAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
