services:
  app:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    container_name: app
    env_file:
      - .env
    environment:
      - DB_CONNECTION_STRING=/app/data/vega.db
      - IS_DEVELOPMENT=true
    volumes:
      - .:/app
      - vega-dev-data:/app/data
    ports:
      - "8765:8765"
    networks:
      - vega


  db-dashboard:
    image: coleifer/sqlite-web:latest
    container_name: db-dashboard
    volumes:
      - vega-dev-data:/data
    command: sqlite_web -H 0.0.0.0 -p 8080 /data/vega.db
    depends_on:
      - app
    ports:
      - "8080:8080"
    networks:
      - vega


networks:
  vega:


volumes:
  vega-dev-data:
