// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/benidevo/vega/internal/documents/models"
	mock "github.com/stretchr/testify/mock"
)

// MockDocumentRepository is an autogenerated mock type for the DocumentRepository type
type MockDocumentRepository struct {
	mock.Mock
}

type MockDocumentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDocumentRepository) EXPECT() *MockDocumentRepository_Expecter {
	return &MockDocumentRepository_Expecter{mock: &_m.Mock}
}

// DeleteDocument provides a mock function with given fields: ctx, docID, userID
func (_m *MockDocumentRepository) DeleteDocument(ctx context.Context, docID int, userID int) error {
	ret := _m.Called(ctx, docID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDocument")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, docID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDocumentRepository_DeleteDocument_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteDocument'
type MockDocumentRepository_DeleteDocument_Call struct {
	*mock.Call
}

// DeleteDocument is a helper method to define mock.On call
//   - ctx context.Context
//   - docID int
//   - userID int
func (_e *MockDocumentRepository_Expecter) DeleteDocument(ctx interface{}, docID interface{}, userID interface{}) *MockDocumentRepository_DeleteDocument_Call {
	return &MockDocumentRepository_DeleteDocument_Call{Call: _e.mock.On("DeleteDocument", ctx, docID, userID)}
}

func (_c *MockDocumentRepository_DeleteDocument_Call) Run(run func(ctx context.Context, docID int, userID int)) *MockDocumentRepository_DeleteDocument_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockDocumentRepository_DeleteDocument_Call) Return(_a0 error) *MockDocumentRepository_DeleteDocument_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDocumentRepository_DeleteDocument_Call) RunAndReturn(run func(context.Context, int, int) error) *MockDocumentRepository_DeleteDocument_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllDocuments provides a mock function with given fields: ctx, userID, limit, offset
func (_m *MockDocumentRepository) GetAllDocuments(ctx context.Context, userID int, limit int, offset int) ([]*models.DocumentSummary, int, error) {
	ret := _m.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetAllDocuments")
	}

	var r0 []*models.DocumentSummary
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int) ([]*models.DocumentSummary, int, error)); ok {
		return rf(ctx, userID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int) []*models.DocumentSummary); ok {
		r0 = rf(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.DocumentSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, int) int); ok {
		r1 = rf(ctx, userID, limit, offset)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int, int) error); ok {
		r2 = rf(ctx, userID, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockDocumentRepository_GetAllDocuments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllDocuments'
type MockDocumentRepository_GetAllDocuments_Call struct {
	*mock.Call
}

// GetAllDocuments is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - limit int
//   - offset int
func (_e *MockDocumentRepository_Expecter) GetAllDocuments(ctx interface{}, userID interface{}, limit interface{}, offset interface{}) *MockDocumentRepository_GetAllDocuments_Call {
	return &MockDocumentRepository_GetAllDocuments_Call{Call: _e.mock.On("GetAllDocuments", ctx, userID, limit, offset)}
}

func (_c *MockDocumentRepository_GetAllDocuments_Call) Run(run func(ctx context.Context, userID int, limit int, offset int)) *MockDocumentRepository_GetAllDocuments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockDocumentRepository_GetAllDocuments_Call) Return(_a0 []*models.DocumentSummary, _a1 int, _a2 error) *MockDocumentRepository_GetAllDocuments_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockDocumentRepository_GetAllDocuments_Call) RunAndReturn(run func(context.Context, int, int, int) ([]*models.DocumentSummary, int, error)) *MockDocumentRepository_GetAllDocuments_Call {
	_c.Call.Return(run)
	return _c
}

// GetDocument provides a mock function with given fields: ctx, docID, userID
func (_m *MockDocumentRepository) GetDocument(ctx context.Context, docID int, userID int) (*models.Document, error) {
	ret := _m.Called(ctx, docID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetDocument")
	}

	var r0 *models.Document
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) (*models.Document, error)); ok {
		return rf(ctx, docID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) *models.Document); ok {
		r0 = rf(ctx, docID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Document)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, docID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDocumentRepository_GetDocument_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDocument'
type MockDocumentRepository_GetDocument_Call struct {
	*mock.Call
}

// GetDocument is a helper method to define mock.On call
//   - ctx context.Context
//   - docID int
//   - userID int
func (_e *MockDocumentRepository_Expecter) GetDocument(ctx interface{}, docID interface{}, userID interface{}) *MockDocumentRepository_GetDocument_Call {
	return &MockDocumentRepository_GetDocument_Call{Call: _e.mock.On("GetDocument", ctx, docID, userID)}
}

func (_c *MockDocumentRepository_GetDocument_Call) Run(run func(ctx context.Context, docID int, userID int)) *MockDocumentRepository_GetDocument_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockDocumentRepository_GetDocument_Call) Return(_a0 *models.Document, _a1 error) *MockDocumentRepository_GetDocument_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDocumentRepository_GetDocument_Call) RunAndReturn(run func(context.Context, int, int) (*models.Document, error)) *MockDocumentRepository_GetDocument_Call {
	_c.Call.Return(run)
	return _c
}

// GetDocumentByJobAndType provides a mock function with given fields: ctx, userID, jobID, docType
func (_m *MockDocumentRepository) GetDocumentByJobAndType(ctx context.Context, userID int, jobID int, docType models.DocumentType) (*models.Document, error) {
	ret := _m.Called(ctx, userID, jobID, docType)

	if len(ret) == 0 {
		panic("no return value specified for GetDocumentByJobAndType")
	}

	var r0 *models.Document
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, models.DocumentType) (*models.Document, error)); ok {
		return rf(ctx, userID, jobID, docType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, models.DocumentType) *models.Document); ok {
		r0 = rf(ctx, userID, jobID, docType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Document)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, models.DocumentType) error); ok {
		r1 = rf(ctx, userID, jobID, docType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDocumentRepository_GetDocumentByJobAndType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDocumentByJobAndType'
type MockDocumentRepository_GetDocumentByJobAndType_Call struct {
	*mock.Call
}

// GetDocumentByJobAndType is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - jobID int
//   - docType models.DocumentType
func (_e *MockDocumentRepository_Expecter) GetDocumentByJobAndType(ctx interface{}, userID interface{}, jobID interface{}, docType interface{}) *MockDocumentRepository_GetDocumentByJobAndType_Call {
	return &MockDocumentRepository_GetDocumentByJobAndType_Call{Call: _e.mock.On("GetDocumentByJobAndType", ctx, userID, jobID, docType)}
}

func (_c *MockDocumentRepository_GetDocumentByJobAndType_Call) Run(run func(ctx context.Context, userID int, jobID int, docType models.DocumentType)) *MockDocumentRepository_GetDocumentByJobAndType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int), args[3].(models.DocumentType))
	})
	return _c
}

func (_c *MockDocumentRepository_GetDocumentByJobAndType_Call) Return(_a0 *models.Document, _a1 error) *MockDocumentRepository_GetDocumentByJobAndType_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDocumentRepository_GetDocumentByJobAndType_Call) RunAndReturn(run func(context.Context, int, int, models.DocumentType) (*models.Document, error)) *MockDocumentRepository_GetDocumentByJobAndType_Call {
	_c.Call.Return(run)
	return _c
}

// GetDocumentMetrics provides a mock function with given fields: ctx, userID
func (_m *MockDocumentRepository) GetDocumentMetrics(ctx context.Context, userID int) (*models.DocumentMetrics, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetDocumentMetrics")
	}

	var r0 *models.DocumentMetrics
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*models.DocumentMetrics, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *models.DocumentMetrics); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.DocumentMetrics)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDocumentRepository_GetDocumentMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDocumentMetrics'
type MockDocumentRepository_GetDocumentMetrics_Call struct {
	*mock.Call
}

// GetDocumentMetrics is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockDocumentRepository_Expecter) GetDocumentMetrics(ctx interface{}, userID interface{}) *MockDocumentRepository_GetDocumentMetrics_Call {
	return &MockDocumentRepository_GetDocumentMetrics_Call{Call: _e.mock.On("GetDocumentMetrics", ctx, userID)}
}

func (_c *MockDocumentRepository_GetDocumentMetrics_Call) Run(run func(ctx context.Context, userID int)) *MockDocumentRepository_GetDocumentMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockDocumentRepository_GetDocumentMetrics_Call) Return(_a0 *models.DocumentMetrics, _a1 error) *MockDocumentRepository_GetDocumentMetrics_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDocumentRepository_GetDocumentMetrics_Call) RunAndReturn(run func(context.Context, int) (*models.DocumentMetrics, error)) *MockDocumentRepository_GetDocumentMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// GetDocumentsByJob provides a mock function with given fields: ctx, userID, jobID
func (_m *MockDocumentRepository) GetDocumentsByJob(ctx context.Context, userID int, jobID int) ([]*models.Document, error) {
	ret := _m.Called(ctx, userID, jobID)

	if len(ret) == 0 {
		panic("no return value specified for GetDocumentsByJob")
	}

	var r0 []*models.Document
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]*models.Document, error)); ok {
		return rf(ctx, userID, jobID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []*models.Document); ok {
		r0 = rf(ctx, userID, jobID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Document)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, userID, jobID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDocumentRepository_GetDocumentsByJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDocumentsByJob'
type MockDocumentRepository_GetDocumentsByJob_Call struct {
	*mock.Call
}

// GetDocumentsByJob is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - jobID int
func (_e *MockDocumentRepository_Expecter) GetDocumentsByJob(ctx interface{}, userID interface{}, jobID interface{}) *MockDocumentRepository_GetDocumentsByJob_Call {
	return &MockDocumentRepository_GetDocumentsByJob_Call{Call: _e.mock.On("GetDocumentsByJob", ctx, userID, jobID)}
}

func (_c *MockDocumentRepository_GetDocumentsByJob_Call) Run(run func(ctx context.Context, userID int, jobID int)) *MockDocumentRepository_GetDocumentsByJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockDocumentRepository_GetDocumentsByJob_Call) Return(_a0 []*models.Document, _a1 error) *MockDocumentRepository_GetDocumentsByJob_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDocumentRepository_GetDocumentsByJob_Call) RunAndReturn(run func(context.Context, int, int) ([]*models.Document, error)) *MockDocumentRepository_GetDocumentsByJob_Call {
	_c.Call.Return(run)
	return _c
}

// GetDocumentsByType provides a mock function with given fields: ctx, userID, docType, limit, offset
func (_m *MockDocumentRepository) GetDocumentsByType(ctx context.Context, userID int, docType models.DocumentType, limit int, offset int) ([]*models.DocumentSummary, int, error) {
	ret := _m.Called(ctx, userID, docType, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetDocumentsByType")
	}

	var r0 []*models.DocumentSummary
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, models.DocumentType, int, int) ([]*models.DocumentSummary, int, error)); ok {
		return rf(ctx, userID, docType, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, models.DocumentType, int, int) []*models.DocumentSummary); ok {
		r0 = rf(ctx, userID, docType, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.DocumentSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, models.DocumentType, int, int) int); ok {
		r1 = rf(ctx, userID, docType, limit, offset)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, models.DocumentType, int, int) error); ok {
		r2 = rf(ctx, userID, docType, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockDocumentRepository_GetDocumentsByType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDocumentsByType'
type MockDocumentRepository_GetDocumentsByType_Call struct {
	*mock.Call
}

// GetDocumentsByType is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - docType models.DocumentType
//   - limit int
//   - offset int
func (_e *MockDocumentRepository_Expecter) GetDocumentsByType(ctx interface{}, userID interface{}, docType interface{}, limit interface{}, offset interface{}) *MockDocumentRepository_GetDocumentsByType_Call {
	return &MockDocumentRepository_GetDocumentsByType_Call{Call: _e.mock.On("GetDocumentsByType", ctx, userID, docType, limit, offset)}
}

func (_c *MockDocumentRepository_GetDocumentsByType_Call) Run(run func(ctx context.Context, userID int, docType models.DocumentType, limit int, offset int)) *MockDocumentRepository_GetDocumentsByType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(models.DocumentType), args[3].(int), args[4].(int))
	})
	return _c
}

func (_c *MockDocumentRepository_GetDocumentsByType_Call) Return(_a0 []*models.DocumentSummary, _a1 int, _a2 error) *MockDocumentRepository_GetDocumentsByType_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockDocumentRepository_GetDocumentsByType_Call) RunAndReturn(run func(context.Context, int, models.DocumentType, int, int) ([]*models.DocumentSummary, int, error)) *MockDocumentRepository_GetDocumentsByType_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertDocument provides a mock function with given fields: ctx, doc
func (_m *MockDocumentRepository) UpsertDocument(ctx context.Context, doc *models.Document) error {
	ret := _m.Called(ctx, doc)

	if len(ret) == 0 {
		panic("no return value specified for UpsertDocument")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Document) error); ok {
		r0 = rf(ctx, doc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDocumentRepository_UpsertDocument_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertDocument'
type MockDocumentRepository_UpsertDocument_Call struct {
	*mock.Call
}

// UpsertDocument is a helper method to define mock.On call
//   - ctx context.Context
//   - doc *models.Document
func (_e *MockDocumentRepository_Expecter) UpsertDocument(ctx interface{}, doc interface{}) *MockDocumentRepository_UpsertDocument_Call {
	return &MockDocumentRepository_UpsertDocument_Call{Call: _e.mock.On("UpsertDocument", ctx, doc)}
}

func (_c *MockDocumentRepository_UpsertDocument_Call) Run(run func(ctx context.Context, doc *models.Document)) *MockDocumentRepository_UpsertDocument_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Document))
	})
	return _c
}

func (_c *MockDocumentRepository_UpsertDocument_Call) Return(_a0 error) *MockDocumentRepository_UpsertDocument_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDocumentRepository_UpsertDocument_Call) RunAndReturn(run func(context.Context, *models.Document) error) *MockDocumentRepository_UpsertDocument_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDocumentRepository creates a new instance of MockDocumentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDocumentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDocumentRepository {
	mock := &MockDocumentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
