// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	quota "github.com/benidevo/vega/internal/quota"
	mock "github.com/stretchr/testify/mock"
)

// MockQuotaReporter is an autogenerated mock type for the QuotaReporter type
type MockQuotaReporter struct {
	mock.Mock
}

type MockQuotaReporter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQuotaReporter) EXPECT() *MockQuotaReporter_Expecter {
	return &MockQuotaReporter_Expecter{mock: &_m.Mock}
}

// GetMonthlyUsage provides a mock function with given fields: ctx, userID
func (_m *MockQuotaReporter) GetMonthlyUsage(ctx context.Context, userID int) (*quota.QuotaUsage, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetMonthlyUsage")
	}

	var r0 *quota.QuotaUsage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*quota.QuotaUsage, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *quota.QuotaUsage); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*quota.QuotaUsage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuotaReporter_GetMonthlyUsage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMonthlyUsage'
type MockQuotaReporter_GetMonthlyUsage_Call struct {
	*mock.Call
}

// GetMonthlyUsage is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockQuotaReporter_Expecter) GetMonthlyUsage(ctx interface{}, userID interface{}) *MockQuotaReporter_GetMonthlyUsage_Call {
	return &MockQuotaReporter_GetMonthlyUsage_Call{Call: _e.mock.On("GetMonthlyUsage", ctx, userID)}
}

func (_c *MockQuotaReporter_GetMonthlyUsage_Call) Run(run func(ctx context.Context, userID int)) *MockQuotaReporter_GetMonthlyUsage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockQuotaReporter_GetMonthlyUsage_Call) Return(_a0 *quota.QuotaUsage, _a1 error) *MockQuotaReporter_GetMonthlyUsage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuotaReporter_GetMonthlyUsage_Call) RunAndReturn(run func(context.Context, int) (*quota.QuotaUsage, error)) *MockQuotaReporter_GetMonthlyUsage_Call {
	_c.Call.Return(run)
	return _c
}

// GetQuotaStatus provides a mock function with given fields: ctx, userID
func (_m *MockQuotaReporter) GetQuotaStatus(ctx context.Context, userID int) (*quota.QuotaStatus, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetQuotaStatus")
	}

	var r0 *quota.QuotaStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*quota.QuotaStatus, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *quota.QuotaStatus); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*quota.QuotaStatus)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuotaReporter_GetQuotaStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQuotaStatus'
type MockQuotaReporter_GetQuotaStatus_Call struct {
	*mock.Call
}

// GetQuotaStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockQuotaReporter_Expecter) GetQuotaStatus(ctx interface{}, userID interface{}) *MockQuotaReporter_GetQuotaStatus_Call {
	return &MockQuotaReporter_GetQuotaStatus_Call{Call: _e.mock.On("GetQuotaStatus", ctx, userID)}
}

func (_c *MockQuotaReporter_GetQuotaStatus_Call) Run(run func(ctx context.Context, userID int)) *MockQuotaReporter_GetQuotaStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockQuotaReporter_GetQuotaStatus_Call) Return(_a0 *quota.QuotaStatus, _a1 error) *MockQuotaReporter_GetQuotaStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuotaReporter_GetQuotaStatus_Call) RunAndReturn(run func(context.Context, int) (*quota.QuotaStatus, error)) *MockQuotaReporter_GetQuotaStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQuotaReporter creates a new instance of MockQuotaReporter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQuotaReporter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQuotaReporter {
	mock := &MockQuotaReporter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
