// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/benidevo/vega/internal/quota/models"
	mock "github.com/stretchr/testify/mock"
)

// MockQuotaService is an autogenerated mock type for the QuotaService type
type MockQuotaService struct {
	mock.Mock
}

type MockQuotaService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQuotaService) EXPECT() *MockQuotaService_Expecter {
	return &MockQuotaService_Expecter{mock: &_m.Mock}
}

// CanAnalyzeJob provides a mock function with given fields: ctx, userID, jobID
func (_m *MockQuotaService) CanAnalyzeJob(ctx context.Context, userID int, jobID int) (*models.QuotaCheckResult, error) {
	ret := _m.Called(ctx, userID, jobID)

	if len(ret) == 0 {
		panic("no return value specified for CanAnalyzeJob")
	}

	var r0 *models.QuotaCheckResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) (*models.QuotaCheckResult, error)); ok {
		return rf(ctx, userID, jobID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) *models.QuotaCheckResult); ok {
		r0 = rf(ctx, userID, jobID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.QuotaCheckResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, userID, jobID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuotaService_CanAnalyzeJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CanAnalyzeJob'
type MockQuotaService_CanAnalyzeJob_Call struct {
	*mock.Call
}

// CanAnalyzeJob is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - jobID int
func (_e *MockQuotaService_Expecter) CanAnalyzeJob(ctx interface{}, userID interface{}, jobID interface{}) *MockQuotaService_CanAnalyzeJob_Call {
	return &MockQuotaService_CanAnalyzeJob_Call{Call: _e.mock.On("CanAnalyzeJob", ctx, userID, jobID)}
}

func (_c *MockQuotaService_CanAnalyzeJob_Call) Run(run func(ctx context.Context, userID int, jobID int)) *MockQuotaService_CanAnalyzeJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockQuotaService_CanAnalyzeJob_Call) Return(_a0 *models.QuotaCheckResult, _a1 error) *MockQuotaService_CanAnalyzeJob_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuotaService_CanAnalyzeJob_Call) RunAndReturn(run func(context.Context, int, int) (*models.QuotaCheckResult, error)) *MockQuotaService_CanAnalyzeJob_Call {
	_c.Call.Return(run)
	return _c
}

// GetMonthlyUsage provides a mock function with given fields: ctx, userID
func (_m *MockQuotaService) GetMonthlyUsage(ctx context.Context, userID int) (*models.QuotaUsage, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetMonthlyUsage")
	}

	var r0 *models.QuotaUsage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*models.QuotaUsage, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *models.QuotaUsage); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.QuotaUsage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuotaService_GetMonthlyUsage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMonthlyUsage'
type MockQuotaService_GetMonthlyUsage_Call struct {
	*mock.Call
}

// GetMonthlyUsage is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockQuotaService_Expecter) GetMonthlyUsage(ctx interface{}, userID interface{}) *MockQuotaService_GetMonthlyUsage_Call {
	return &MockQuotaService_GetMonthlyUsage_Call{Call: _e.mock.On("GetMonthlyUsage", ctx, userID)}
}

func (_c *MockQuotaService_GetMonthlyUsage_Call) Run(run func(ctx context.Context, userID int)) *MockQuotaService_GetMonthlyUsage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockQuotaService_GetMonthlyUsage_Call) Return(_a0 *models.QuotaUsage, _a1 error) *MockQuotaService_GetMonthlyUsage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuotaService_GetMonthlyUsage_Call) RunAndReturn(run func(context.Context, int) (*models.QuotaUsage, error)) *MockQuotaService_GetMonthlyUsage_Call {
	_c.Call.Return(run)
	return _c
}

// GetQuotaStatus provides a mock function with given fields: ctx, userID
func (_m *MockQuotaService) GetQuotaStatus(ctx context.Context, userID int) (*models.QuotaStatus, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetQuotaStatus")
	}

	var r0 *models.QuotaStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*models.QuotaStatus, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *models.QuotaStatus); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.QuotaStatus)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuotaService_GetQuotaStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQuotaStatus'
type MockQuotaService_GetQuotaStatus_Call struct {
	*mock.Call
}

// GetQuotaStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockQuotaService_Expecter) GetQuotaStatus(ctx interface{}, userID interface{}) *MockQuotaService_GetQuotaStatus_Call {
	return &MockQuotaService_GetQuotaStatus_Call{Call: _e.mock.On("GetQuotaStatus", ctx, userID)}
}

func (_c *MockQuotaService_GetQuotaStatus_Call) Run(run func(ctx context.Context, userID int)) *MockQuotaService_GetQuotaStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockQuotaService_GetQuotaStatus_Call) Return(_a0 *models.QuotaStatus, _a1 error) *MockQuotaService_GetQuotaStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuotaService_GetQuotaStatus_Call) RunAndReturn(run func(context.Context, int) (*models.QuotaStatus, error)) *MockQuotaService_GetQuotaStatus_Call {
	_c.Call.Return(run)
	return _c
}

// RecordAnalysis provides a mock function with given fields: ctx, userID, jobID
func (_m *MockQuotaService) RecordAnalysis(ctx context.Context, userID int, jobID int) error {
	ret := _m.Called(ctx, userID, jobID)

	if len(ret) == 0 {
		panic("no return value specified for RecordAnalysis")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, userID, jobID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuotaService_RecordAnalysis_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordAnalysis'
type MockQuotaService_RecordAnalysis_Call struct {
	*mock.Call
}

// RecordAnalysis is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - jobID int
func (_e *MockQuotaService_Expecter) RecordAnalysis(ctx interface{}, userID interface{}, jobID interface{}) *MockQuotaService_RecordAnalysis_Call {
	return &MockQuotaService_RecordAnalysis_Call{Call: _e.mock.On("RecordAnalysis", ctx, userID, jobID)}
}

func (_c *MockQuotaService_RecordAnalysis_Call) Run(run func(ctx context.Context, userID int, jobID int)) *MockQuotaService_RecordAnalysis_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockQuotaService_RecordAnalysis_Call) Return(_a0 error) *MockQuotaService_RecordAnalysis_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuotaService_RecordAnalysis_Call) RunAndReturn(run func(context.Context, int, int) error) *MockQuotaService_RecordAnalysis_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQuotaService creates a new instance of MockQuotaService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQuotaService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQuotaService {
	mock := &MockQuotaService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
