// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/benidevo/vega/internal/quota/models"
	mock "github.com/stretchr/testify/mock"
)

// MockJobRepository is an autogenerated mock type for the JobRepository type
type MockJobRepository struct {
	mock.Mock
}

type MockJobRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJobRepository) EXPECT() *MockJobRepository_Expecter {
	return &MockJobRepository_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function with given fields: ctx, userID, jobID
func (_m *MockJobRepository) GetByID(ctx context.Context, userID int, jobID int) (*models.Job, error) {
	ret := _m.Called(ctx, userID, jobID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Job
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) (*models.Job, error)); ok {
		return rf(ctx, userID, jobID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) *models.Job); ok {
		r0 = rf(ctx, userID, jobID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Job)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, userID, jobID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockJobRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockJobRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - jobID int
func (_e *MockJobRepository_Expecter) GetByID(ctx interface{}, userID interface{}, jobID interface{}) *MockJobRepository_GetByID_Call {
	return &MockJobRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, userID, jobID)}
}

func (_c *MockJobRepository_GetByID_Call) Run(run func(ctx context.Context, userID int, jobID int)) *MockJobRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockJobRepository_GetByID_Call) Return(_a0 *models.Job, _a1 error) *MockJobRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockJobRepository_GetByID_Call) RunAndReturn(run func(context.Context, int, int) (*models.Job, error)) *MockJobRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// SetFirstAnalyzedAt provides a mock function with given fields: ctx, jobID
func (_m *MockJobRepository) SetFirstAnalyzedAt(ctx context.Context, jobID int) error {
	ret := _m.Called(ctx, jobID)

	if len(ret) == 0 {
		panic("no return value specified for SetFirstAnalyzedAt")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, jobID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockJobRepository_SetFirstAnalyzedAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetFirstAnalyzedAt'
type MockJobRepository_SetFirstAnalyzedAt_Call struct {
	*mock.Call
}

// SetFirstAnalyzedAt is a helper method to define mock.On call
//   - ctx context.Context
//   - jobID int
func (_e *MockJobRepository_Expecter) SetFirstAnalyzedAt(ctx interface{}, jobID interface{}) *MockJobRepository_SetFirstAnalyzedAt_Call {
	return &MockJobRepository_SetFirstAnalyzedAt_Call{Call: _e.mock.On("SetFirstAnalyzedAt", ctx, jobID)}
}

func (_c *MockJobRepository_SetFirstAnalyzedAt_Call) Run(run func(ctx context.Context, jobID int)) *MockJobRepository_SetFirstAnalyzedAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockJobRepository_SetFirstAnalyzedAt_Call) Return(_a0 error) *MockJobRepository_SetFirstAnalyzedAt_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockJobRepository_SetFirstAnalyzedAt_Call) RunAndReturn(run func(context.Context, int) error) *MockJobRepository_SetFirstAnalyzedAt_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJobRepository creates a new instance of MockJobRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJobRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJobRepository {
	mock := &MockJobRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
