// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	quota "github.com/benidevo/vega/internal/quota"
	mock "github.com/stretchr/testify/mock"
)

// MockQuotaChecker is an autogenerated mock type for the QuotaChecker type
type MockQuotaChecker struct {
	mock.Mock
}

type MockQuotaChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQuotaChecker) EXPECT() *MockQuotaChecker_Expecter {
	return &MockQuotaChecker_Expecter{mock: &_m.Mock}
}

// CanAnalyzeJob provides a mock function with given fields: ctx, userID, jobID
func (_m *MockQuotaChecker) CanAnalyzeJob(ctx context.Context, userID int, jobID int) (*quota.QuotaCheckResult, error) {
	ret := _m.Called(ctx, userID, jobID)

	if len(ret) == 0 {
		panic("no return value specified for CanAnalyzeJob")
	}

	var r0 *quota.QuotaCheckResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) (*quota.QuotaCheckResult, error)); ok {
		return rf(ctx, userID, jobID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) *quota.QuotaCheckResult); ok {
		r0 = rf(ctx, userID, jobID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*quota.QuotaCheckResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, userID, jobID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuotaChecker_CanAnalyzeJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CanAnalyzeJob'
type MockQuotaChecker_CanAnalyzeJob_Call struct {
	*mock.Call
}

// CanAnalyzeJob is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - jobID int
func (_e *MockQuotaChecker_Expecter) CanAnalyzeJob(ctx interface{}, userID interface{}, jobID interface{}) *MockQuotaChecker_CanAnalyzeJob_Call {
	return &MockQuotaChecker_CanAnalyzeJob_Call{Call: _e.mock.On("CanAnalyzeJob", ctx, userID, jobID)}
}

func (_c *MockQuotaChecker_CanAnalyzeJob_Call) Run(run func(ctx context.Context, userID int, jobID int)) *MockQuotaChecker_CanAnalyzeJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockQuotaChecker_CanAnalyzeJob_Call) Return(_a0 *quota.QuotaCheckResult, _a1 error) *MockQuotaChecker_CanAnalyzeJob_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuotaChecker_CanAnalyzeJob_Call) RunAndReturn(run func(context.Context, int, int) (*quota.QuotaCheckResult, error)) *MockQuotaChecker_CanAnalyzeJob_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQuotaChecker creates a new instance of MockQuotaChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQuotaChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQuotaChecker {
	mock := &MockQuotaChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
