// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockQuotaRecorder is an autogenerated mock type for the QuotaRecorder type
type MockQuotaRecorder struct {
	mock.Mock
}

type MockQuotaRecorder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQuotaRecorder) EXPECT() *MockQuotaRecorder_Expecter {
	return &MockQuotaRecorder_Expecter{mock: &_m.Mock}
}

// RecordAnalysis provides a mock function with given fields: ctx, userID, jobID
func (_m *MockQuotaRecorder) RecordAnalysis(ctx context.Context, userID int, jobID int) error {
	ret := _m.Called(ctx, userID, jobID)

	if len(ret) == 0 {
		panic("no return value specified for RecordAnalysis")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, userID, jobID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuotaRecorder_RecordAnalysis_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordAnalysis'
type MockQuotaRecorder_RecordAnalysis_Call struct {
	*mock.Call
}

// RecordAnalysis is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - jobID int
func (_e *MockQuotaRecorder_Expecter) RecordAnalysis(ctx interface{}, userID interface{}, jobID interface{}) *MockQuotaRecorder_RecordAnalysis_Call {
	return &MockQuotaRecorder_RecordAnalysis_Call{Call: _e.mock.On("RecordAnalysis", ctx, userID, jobID)}
}

func (_c *MockQuotaRecorder_RecordAnalysis_Call) Run(run func(ctx context.Context, userID int, jobID int)) *MockQuotaRecorder_RecordAnalysis_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockQuotaRecorder_RecordAnalysis_Call) Return(_a0 error) *MockQuotaRecorder_RecordAnalysis_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuotaRecorder_RecordAnalysis_Call) RunAndReturn(run func(context.Context, int, int) error) *MockQuotaRecorder_RecordAnalysis_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQuotaRecorder creates a new instance of MockQuotaRecorder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQuotaRecorder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQuotaRecorder {
	mock := &MockQuotaRecorder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
