// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	quota "github.com/benidevo/vega/internal/quota"
	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// GetAllDailyUsage provides a mock function with given fields: ctx, userID, date
func (_m *MockRepository) GetAllDailyUsage(ctx context.Context, userID int, date string) (map[string]int, error) {
	ret := _m.Called(ctx, userID, date)

	if len(ret) == 0 {
		panic("no return value specified for GetAllDailyUsage")
	}

	var r0 map[string]int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string) (map[string]int, error)); ok {
		return rf(ctx, userID, date)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, string) map[string]int); ok {
		r0 = rf(ctx, userID, date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, string) error); ok {
		r1 = rf(ctx, userID, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetAllDailyUsage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllDailyUsage'
type MockRepository_GetAllDailyUsage_Call struct {
	*mock.Call
}

// GetAllDailyUsage is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - date string
func (_e *MockRepository_Expecter) GetAllDailyUsage(ctx interface{}, userID interface{}, date interface{}) *MockRepository_GetAllDailyUsage_Call {
	return &MockRepository_GetAllDailyUsage_Call{Call: _e.mock.On("GetAllDailyUsage", ctx, userID, date)}
}

func (_c *MockRepository_GetAllDailyUsage_Call) Run(run func(ctx context.Context, userID int, date string)) *MockRepository_GetAllDailyUsage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(string))
	})
	return _c
}

func (_c *MockRepository_GetAllDailyUsage_Call) Return(_a0 map[string]int, _a1 error) *MockRepository_GetAllDailyUsage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetAllDailyUsage_Call) RunAndReturn(run func(context.Context, int, string) (map[string]int, error)) *MockRepository_GetAllDailyUsage_Call {
	_c.Call.Return(run)
	return _c
}

// GetDailyUsage provides a mock function with given fields: ctx, userID, date, quotaKey
func (_m *MockRepository) GetDailyUsage(ctx context.Context, userID int, date string, quotaKey string) (int, error) {
	ret := _m.Called(ctx, userID, date, quotaKey)

	if len(ret) == 0 {
		panic("no return value specified for GetDailyUsage")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string, string) (int, error)); ok {
		return rf(ctx, userID, date, quotaKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, string, string) int); ok {
		r0 = rf(ctx, userID, date, quotaKey)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, string, string) error); ok {
		r1 = rf(ctx, userID, date, quotaKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetDailyUsage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDailyUsage'
type MockRepository_GetDailyUsage_Call struct {
	*mock.Call
}

// GetDailyUsage is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - date string
//   - quotaKey string
func (_e *MockRepository_Expecter) GetDailyUsage(ctx interface{}, userID interface{}, date interface{}, quotaKey interface{}) *MockRepository_GetDailyUsage_Call {
	return &MockRepository_GetDailyUsage_Call{Call: _e.mock.On("GetDailyUsage", ctx, userID, date, quotaKey)}
}

func (_c *MockRepository_GetDailyUsage_Call) Run(run func(ctx context.Context, userID int, date string, quotaKey string)) *MockRepository_GetDailyUsage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockRepository_GetDailyUsage_Call) Return(_a0 int, _a1 error) *MockRepository_GetDailyUsage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetDailyUsage_Call) RunAndReturn(run func(context.Context, int, string, string) (int, error)) *MockRepository_GetDailyUsage_Call {
	_c.Call.Return(run)
	return _c
}

// GetMonthlyUsage provides a mock function with given fields: ctx, userID, monthYear
func (_m *MockRepository) GetMonthlyUsage(ctx context.Context, userID int, monthYear string) (*quota.QuotaUsage, error) {
	ret := _m.Called(ctx, userID, monthYear)

	if len(ret) == 0 {
		panic("no return value specified for GetMonthlyUsage")
	}

	var r0 *quota.QuotaUsage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string) (*quota.QuotaUsage, error)); ok {
		return rf(ctx, userID, monthYear)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, string) *quota.QuotaUsage); ok {
		r0 = rf(ctx, userID, monthYear)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*quota.QuotaUsage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, string) error); ok {
		r1 = rf(ctx, userID, monthYear)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetMonthlyUsage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMonthlyUsage'
type MockRepository_GetMonthlyUsage_Call struct {
	*mock.Call
}

// GetMonthlyUsage is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - monthYear string
func (_e *MockRepository_Expecter) GetMonthlyUsage(ctx interface{}, userID interface{}, monthYear interface{}) *MockRepository_GetMonthlyUsage_Call {
	return &MockRepository_GetMonthlyUsage_Call{Call: _e.mock.On("GetMonthlyUsage", ctx, userID, monthYear)}
}

func (_c *MockRepository_GetMonthlyUsage_Call) Run(run func(ctx context.Context, userID int, monthYear string)) *MockRepository_GetMonthlyUsage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(string))
	})
	return _c
}

func (_c *MockRepository_GetMonthlyUsage_Call) Return(_a0 *quota.QuotaUsage, _a1 error) *MockRepository_GetMonthlyUsage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetMonthlyUsage_Call) RunAndReturn(run func(context.Context, int, string) (*quota.QuotaUsage, error)) *MockRepository_GetMonthlyUsage_Call {
	_c.Call.Return(run)
	return _c
}

// GetQuotaConfig provides a mock function with given fields: ctx, quotaType
func (_m *MockRepository) GetQuotaConfig(ctx context.Context, quotaType string) (*quota.QuotaConfig, error) {
	ret := _m.Called(ctx, quotaType)

	if len(ret) == 0 {
		panic("no return value specified for GetQuotaConfig")
	}

	var r0 *quota.QuotaConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*quota.QuotaConfig, error)); ok {
		return rf(ctx, quotaType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *quota.QuotaConfig); ok {
		r0 = rf(ctx, quotaType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*quota.QuotaConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, quotaType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetQuotaConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQuotaConfig'
type MockRepository_GetQuotaConfig_Call struct {
	*mock.Call
}

// GetQuotaConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - quotaType string
func (_e *MockRepository_Expecter) GetQuotaConfig(ctx interface{}, quotaType interface{}) *MockRepository_GetQuotaConfig_Call {
	return &MockRepository_GetQuotaConfig_Call{Call: _e.mock.On("GetQuotaConfig", ctx, quotaType)}
}

func (_c *MockRepository_GetQuotaConfig_Call) Run(run func(ctx context.Context, quotaType string)) *MockRepository_GetQuotaConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_GetQuotaConfig_Call) Return(_a0 *quota.QuotaConfig, _a1 error) *MockRepository_GetQuotaConfig_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetQuotaConfig_Call) RunAndReturn(run func(context.Context, string) (*quota.QuotaConfig, error)) *MockRepository_GetQuotaConfig_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementDailyUsage provides a mock function with given fields: ctx, userID, date, quotaKey, amount
func (_m *MockRepository) IncrementDailyUsage(ctx context.Context, userID int, date string, quotaKey string, amount int) error {
	ret := _m.Called(ctx, userID, date, quotaKey, amount)

	if len(ret) == 0 {
		panic("no return value specified for IncrementDailyUsage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string, string, int) error); ok {
		r0 = rf(ctx, userID, date, quotaKey, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_IncrementDailyUsage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementDailyUsage'
type MockRepository_IncrementDailyUsage_Call struct {
	*mock.Call
}

// IncrementDailyUsage is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - date string
//   - quotaKey string
//   - amount int
func (_e *MockRepository_Expecter) IncrementDailyUsage(ctx interface{}, userID interface{}, date interface{}, quotaKey interface{}, amount interface{}) *MockRepository_IncrementDailyUsage_Call {
	return &MockRepository_IncrementDailyUsage_Call{Call: _e.mock.On("IncrementDailyUsage", ctx, userID, date, quotaKey, amount)}
}

func (_c *MockRepository_IncrementDailyUsage_Call) Run(run func(ctx context.Context, userID int, date string, quotaKey string, amount int)) *MockRepository_IncrementDailyUsage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(string), args[3].(string), args[4].(int))
	})
	return _c
}

func (_c *MockRepository_IncrementDailyUsage_Call) Return(_a0 error) *MockRepository_IncrementDailyUsage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_IncrementDailyUsage_Call) RunAndReturn(run func(context.Context, int, string, string, int) error) *MockRepository_IncrementDailyUsage_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementMonthlyUsage provides a mock function with given fields: ctx, userID, monthYear
func (_m *MockRepository) IncrementMonthlyUsage(ctx context.Context, userID int, monthYear string) error {
	ret := _m.Called(ctx, userID, monthYear)

	if len(ret) == 0 {
		panic("no return value specified for IncrementMonthlyUsage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string) error); ok {
		r0 = rf(ctx, userID, monthYear)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_IncrementMonthlyUsage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementMonthlyUsage'
type MockRepository_IncrementMonthlyUsage_Call struct {
	*mock.Call
}

// IncrementMonthlyUsage is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - monthYear string
func (_e *MockRepository_Expecter) IncrementMonthlyUsage(ctx interface{}, userID interface{}, monthYear interface{}) *MockRepository_IncrementMonthlyUsage_Call {
	return &MockRepository_IncrementMonthlyUsage_Call{Call: _e.mock.On("IncrementMonthlyUsage", ctx, userID, monthYear)}
}

func (_c *MockRepository_IncrementMonthlyUsage_Call) Run(run func(ctx context.Context, userID int, monthYear string)) *MockRepository_IncrementMonthlyUsage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(string))
	})
	return _c
}

func (_c *MockRepository_IncrementMonthlyUsage_Call) Return(_a0 error) *MockRepository_IncrementMonthlyUsage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_IncrementMonthlyUsage_Call) RunAndReturn(run func(context.Context, int, string) error) *MockRepository_IncrementMonthlyUsage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
