// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/benidevo/vega/internal/documents/models"
	mock "github.com/stretchr/testify/mock"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// CheckDocumentExists provides a mock function with given fields: ctx, userID, jobID, docType
func (_m *MockService) CheckDocumentExists(ctx context.Context, userID int, jobID int, docType models.DocumentType) (bool, error) {
	ret := _m.Called(ctx, userID, jobID, docType)

	if len(ret) == 0 {
		panic("no return value specified for CheckDocumentExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, models.DocumentType) (bool, error)); ok {
		return rf(ctx, userID, jobID, docType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, models.DocumentType) bool); ok {
		r0 = rf(ctx, userID, jobID, docType)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, models.DocumentType) error); ok {
		r1 = rf(ctx, userID, jobID, docType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_CheckDocumentExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckDocumentExists'
type MockService_CheckDocumentExists_Call struct {
	*mock.Call
}

// CheckDocumentExists is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - jobID int
//   - docType models.DocumentType
func (_e *MockService_Expecter) CheckDocumentExists(ctx interface{}, userID interface{}, jobID interface{}, docType interface{}) *MockService_CheckDocumentExists_Call {
	return &MockService_CheckDocumentExists_Call{Call: _e.mock.On("CheckDocumentExists", ctx, userID, jobID, docType)}
}

func (_c *MockService_CheckDocumentExists_Call) Run(run func(ctx context.Context, userID int, jobID int, docType models.DocumentType)) *MockService_CheckDocumentExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int), args[3].(models.DocumentType))
	})
	return _c
}

func (_c *MockService_CheckDocumentExists_Call) Return(_a0 bool, _a1 error) *MockService_CheckDocumentExists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_CheckDocumentExists_Call) RunAndReturn(run func(context.Context, int, int, models.DocumentType) (bool, error)) *MockService_CheckDocumentExists_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteDocument provides a mock function with given fields: ctx, docID, userID
func (_m *MockService) DeleteDocument(ctx context.Context, docID int, userID int) error {
	ret := _m.Called(ctx, docID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDocument")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, docID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_DeleteDocument_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteDocument'
type MockService_DeleteDocument_Call struct {
	*mock.Call
}

// DeleteDocument is a helper method to define mock.On call
//   - ctx context.Context
//   - docID int
//   - userID int
func (_e *MockService_Expecter) DeleteDocument(ctx interface{}, docID interface{}, userID interface{}) *MockService_DeleteDocument_Call {
	return &MockService_DeleteDocument_Call{Call: _e.mock.On("DeleteDocument", ctx, docID, userID)}
}

func (_c *MockService_DeleteDocument_Call) Run(run func(ctx context.Context, docID int, userID int)) *MockService_DeleteDocument_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockService_DeleteDocument_Call) Return(_a0 error) *MockService_DeleteDocument_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_DeleteDocument_Call) RunAndReturn(run func(context.Context, int, int) error) *MockService_DeleteDocument_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllDocuments provides a mock function with given fields: ctx, userID, page, pageSize
func (_m *MockService) GetAllDocuments(ctx context.Context, userID int, page int, pageSize int) ([]*models.DocumentSummary, int, error) {
	ret := _m.Called(ctx, userID, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for GetAllDocuments")
	}

	var r0 []*models.DocumentSummary
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int) ([]*models.DocumentSummary, int, error)); ok {
		return rf(ctx, userID, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int) []*models.DocumentSummary); ok {
		r0 = rf(ctx, userID, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.DocumentSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, int) int); ok {
		r1 = rf(ctx, userID, page, pageSize)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int, int) error); ok {
		r2 = rf(ctx, userID, page, pageSize)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockService_GetAllDocuments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllDocuments'
type MockService_GetAllDocuments_Call struct {
	*mock.Call
}

// GetAllDocuments is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - page int
//   - pageSize int
func (_e *MockService_Expecter) GetAllDocuments(ctx interface{}, userID interface{}, page interface{}, pageSize interface{}) *MockService_GetAllDocuments_Call {
	return &MockService_GetAllDocuments_Call{Call: _e.mock.On("GetAllDocuments", ctx, userID, page, pageSize)}
}

func (_c *MockService_GetAllDocuments_Call) Run(run func(ctx context.Context, userID int, page int, pageSize int)) *MockService_GetAllDocuments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockService_GetAllDocuments_Call) Return(_a0 []*models.DocumentSummary, _a1 int, _a2 error) *MockService_GetAllDocuments_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockService_GetAllDocuments_Call) RunAndReturn(run func(context.Context, int, int, int) ([]*models.DocumentSummary, int, error)) *MockService_GetAllDocuments_Call {
	_c.Call.Return(run)
	return _c
}

// GetDocument provides a mock function with given fields: ctx, docID, userID
func (_m *MockService) GetDocument(ctx context.Context, docID int, userID int) (*models.Document, error) {
	ret := _m.Called(ctx, docID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetDocument")
	}

	var r0 *models.Document
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) (*models.Document, error)); ok {
		return rf(ctx, docID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) *models.Document); ok {
		r0 = rf(ctx, docID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Document)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, docID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetDocument_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDocument'
type MockService_GetDocument_Call struct {
	*mock.Call
}

// GetDocument is a helper method to define mock.On call
//   - ctx context.Context
//   - docID int
//   - userID int
func (_e *MockService_Expecter) GetDocument(ctx interface{}, docID interface{}, userID interface{}) *MockService_GetDocument_Call {
	return &MockService_GetDocument_Call{Call: _e.mock.On("GetDocument", ctx, docID, userID)}
}

func (_c *MockService_GetDocument_Call) Run(run func(ctx context.Context, docID int, userID int)) *MockService_GetDocument_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockService_GetDocument_Call) Return(_a0 *models.Document, _a1 error) *MockService_GetDocument_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetDocument_Call) RunAndReturn(run func(context.Context, int, int) (*models.Document, error)) *MockService_GetDocument_Call {
	_c.Call.Return(run)
	return _c
}

// GetDocumentByJobAndType provides a mock function with given fields: ctx, userID, jobID, docType
func (_m *MockService) GetDocumentByJobAndType(ctx context.Context, userID int, jobID int, docType models.DocumentType) (*models.Document, error) {
	ret := _m.Called(ctx, userID, jobID, docType)

	if len(ret) == 0 {
		panic("no return value specified for GetDocumentByJobAndType")
	}

	var r0 *models.Document
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, models.DocumentType) (*models.Document, error)); ok {
		return rf(ctx, userID, jobID, docType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, models.DocumentType) *models.Document); ok {
		r0 = rf(ctx, userID, jobID, docType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Document)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, models.DocumentType) error); ok {
		r1 = rf(ctx, userID, jobID, docType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetDocumentByJobAndType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDocumentByJobAndType'
type MockService_GetDocumentByJobAndType_Call struct {
	*mock.Call
}

// GetDocumentByJobAndType is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - jobID int
//   - docType models.DocumentType
func (_e *MockService_Expecter) GetDocumentByJobAndType(ctx interface{}, userID interface{}, jobID interface{}, docType interface{}) *MockService_GetDocumentByJobAndType_Call {
	return &MockService_GetDocumentByJobAndType_Call{Call: _e.mock.On("GetDocumentByJobAndType", ctx, userID, jobID, docType)}
}

func (_c *MockService_GetDocumentByJobAndType_Call) Run(run func(ctx context.Context, userID int, jobID int, docType models.DocumentType)) *MockService_GetDocumentByJobAndType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int), args[3].(models.DocumentType))
	})
	return _c
}

func (_c *MockService_GetDocumentByJobAndType_Call) Return(_a0 *models.Document, _a1 error) *MockService_GetDocumentByJobAndType_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetDocumentByJobAndType_Call) RunAndReturn(run func(context.Context, int, int, models.DocumentType) (*models.Document, error)) *MockService_GetDocumentByJobAndType_Call {
	_c.Call.Return(run)
	return _c
}

// GetDocumentMetrics provides a mock function with given fields: ctx, userID
func (_m *MockService) GetDocumentMetrics(ctx context.Context, userID int) (*models.DocumentMetrics, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetDocumentMetrics")
	}

	var r0 *models.DocumentMetrics
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*models.DocumentMetrics, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *models.DocumentMetrics); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.DocumentMetrics)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetDocumentMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDocumentMetrics'
type MockService_GetDocumentMetrics_Call struct {
	*mock.Call
}

// GetDocumentMetrics is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockService_Expecter) GetDocumentMetrics(ctx interface{}, userID interface{}) *MockService_GetDocumentMetrics_Call {
	return &MockService_GetDocumentMetrics_Call{Call: _e.mock.On("GetDocumentMetrics", ctx, userID)}
}

func (_c *MockService_GetDocumentMetrics_Call) Run(run func(ctx context.Context, userID int)) *MockService_GetDocumentMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockService_GetDocumentMetrics_Call) Return(_a0 *models.DocumentMetrics, _a1 error) *MockService_GetDocumentMetrics_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetDocumentMetrics_Call) RunAndReturn(run func(context.Context, int) (*models.DocumentMetrics, error)) *MockService_GetDocumentMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// GetDocumentsByJob provides a mock function with given fields: ctx, userID, jobID
func (_m *MockService) GetDocumentsByJob(ctx context.Context, userID int, jobID int) ([]*models.Document, error) {
	ret := _m.Called(ctx, userID, jobID)

	if len(ret) == 0 {
		panic("no return value specified for GetDocumentsByJob")
	}

	var r0 []*models.Document
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]*models.Document, error)); ok {
		return rf(ctx, userID, jobID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []*models.Document); ok {
		r0 = rf(ctx, userID, jobID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Document)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, userID, jobID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetDocumentsByJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDocumentsByJob'
type MockService_GetDocumentsByJob_Call struct {
	*mock.Call
}

// GetDocumentsByJob is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - jobID int
func (_e *MockService_Expecter) GetDocumentsByJob(ctx interface{}, userID interface{}, jobID interface{}) *MockService_GetDocumentsByJob_Call {
	return &MockService_GetDocumentsByJob_Call{Call: _e.mock.On("GetDocumentsByJob", ctx, userID, jobID)}
}

func (_c *MockService_GetDocumentsByJob_Call) Run(run func(ctx context.Context, userID int, jobID int)) *MockService_GetDocumentsByJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockService_GetDocumentsByJob_Call) Return(_a0 []*models.Document, _a1 error) *MockService_GetDocumentsByJob_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetDocumentsByJob_Call) RunAndReturn(run func(context.Context, int, int) ([]*models.Document, error)) *MockService_GetDocumentsByJob_Call {
	_c.Call.Return(run)
	return _c
}

// GetDocumentsByType provides a mock function with given fields: ctx, userID, docType, page, pageSize
func (_m *MockService) GetDocumentsByType(ctx context.Context, userID int, docType models.DocumentType, page int, pageSize int) ([]*models.DocumentSummary, int, error) {
	ret := _m.Called(ctx, userID, docType, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for GetDocumentsByType")
	}

	var r0 []*models.DocumentSummary
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, models.DocumentType, int, int) ([]*models.DocumentSummary, int, error)); ok {
		return rf(ctx, userID, docType, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, models.DocumentType, int, int) []*models.DocumentSummary); ok {
		r0 = rf(ctx, userID, docType, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.DocumentSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, models.DocumentType, int, int) int); ok {
		r1 = rf(ctx, userID, docType, page, pageSize)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, models.DocumentType, int, int) error); ok {
		r2 = rf(ctx, userID, docType, page, pageSize)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockService_GetDocumentsByType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDocumentsByType'
type MockService_GetDocumentsByType_Call struct {
	*mock.Call
}

// GetDocumentsByType is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - docType models.DocumentType
//   - page int
//   - pageSize int
func (_e *MockService_Expecter) GetDocumentsByType(ctx interface{}, userID interface{}, docType interface{}, page interface{}, pageSize interface{}) *MockService_GetDocumentsByType_Call {
	return &MockService_GetDocumentsByType_Call{Call: _e.mock.On("GetDocumentsByType", ctx, userID, docType, page, pageSize)}
}

func (_c *MockService_GetDocumentsByType_Call) Run(run func(ctx context.Context, userID int, docType models.DocumentType, page int, pageSize int)) *MockService_GetDocumentsByType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(models.DocumentType), args[3].(int), args[4].(int))
	})
	return _c
}

func (_c *MockService_GetDocumentsByType_Call) Return(_a0 []*models.DocumentSummary, _a1 int, _a2 error) *MockService_GetDocumentsByType_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockService_GetDocumentsByType_Call) RunAndReturn(run func(context.Context, int, models.DocumentType, int, int) ([]*models.DocumentSummary, int, error)) *MockService_GetDocumentsByType_Call {
	_c.Call.Return(run)
	return _c
}

// SaveGeneratedDocument provides a mock function with given fields: ctx, userID, jobID, docType, content
func (_m *MockService) SaveGeneratedDocument(ctx context.Context, userID int, jobID int, docType models.DocumentType, content string) (*models.Document, error) {
	ret := _m.Called(ctx, userID, jobID, docType, content)

	if len(ret) == 0 {
		panic("no return value specified for SaveGeneratedDocument")
	}

	var r0 *models.Document
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, models.DocumentType, string) (*models.Document, error)); ok {
		return rf(ctx, userID, jobID, docType, content)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, models.DocumentType, string) *models.Document); ok {
		r0 = rf(ctx, userID, jobID, docType, content)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Document)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, models.DocumentType, string) error); ok {
		r1 = rf(ctx, userID, jobID, docType, content)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_SaveGeneratedDocument_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveGeneratedDocument'
type MockService_SaveGeneratedDocument_Call struct {
	*mock.Call
}

// SaveGeneratedDocument is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - jobID int
//   - docType models.DocumentType
//   - content string
func (_e *MockService_Expecter) SaveGeneratedDocument(ctx interface{}, userID interface{}, jobID interface{}, docType interface{}, content interface{}) *MockService_SaveGeneratedDocument_Call {
	return &MockService_SaveGeneratedDocument_Call{Call: _e.mock.On("SaveGeneratedDocument", ctx, userID, jobID, docType, content)}
}

func (_c *MockService_SaveGeneratedDocument_Call) Run(run func(ctx context.Context, userID int, jobID int, docType models.DocumentType, content string)) *MockService_SaveGeneratedDocument_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int), args[3].(models.DocumentType), args[4].(string))
	})
	return _c
}

func (_c *MockService_SaveGeneratedDocument_Call) Return(_a0 *models.Document, _a1 error) *MockService_SaveGeneratedDocument_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_SaveGeneratedDocument_Call) RunAndReturn(run func(context.Context, int, int, models.DocumentType, string) (*models.Document, error)) *MockService_SaveGeneratedDocument_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
