// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/benidevo/vega/internal/settings/models"
	mock "github.com/stretchr/testify/mock"
)

// MockSettingsRepository is an autogenerated mock type for the SettingsRepository type
type MockSettingsRepository struct {
	mock.Mock
}

type MockSettingsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSettingsRepository) EXPECT() *MockSettingsRepository_Expecter {
	return &MockSettingsRepository_Expecter{mock: &_m.Mock}
}

// AddCertification provides a mock function with given fields: ctx, certification
func (_m *MockSettingsRepository) AddCertification(ctx context.Context, certification *models.Certification) error {
	ret := _m.Called(ctx, certification)

	if len(ret) == 0 {
		panic("no return value specified for AddCertification")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Certification) error); ok {
		r0 = rf(ctx, certification)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSettingsRepository_AddCertification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddCertification'
type MockSettingsRepository_AddCertification_Call struct {
	*mock.Call
}

// AddCertification is a helper method to define mock.On call
//   - ctx context.Context
//   - certification *models.Certification
func (_e *MockSettingsRepository_Expecter) AddCertification(ctx interface{}, certification interface{}) *MockSettingsRepository_AddCertification_Call {
	return &MockSettingsRepository_AddCertification_Call{Call: _e.mock.On("AddCertification", ctx, certification)}
}

func (_c *MockSettingsRepository_AddCertification_Call) Run(run func(ctx context.Context, certification *models.Certification)) *MockSettingsRepository_AddCertification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Certification))
	})
	return _c
}

func (_c *MockSettingsRepository_AddCertification_Call) Return(_a0 error) *MockSettingsRepository_AddCertification_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSettingsRepository_AddCertification_Call) RunAndReturn(run func(context.Context, *models.Certification) error) *MockSettingsRepository_AddCertification_Call {
	_c.Call.Return(run)
	return _c
}

// AddEducation provides a mock function with given fields: ctx, education
func (_m *MockSettingsRepository) AddEducation(ctx context.Context, education *models.Education) error {
	ret := _m.Called(ctx, education)

	if len(ret) == 0 {
		panic("no return value specified for AddEducation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Education) error); ok {
		r0 = rf(ctx, education)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSettingsRepository_AddEducation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddEducation'
type MockSettingsRepository_AddEducation_Call struct {
	*mock.Call
}

// AddEducation is a helper method to define mock.On call
//   - ctx context.Context
//   - education *models.Education
func (_e *MockSettingsRepository_Expecter) AddEducation(ctx interface{}, education interface{}) *MockSettingsRepository_AddEducation_Call {
	return &MockSettingsRepository_AddEducation_Call{Call: _e.mock.On("AddEducation", ctx, education)}
}

func (_c *MockSettingsRepository_AddEducation_Call) Run(run func(ctx context.Context, education *models.Education)) *MockSettingsRepository_AddEducation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Education))
	})
	return _c
}

func (_c *MockSettingsRepository_AddEducation_Call) Return(_a0 error) *MockSettingsRepository_AddEducation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSettingsRepository_AddEducation_Call) RunAndReturn(run func(context.Context, *models.Education) error) *MockSettingsRepository_AddEducation_Call {
	_c.Call.Return(run)
	return _c
}

// AddWorkExperience provides a mock function with given fields: ctx, experience
func (_m *MockSettingsRepository) AddWorkExperience(ctx context.Context, experience *models.WorkExperience) error {
	ret := _m.Called(ctx, experience)

	if len(ret) == 0 {
		panic("no return value specified for AddWorkExperience")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.WorkExperience) error); ok {
		r0 = rf(ctx, experience)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSettingsRepository_AddWorkExperience_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddWorkExperience'
type MockSettingsRepository_AddWorkExperience_Call struct {
	*mock.Call
}

// AddWorkExperience is a helper method to define mock.On call
//   - ctx context.Context
//   - experience *models.WorkExperience
func (_e *MockSettingsRepository_Expecter) AddWorkExperience(ctx interface{}, experience interface{}) *MockSettingsRepository_AddWorkExperience_Call {
	return &MockSettingsRepository_AddWorkExperience_Call{Call: _e.mock.On("AddWorkExperience", ctx, experience)}
}

func (_c *MockSettingsRepository_AddWorkExperience_Call) Run(run func(ctx context.Context, experience *models.WorkExperience)) *MockSettingsRepository_AddWorkExperience_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.WorkExperience))
	})
	return _c
}

func (_c *MockSettingsRepository_AddWorkExperience_Call) Return(_a0 error) *MockSettingsRepository_AddWorkExperience_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSettingsRepository_AddWorkExperience_Call) RunAndReturn(run func(context.Context, *models.WorkExperience) error) *MockSettingsRepository_AddWorkExperience_Call {
	_c.Call.Return(run)
	return _c
}

// CreateProfileIfNotExists provides a mock function with given fields: ctx, userID
func (_m *MockSettingsRepository) CreateProfileIfNotExists(ctx context.Context, userID int) (*models.Profile, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CreateProfileIfNotExists")
	}

	var r0 *models.Profile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*models.Profile, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *models.Profile); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Profile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSettingsRepository_CreateProfileIfNotExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProfileIfNotExists'
type MockSettingsRepository_CreateProfileIfNotExists_Call struct {
	*mock.Call
}

// CreateProfileIfNotExists is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockSettingsRepository_Expecter) CreateProfileIfNotExists(ctx interface{}, userID interface{}) *MockSettingsRepository_CreateProfileIfNotExists_Call {
	return &MockSettingsRepository_CreateProfileIfNotExists_Call{Call: _e.mock.On("CreateProfileIfNotExists", ctx, userID)}
}

func (_c *MockSettingsRepository_CreateProfileIfNotExists_Call) Run(run func(ctx context.Context, userID int)) *MockSettingsRepository_CreateProfileIfNotExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockSettingsRepository_CreateProfileIfNotExists_Call) Return(_a0 *models.Profile, _a1 error) *MockSettingsRepository_CreateProfileIfNotExists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSettingsRepository_CreateProfileIfNotExists_Call) RunAndReturn(run func(context.Context, int) (*models.Profile, error)) *MockSettingsRepository_CreateProfileIfNotExists_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAllCertifications provides a mock function with given fields: ctx, profileID
func (_m *MockSettingsRepository) DeleteAllCertifications(ctx context.Context, profileID int) error {
	ret := _m.Called(ctx, profileID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAllCertifications")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, profileID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSettingsRepository_DeleteAllCertifications_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAllCertifications'
type MockSettingsRepository_DeleteAllCertifications_Call struct {
	*mock.Call
}

// DeleteAllCertifications is a helper method to define mock.On call
//   - ctx context.Context
//   - profileID int
func (_e *MockSettingsRepository_Expecter) DeleteAllCertifications(ctx interface{}, profileID interface{}) *MockSettingsRepository_DeleteAllCertifications_Call {
	return &MockSettingsRepository_DeleteAllCertifications_Call{Call: _e.mock.On("DeleteAllCertifications", ctx, profileID)}
}

func (_c *MockSettingsRepository_DeleteAllCertifications_Call) Run(run func(ctx context.Context, profileID int)) *MockSettingsRepository_DeleteAllCertifications_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockSettingsRepository_DeleteAllCertifications_Call) Return(_a0 error) *MockSettingsRepository_DeleteAllCertifications_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSettingsRepository_DeleteAllCertifications_Call) RunAndReturn(run func(context.Context, int) error) *MockSettingsRepository_DeleteAllCertifications_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAllEducation provides a mock function with given fields: ctx, profileID
func (_m *MockSettingsRepository) DeleteAllEducation(ctx context.Context, profileID int) error {
	ret := _m.Called(ctx, profileID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAllEducation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, profileID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSettingsRepository_DeleteAllEducation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAllEducation'
type MockSettingsRepository_DeleteAllEducation_Call struct {
	*mock.Call
}

// DeleteAllEducation is a helper method to define mock.On call
//   - ctx context.Context
//   - profileID int
func (_e *MockSettingsRepository_Expecter) DeleteAllEducation(ctx interface{}, profileID interface{}) *MockSettingsRepository_DeleteAllEducation_Call {
	return &MockSettingsRepository_DeleteAllEducation_Call{Call: _e.mock.On("DeleteAllEducation", ctx, profileID)}
}

func (_c *MockSettingsRepository_DeleteAllEducation_Call) Run(run func(ctx context.Context, profileID int)) *MockSettingsRepository_DeleteAllEducation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockSettingsRepository_DeleteAllEducation_Call) Return(_a0 error) *MockSettingsRepository_DeleteAllEducation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSettingsRepository_DeleteAllEducation_Call) RunAndReturn(run func(context.Context, int) error) *MockSettingsRepository_DeleteAllEducation_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAllWorkExperience provides a mock function with given fields: ctx, profileID
func (_m *MockSettingsRepository) DeleteAllWorkExperience(ctx context.Context, profileID int) error {
	ret := _m.Called(ctx, profileID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAllWorkExperience")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, profileID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSettingsRepository_DeleteAllWorkExperience_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAllWorkExperience'
type MockSettingsRepository_DeleteAllWorkExperience_Call struct {
	*mock.Call
}

// DeleteAllWorkExperience is a helper method to define mock.On call
//   - ctx context.Context
//   - profileID int
func (_e *MockSettingsRepository_Expecter) DeleteAllWorkExperience(ctx interface{}, profileID interface{}) *MockSettingsRepository_DeleteAllWorkExperience_Call {
	return &MockSettingsRepository_DeleteAllWorkExperience_Call{Call: _e.mock.On("DeleteAllWorkExperience", ctx, profileID)}
}

func (_c *MockSettingsRepository_DeleteAllWorkExperience_Call) Run(run func(ctx context.Context, profileID int)) *MockSettingsRepository_DeleteAllWorkExperience_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockSettingsRepository_DeleteAllWorkExperience_Call) Return(_a0 error) *MockSettingsRepository_DeleteAllWorkExperience_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSettingsRepository_DeleteAllWorkExperience_Call) RunAndReturn(run func(context.Context, int) error) *MockSettingsRepository_DeleteAllWorkExperience_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCertification provides a mock function with given fields: ctx, id, profileID
func (_m *MockSettingsRepository) DeleteCertification(ctx context.Context, id int, profileID int) error {
	ret := _m.Called(ctx, id, profileID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCertification")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, id, profileID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSettingsRepository_DeleteCertification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCertification'
type MockSettingsRepository_DeleteCertification_Call struct {
	*mock.Call
}

// DeleteCertification is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
//   - profileID int
func (_e *MockSettingsRepository_Expecter) DeleteCertification(ctx interface{}, id interface{}, profileID interface{}) *MockSettingsRepository_DeleteCertification_Call {
	return &MockSettingsRepository_DeleteCertification_Call{Call: _e.mock.On("DeleteCertification", ctx, id, profileID)}
}

func (_c *MockSettingsRepository_DeleteCertification_Call) Run(run func(ctx context.Context, id int, profileID int)) *MockSettingsRepository_DeleteCertification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockSettingsRepository_DeleteCertification_Call) Return(_a0 error) *MockSettingsRepository_DeleteCertification_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSettingsRepository_DeleteCertification_Call) RunAndReturn(run func(context.Context, int, int) error) *MockSettingsRepository_DeleteCertification_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteEducation provides a mock function with given fields: ctx, id, profileID
func (_m *MockSettingsRepository) DeleteEducation(ctx context.Context, id int, profileID int) error {
	ret := _m.Called(ctx, id, profileID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteEducation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, id, profileID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSettingsRepository_DeleteEducation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteEducation'
type MockSettingsRepository_DeleteEducation_Call struct {
	*mock.Call
}

// DeleteEducation is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
//   - profileID int
func (_e *MockSettingsRepository_Expecter) DeleteEducation(ctx interface{}, id interface{}, profileID interface{}) *MockSettingsRepository_DeleteEducation_Call {
	return &MockSettingsRepository_DeleteEducation_Call{Call: _e.mock.On("DeleteEducation", ctx, id, profileID)}
}

func (_c *MockSettingsRepository_DeleteEducation_Call) Run(run func(ctx context.Context, id int, profileID int)) *MockSettingsRepository_DeleteEducation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockSettingsRepository_DeleteEducation_Call) Return(_a0 error) *MockSettingsRepository_DeleteEducation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSettingsRepository_DeleteEducation_Call) RunAndReturn(run func(context.Context, int, int) error) *MockSettingsRepository_DeleteEducation_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteWorkExperience provides a mock function with given fields: ctx, id, profileID
func (_m *MockSettingsRepository) DeleteWorkExperience(ctx context.Context, id int, profileID int) error {
	ret := _m.Called(ctx, id, profileID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteWorkExperience")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, id, profileID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSettingsRepository_DeleteWorkExperience_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteWorkExperience'
type MockSettingsRepository_DeleteWorkExperience_Call struct {
	*mock.Call
}

// DeleteWorkExperience is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
//   - profileID int
func (_e *MockSettingsRepository_Expecter) DeleteWorkExperience(ctx interface{}, id interface{}, profileID interface{}) *MockSettingsRepository_DeleteWorkExperience_Call {
	return &MockSettingsRepository_DeleteWorkExperience_Call{Call: _e.mock.On("DeleteWorkExperience", ctx, id, profileID)}
}

func (_c *MockSettingsRepository_DeleteWorkExperience_Call) Run(run func(ctx context.Context, id int, profileID int)) *MockSettingsRepository_DeleteWorkExperience_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockSettingsRepository_DeleteWorkExperience_Call) Return(_a0 error) *MockSettingsRepository_DeleteWorkExperience_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSettingsRepository_DeleteWorkExperience_Call) RunAndReturn(run func(context.Context, int, int) error) *MockSettingsRepository_DeleteWorkExperience_Call {
	_c.Call.Return(run)
	return _c
}

// GetCertifications provides a mock function with given fields: ctx, profileID
func (_m *MockSettingsRepository) GetCertifications(ctx context.Context, profileID int) ([]models.Certification, error) {
	ret := _m.Called(ctx, profileID)

	if len(ret) == 0 {
		panic("no return value specified for GetCertifications")
	}

	var r0 []models.Certification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]models.Certification, error)); ok {
		return rf(ctx, profileID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []models.Certification); ok {
		r0 = rf(ctx, profileID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Certification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, profileID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSettingsRepository_GetCertifications_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCertifications'
type MockSettingsRepository_GetCertifications_Call struct {
	*mock.Call
}

// GetCertifications is a helper method to define mock.On call
//   - ctx context.Context
//   - profileID int
func (_e *MockSettingsRepository_Expecter) GetCertifications(ctx interface{}, profileID interface{}) *MockSettingsRepository_GetCertifications_Call {
	return &MockSettingsRepository_GetCertifications_Call{Call: _e.mock.On("GetCertifications", ctx, profileID)}
}

func (_c *MockSettingsRepository_GetCertifications_Call) Run(run func(ctx context.Context, profileID int)) *MockSettingsRepository_GetCertifications_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockSettingsRepository_GetCertifications_Call) Return(_a0 []models.Certification, _a1 error) *MockSettingsRepository_GetCertifications_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSettingsRepository_GetCertifications_Call) RunAndReturn(run func(context.Context, int) ([]models.Certification, error)) *MockSettingsRepository_GetCertifications_Call {
	_c.Call.Return(run)
	return _c
}

// GetEducation provides a mock function with given fields: ctx, profileID
func (_m *MockSettingsRepository) GetEducation(ctx context.Context, profileID int) ([]models.Education, error) {
	ret := _m.Called(ctx, profileID)

	if len(ret) == 0 {
		panic("no return value specified for GetEducation")
	}

	var r0 []models.Education
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]models.Education, error)); ok {
		return rf(ctx, profileID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []models.Education); ok {
		r0 = rf(ctx, profileID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Education)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, profileID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSettingsRepository_GetEducation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEducation'
type MockSettingsRepository_GetEducation_Call struct {
	*mock.Call
}

// GetEducation is a helper method to define mock.On call
//   - ctx context.Context
//   - profileID int
func (_e *MockSettingsRepository_Expecter) GetEducation(ctx interface{}, profileID interface{}) *MockSettingsRepository_GetEducation_Call {
	return &MockSettingsRepository_GetEducation_Call{Call: _e.mock.On("GetEducation", ctx, profileID)}
}

func (_c *MockSettingsRepository_GetEducation_Call) Run(run func(ctx context.Context, profileID int)) *MockSettingsRepository_GetEducation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockSettingsRepository_GetEducation_Call) Return(_a0 []models.Education, _a1 error) *MockSettingsRepository_GetEducation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSettingsRepository_GetEducation_Call) RunAndReturn(run func(context.Context, int) ([]models.Education, error)) *MockSettingsRepository_GetEducation_Call {
	_c.Call.Return(run)
	return _c
}

// GetEntityByID provides a mock function with given fields: ctx, entityID, profileID, entityType
func (_m *MockSettingsRepository) GetEntityByID(ctx context.Context, entityID int, profileID int, entityType string) (interface{}, error) {
	ret := _m.Called(ctx, entityID, profileID, entityType)

	if len(ret) == 0 {
		panic("no return value specified for GetEntityByID")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string) (interface{}, error)); ok {
		return rf(ctx, entityID, profileID, entityType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string) interface{}); ok {
		r0 = rf(ctx, entityID, profileID, entityType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, string) error); ok {
		r1 = rf(ctx, entityID, profileID, entityType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSettingsRepository_GetEntityByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEntityByID'
type MockSettingsRepository_GetEntityByID_Call struct {
	*mock.Call
}

// GetEntityByID is a helper method to define mock.On call
//   - ctx context.Context
//   - entityID int
//   - profileID int
//   - entityType string
func (_e *MockSettingsRepository_Expecter) GetEntityByID(ctx interface{}, entityID interface{}, profileID interface{}, entityType interface{}) *MockSettingsRepository_GetEntityByID_Call {
	return &MockSettingsRepository_GetEntityByID_Call{Call: _e.mock.On("GetEntityByID", ctx, entityID, profileID, entityType)}
}

func (_c *MockSettingsRepository_GetEntityByID_Call) Run(run func(ctx context.Context, entityID int, profileID int, entityType string)) *MockSettingsRepository_GetEntityByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int), args[3].(string))
	})
	return _c
}

func (_c *MockSettingsRepository_GetEntityByID_Call) Return(_a0 interface{}, _a1 error) *MockSettingsRepository_GetEntityByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSettingsRepository_GetEntityByID_Call) RunAndReturn(run func(context.Context, int, int, string) (interface{}, error)) *MockSettingsRepository_GetEntityByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetProfile provides a mock function with given fields: ctx, userID
func (_m *MockSettingsRepository) GetProfile(ctx context.Context, userID int) (*models.Profile, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetProfile")
	}

	var r0 *models.Profile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*models.Profile, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *models.Profile); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Profile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSettingsRepository_GetProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfile'
type MockSettingsRepository_GetProfile_Call struct {
	*mock.Call
}

// GetProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockSettingsRepository_Expecter) GetProfile(ctx interface{}, userID interface{}) *MockSettingsRepository_GetProfile_Call {
	return &MockSettingsRepository_GetProfile_Call{Call: _e.mock.On("GetProfile", ctx, userID)}
}

func (_c *MockSettingsRepository_GetProfile_Call) Run(run func(ctx context.Context, userID int)) *MockSettingsRepository_GetProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockSettingsRepository_GetProfile_Call) Return(_a0 *models.Profile, _a1 error) *MockSettingsRepository_GetProfile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSettingsRepository_GetProfile_Call) RunAndReturn(run func(context.Context, int) (*models.Profile, error)) *MockSettingsRepository_GetProfile_Call {
	_c.Call.Return(run)
	return _c
}

// GetProfileWithRelated provides a mock function with given fields: ctx, userID
func (_m *MockSettingsRepository) GetProfileWithRelated(ctx context.Context, userID int) (*models.Profile, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetProfileWithRelated")
	}

	var r0 *models.Profile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*models.Profile, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *models.Profile); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Profile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSettingsRepository_GetProfileWithRelated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfileWithRelated'
type MockSettingsRepository_GetProfileWithRelated_Call struct {
	*mock.Call
}

// GetProfileWithRelated is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockSettingsRepository_Expecter) GetProfileWithRelated(ctx interface{}, userID interface{}) *MockSettingsRepository_GetProfileWithRelated_Call {
	return &MockSettingsRepository_GetProfileWithRelated_Call{Call: _e.mock.On("GetProfileWithRelated", ctx, userID)}
}

func (_c *MockSettingsRepository_GetProfileWithRelated_Call) Run(run func(ctx context.Context, userID int)) *MockSettingsRepository_GetProfileWithRelated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockSettingsRepository_GetProfileWithRelated_Call) Return(_a0 *models.Profile, _a1 error) *MockSettingsRepository_GetProfileWithRelated_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSettingsRepository_GetProfileWithRelated_Call) RunAndReturn(run func(context.Context, int) (*models.Profile, error)) *MockSettingsRepository_GetProfileWithRelated_Call {
	_c.Call.Return(run)
	return _c
}

// GetWorkExperiences provides a mock function with given fields: ctx, profileID
func (_m *MockSettingsRepository) GetWorkExperiences(ctx context.Context, profileID int) ([]models.WorkExperience, error) {
	ret := _m.Called(ctx, profileID)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkExperiences")
	}

	var r0 []models.WorkExperience
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]models.WorkExperience, error)); ok {
		return rf(ctx, profileID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []models.WorkExperience); ok {
		r0 = rf(ctx, profileID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.WorkExperience)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, profileID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSettingsRepository_GetWorkExperiences_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorkExperiences'
type MockSettingsRepository_GetWorkExperiences_Call struct {
	*mock.Call
}

// GetWorkExperiences is a helper method to define mock.On call
//   - ctx context.Context
//   - profileID int
func (_e *MockSettingsRepository_Expecter) GetWorkExperiences(ctx interface{}, profileID interface{}) *MockSettingsRepository_GetWorkExperiences_Call {
	return &MockSettingsRepository_GetWorkExperiences_Call{Call: _e.mock.On("GetWorkExperiences", ctx, profileID)}
}

func (_c *MockSettingsRepository_GetWorkExperiences_Call) Run(run func(ctx context.Context, profileID int)) *MockSettingsRepository_GetWorkExperiences_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockSettingsRepository_GetWorkExperiences_Call) Return(_a0 []models.WorkExperience, _a1 error) *MockSettingsRepository_GetWorkExperiences_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSettingsRepository_GetWorkExperiences_Call) RunAndReturn(run func(context.Context, int) ([]models.WorkExperience, error)) *MockSettingsRepository_GetWorkExperiences_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCertification provides a mock function with given fields: ctx, certification
func (_m *MockSettingsRepository) UpdateCertification(ctx context.Context, certification *models.Certification) (*models.Certification, error) {
	ret := _m.Called(ctx, certification)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCertification")
	}

	var r0 *models.Certification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Certification) (*models.Certification, error)); ok {
		return rf(ctx, certification)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Certification) *models.Certification); ok {
		r0 = rf(ctx, certification)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Certification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Certification) error); ok {
		r1 = rf(ctx, certification)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSettingsRepository_UpdateCertification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCertification'
type MockSettingsRepository_UpdateCertification_Call struct {
	*mock.Call
}

// UpdateCertification is a helper method to define mock.On call
//   - ctx context.Context
//   - certification *models.Certification
func (_e *MockSettingsRepository_Expecter) UpdateCertification(ctx interface{}, certification interface{}) *MockSettingsRepository_UpdateCertification_Call {
	return &MockSettingsRepository_UpdateCertification_Call{Call: _e.mock.On("UpdateCertification", ctx, certification)}
}

func (_c *MockSettingsRepository_UpdateCertification_Call) Run(run func(ctx context.Context, certification *models.Certification)) *MockSettingsRepository_UpdateCertification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Certification))
	})
	return _c
}

func (_c *MockSettingsRepository_UpdateCertification_Call) Return(_a0 *models.Certification, _a1 error) *MockSettingsRepository_UpdateCertification_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSettingsRepository_UpdateCertification_Call) RunAndReturn(run func(context.Context, *models.Certification) (*models.Certification, error)) *MockSettingsRepository_UpdateCertification_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateEducation provides a mock function with given fields: ctx, education
func (_m *MockSettingsRepository) UpdateEducation(ctx context.Context, education *models.Education) (*models.Education, error) {
	ret := _m.Called(ctx, education)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEducation")
	}

	var r0 *models.Education
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Education) (*models.Education, error)); ok {
		return rf(ctx, education)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Education) *models.Education); ok {
		r0 = rf(ctx, education)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Education)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Education) error); ok {
		r1 = rf(ctx, education)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSettingsRepository_UpdateEducation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateEducation'
type MockSettingsRepository_UpdateEducation_Call struct {
	*mock.Call
}

// UpdateEducation is a helper method to define mock.On call
//   - ctx context.Context
//   - education *models.Education
func (_e *MockSettingsRepository_Expecter) UpdateEducation(ctx interface{}, education interface{}) *MockSettingsRepository_UpdateEducation_Call {
	return &MockSettingsRepository_UpdateEducation_Call{Call: _e.mock.On("UpdateEducation", ctx, education)}
}

func (_c *MockSettingsRepository_UpdateEducation_Call) Run(run func(ctx context.Context, education *models.Education)) *MockSettingsRepository_UpdateEducation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Education))
	})
	return _c
}

func (_c *MockSettingsRepository_UpdateEducation_Call) Return(_a0 *models.Education, _a1 error) *MockSettingsRepository_UpdateEducation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSettingsRepository_UpdateEducation_Call) RunAndReturn(run func(context.Context, *models.Education) (*models.Education, error)) *MockSettingsRepository_UpdateEducation_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProfile provides a mock function with given fields: ctx, profile
func (_m *MockSettingsRepository) UpdateProfile(ctx context.Context, profile *models.Profile) error {
	ret := _m.Called(ctx, profile)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Profile) error); ok {
		r0 = rf(ctx, profile)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSettingsRepository_UpdateProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProfile'
type MockSettingsRepository_UpdateProfile_Call struct {
	*mock.Call
}

// UpdateProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - profile *models.Profile
func (_e *MockSettingsRepository_Expecter) UpdateProfile(ctx interface{}, profile interface{}) *MockSettingsRepository_UpdateProfile_Call {
	return &MockSettingsRepository_UpdateProfile_Call{Call: _e.mock.On("UpdateProfile", ctx, profile)}
}

func (_c *MockSettingsRepository_UpdateProfile_Call) Run(run func(ctx context.Context, profile *models.Profile)) *MockSettingsRepository_UpdateProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Profile))
	})
	return _c
}

func (_c *MockSettingsRepository_UpdateProfile_Call) Return(_a0 error) *MockSettingsRepository_UpdateProfile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSettingsRepository_UpdateProfile_Call) RunAndReturn(run func(context.Context, *models.Profile) error) *MockSettingsRepository_UpdateProfile_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateWorkExperience provides a mock function with given fields: ctx, experience
func (_m *MockSettingsRepository) UpdateWorkExperience(ctx context.Context, experience *models.WorkExperience) (*models.WorkExperience, error) {
	ret := _m.Called(ctx, experience)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWorkExperience")
	}

	var r0 *models.WorkExperience
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.WorkExperience) (*models.WorkExperience, error)); ok {
		return rf(ctx, experience)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.WorkExperience) *models.WorkExperience); ok {
		r0 = rf(ctx, experience)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.WorkExperience)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.WorkExperience) error); ok {
		r1 = rf(ctx, experience)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSettingsRepository_UpdateWorkExperience_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateWorkExperience'
type MockSettingsRepository_UpdateWorkExperience_Call struct {
	*mock.Call
}

// UpdateWorkExperience is a helper method to define mock.On call
//   - ctx context.Context
//   - experience *models.WorkExperience
func (_e *MockSettingsRepository_Expecter) UpdateWorkExperience(ctx interface{}, experience interface{}) *MockSettingsRepository_UpdateWorkExperience_Call {
	return &MockSettingsRepository_UpdateWorkExperience_Call{Call: _e.mock.On("UpdateWorkExperience", ctx, experience)}
}

func (_c *MockSettingsRepository_UpdateWorkExperience_Call) Run(run func(ctx context.Context, experience *models.WorkExperience)) *MockSettingsRepository_UpdateWorkExperience_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.WorkExperience))
	})
	return _c
}

func (_c *MockSettingsRepository_UpdateWorkExperience_Call) Return(_a0 *models.WorkExperience, _a1 error) *MockSettingsRepository_UpdateWorkExperience_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSettingsRepository_UpdateWorkExperience_Call) RunAndReturn(run func(context.Context, *models.WorkExperience) (*models.WorkExperience, error)) *MockSettingsRepository_UpdateWorkExperience_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSettingsRepository creates a new instance of MockSettingsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSettingsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSettingsRepository {
	mock := &MockSettingsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
