// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// MockErrorHandler is an autogenerated mock type for the ErrorHandler type
type MockErrorHandler struct {
	mock.Mock
}

type MockErrorHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockErrorHandler) EXPECT() *MockErrorHandler_Expecter {
	return &MockErrorHandler_Expecter{mock: &_m.Mock}
}

// HandleError provides a mock function with given fields: c, err
func (_m *MockErrorHandler) HandleError(c *gin.Context, err error) {
	_m.Called(c, err)
}

// MockErrorHandler_HandleError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleError'
type MockErrorHandler_HandleError_Call struct {
	*mock.Call
}

// HandleError is a helper method to define mock.On call
//   - c *gin.Context
//   - err error
func (_e *MockErrorHandler_Expecter) HandleError(c interface{}, err interface{}) *MockErrorHandler_HandleError_Call {
	return &MockErrorHandler_HandleError_Call{Call: _e.mock.On("HandleError", c, err)}
}

func (_c *MockErrorHandler_HandleError_Call) Run(run func(c *gin.Context, err error)) *MockErrorHandler_HandleError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context), args[1].(error))
	})
	return _c
}

func (_c *MockErrorHandler_HandleError_Call) Return() *MockErrorHandler_HandleError_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockErrorHandler_HandleError_Call) RunAndReturn(run func(*gin.Context, error)) *MockErrorHandler_HandleError_Call {
	_c.Run(run)
	return _c
}

// HandleValidationError provides a mock function with given fields: c, err
func (_m *MockErrorHandler) HandleValidationError(c *gin.Context, err error) {
	_m.Called(c, err)
}

// MockErrorHandler_HandleValidationError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleValidationError'
type MockErrorHandler_HandleValidationError_Call struct {
	*mock.Call
}

// HandleValidationError is a helper method to define mock.On call
//   - c *gin.Context
//   - err error
func (_e *MockErrorHandler_Expecter) HandleValidationError(c interface{}, err interface{}) *MockErrorHandler_HandleValidationError_Call {
	return &MockErrorHandler_HandleValidationError_Call{Call: _e.mock.On("HandleValidationError", c, err)}
}

func (_c *MockErrorHandler_HandleValidationError_Call) Run(run func(c *gin.Context, err error)) *MockErrorHandler_HandleValidationError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context), args[1].(error))
	})
	return _c
}

func (_c *MockErrorHandler_HandleValidationError_Call) Return() *MockErrorHandler_HandleValidationError_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockErrorHandler_HandleValidationError_Call) RunAndReturn(run func(*gin.Context, error)) *MockErrorHandler_HandleValidationError_Call {
	_c.Run(run)
	return _c
}

// NewMockErrorHandler creates a new instance of MockErrorHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockErrorHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockErrorHandler {
	mock := &MockErrorHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
