// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// MockHTMLRenderer is an autogenerated mock type for the HTMLRenderer type
type MockHTMLRenderer struct {
	mock.Mock
}

type MockHTMLRenderer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHTMLRenderer) EXPECT() *MockHTMLRenderer_Expecter {
	return &MockHTMLRenderer_Expecter{mock: &_m.Mock}
}

// HTML provides a mock function with given fields: c, code, name, obj
func (_m *MockHTMLRenderer) HTML(c *gin.Context, code int, name string, obj interface{}) {
	_m.Called(c, code, name, obj)
}

// MockHTMLRenderer_HTML_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HTML'
type MockHTMLRenderer_HTML_Call struct {
	*mock.Call
}

// HTML is a helper method to define mock.On call
//   - c *gin.Context
//   - code int
//   - name string
//   - obj interface{}
func (_e *MockHTMLRenderer_Expecter) HTML(c interface{}, code interface{}, name interface{}, obj interface{}) *MockHTMLRenderer_HTML_Call {
	return &MockHTMLRenderer_HTML_Call{Call: _e.mock.On("HTML", c, code, name, obj)}
}

func (_c *MockHTMLRenderer_HTML_Call) Run(run func(c *gin.Context, code int, name string, obj interface{})) *MockHTMLRenderer_HTML_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context), args[1].(int), args[2].(string), args[3].(interface{}))
	})
	return _c
}

func (_c *MockHTMLRenderer_HTML_Call) Return() *MockHTMLRenderer_HTML_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHTMLRenderer_HTML_Call) RunAndReturn(run func(*gin.Context, int, string, interface{})) *MockHTMLRenderer_HTML_Call {
	_c.Run(run)
	return _c
}

// NewMockHTMLRenderer creates a new instance of MockHTMLRenderer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHTMLRenderer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHTMLRenderer {
	mock := &MockHTMLRenderer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
