// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/benidevo/vega/internal/job/models"
	mock "github.com/stretchr/testify/mock"
)

// MockJobRepository is an autogenerated mock type for the JobRepository type
type MockJobRepository struct {
	mock.Mock
}

type MockJobRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJobRepository) EXPECT() *MockJobRepository_Expecter {
	return &MockJobRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, userID, job
func (_m *MockJobRepository) Create(ctx context.Context, userID int, job *models.Job) (*models.Job, error) {
	ret := _m.Called(ctx, userID, job)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.Job
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, *models.Job) (*models.Job, error)); ok {
		return rf(ctx, userID, job)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, *models.Job) *models.Job); ok {
		r0 = rf(ctx, userID, job)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Job)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, *models.Job) error); ok {
		r1 = rf(ctx, userID, job)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockJobRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockJobRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - job *models.Job
func (_e *MockJobRepository_Expecter) Create(ctx interface{}, userID interface{}, job interface{}) *MockJobRepository_Create_Call {
	return &MockJobRepository_Create_Call{Call: _e.mock.On("Create", ctx, userID, job)}
}

func (_c *MockJobRepository_Create_Call) Run(run func(ctx context.Context, userID int, job *models.Job)) *MockJobRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(*models.Job))
	})
	return _c
}

func (_c *MockJobRepository_Create_Call) Return(_a0 *models.Job, _a1 error) *MockJobRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockJobRepository_Create_Call) RunAndReturn(run func(context.Context, int, *models.Job) (*models.Job, error)) *MockJobRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateMatchResult provides a mock function with given fields: ctx, userID, matchResult
func (_m *MockJobRepository) CreateMatchResult(ctx context.Context, userID int, matchResult *models.MatchResult) error {
	ret := _m.Called(ctx, userID, matchResult)

	if len(ret) == 0 {
		panic("no return value specified for CreateMatchResult")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, *models.MatchResult) error); ok {
		r0 = rf(ctx, userID, matchResult)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockJobRepository_CreateMatchResult_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMatchResult'
type MockJobRepository_CreateMatchResult_Call struct {
	*mock.Call
}

// CreateMatchResult is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - matchResult *models.MatchResult
func (_e *MockJobRepository_Expecter) CreateMatchResult(ctx interface{}, userID interface{}, matchResult interface{}) *MockJobRepository_CreateMatchResult_Call {
	return &MockJobRepository_CreateMatchResult_Call{Call: _e.mock.On("CreateMatchResult", ctx, userID, matchResult)}
}

func (_c *MockJobRepository_CreateMatchResult_Call) Run(run func(ctx context.Context, userID int, matchResult *models.MatchResult)) *MockJobRepository_CreateMatchResult_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(*models.MatchResult))
	})
	return _c
}

func (_c *MockJobRepository_CreateMatchResult_Call) Return(_a0 error) *MockJobRepository_CreateMatchResult_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockJobRepository_CreateMatchResult_Call) RunAndReturn(run func(context.Context, int, *models.MatchResult) error) *MockJobRepository_CreateMatchResult_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, userID, id
func (_m *MockJobRepository) Delete(ctx context.Context, userID int, id int) error {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockJobRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockJobRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - id int
func (_e *MockJobRepository_Expecter) Delete(ctx interface{}, userID interface{}, id interface{}) *MockJobRepository_Delete_Call {
	return &MockJobRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, userID, id)}
}

func (_c *MockJobRepository_Delete_Call) Run(run func(ctx context.Context, userID int, id int)) *MockJobRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockJobRepository_Delete_Call) Return(_a0 error) *MockJobRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockJobRepository_Delete_Call) RunAndReturn(run func(context.Context, int, int) error) *MockJobRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteMatchResult provides a mock function with given fields: ctx, userID, matchID
func (_m *MockJobRepository) DeleteMatchResult(ctx context.Context, userID int, matchID int) error {
	ret := _m.Called(ctx, userID, matchID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMatchResult")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, userID, matchID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockJobRepository_DeleteMatchResult_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMatchResult'
type MockJobRepository_DeleteMatchResult_Call struct {
	*mock.Call
}

// DeleteMatchResult is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - matchID int
func (_e *MockJobRepository_Expecter) DeleteMatchResult(ctx interface{}, userID interface{}, matchID interface{}) *MockJobRepository_DeleteMatchResult_Call {
	return &MockJobRepository_DeleteMatchResult_Call{Call: _e.mock.On("DeleteMatchResult", ctx, userID, matchID)}
}

func (_c *MockJobRepository_DeleteMatchResult_Call) Run(run func(ctx context.Context, userID int, matchID int)) *MockJobRepository_DeleteMatchResult_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockJobRepository_DeleteMatchResult_Call) Return(_a0 error) *MockJobRepository_DeleteMatchResult_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockJobRepository_DeleteMatchResult_Call) RunAndReturn(run func(context.Context, int, int) error) *MockJobRepository_DeleteMatchResult_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: ctx, userID, filter
func (_m *MockJobRepository) GetAll(ctx context.Context, userID int, filter models.JobFilter) ([]*models.Job, error) {
	ret := _m.Called(ctx, userID, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*models.Job
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, models.JobFilter) ([]*models.Job, error)); ok {
		return rf(ctx, userID, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, models.JobFilter) []*models.Job); ok {
		r0 = rf(ctx, userID, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Job)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, models.JobFilter) error); ok {
		r1 = rf(ctx, userID, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockJobRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockJobRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - filter models.JobFilter
func (_e *MockJobRepository_Expecter) GetAll(ctx interface{}, userID interface{}, filter interface{}) *MockJobRepository_GetAll_Call {
	return &MockJobRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx, userID, filter)}
}

func (_c *MockJobRepository_GetAll_Call) Run(run func(ctx context.Context, userID int, filter models.JobFilter)) *MockJobRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(models.JobFilter))
	})
	return _c
}

func (_c *MockJobRepository_GetAll_Call) Return(_a0 []*models.Job, _a1 error) *MockJobRepository_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockJobRepository_GetAll_Call) RunAndReturn(run func(context.Context, int, models.JobFilter) ([]*models.Job, error)) *MockJobRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, userID, id
func (_m *MockJobRepository) GetByID(ctx context.Context, userID int, id int) (*models.Job, error) {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Job
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) (*models.Job, error)); ok {
		return rf(ctx, userID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) *models.Job); ok {
		r0 = rf(ctx, userID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Job)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, userID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockJobRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockJobRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - id int
func (_e *MockJobRepository_Expecter) GetByID(ctx interface{}, userID interface{}, id interface{}) *MockJobRepository_GetByID_Call {
	return &MockJobRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, userID, id)}
}

func (_c *MockJobRepository_GetByID_Call) Run(run func(ctx context.Context, userID int, id int)) *MockJobRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockJobRepository_GetByID_Call) Return(_a0 *models.Job, _a1 error) *MockJobRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockJobRepository_GetByID_Call) RunAndReturn(run func(context.Context, int, int) (*models.Job, error)) *MockJobRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetBySourceURL provides a mock function with given fields: ctx, userID, sourceURL
func (_m *MockJobRepository) GetBySourceURL(ctx context.Context, userID int, sourceURL string) (*models.Job, error) {
	ret := _m.Called(ctx, userID, sourceURL)

	if len(ret) == 0 {
		panic("no return value specified for GetBySourceURL")
	}

	var r0 *models.Job
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string) (*models.Job, error)); ok {
		return rf(ctx, userID, sourceURL)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, string) *models.Job); ok {
		r0 = rf(ctx, userID, sourceURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Job)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, string) error); ok {
		r1 = rf(ctx, userID, sourceURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockJobRepository_GetBySourceURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBySourceURL'
type MockJobRepository_GetBySourceURL_Call struct {
	*mock.Call
}

// GetBySourceURL is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - sourceURL string
func (_e *MockJobRepository_Expecter) GetBySourceURL(ctx interface{}, userID interface{}, sourceURL interface{}) *MockJobRepository_GetBySourceURL_Call {
	return &MockJobRepository_GetBySourceURL_Call{Call: _e.mock.On("GetBySourceURL", ctx, userID, sourceURL)}
}

func (_c *MockJobRepository_GetBySourceURL_Call) Run(run func(ctx context.Context, userID int, sourceURL string)) *MockJobRepository_GetBySourceURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(string))
	})
	return _c
}

func (_c *MockJobRepository_GetBySourceURL_Call) Return(_a0 *models.Job, _a1 error) *MockJobRepository_GetBySourceURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockJobRepository_GetBySourceURL_Call) RunAndReturn(run func(context.Context, int, string) (*models.Job, error)) *MockJobRepository_GetBySourceURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetCount provides a mock function with given fields: ctx, userID, filter
func (_m *MockJobRepository) GetCount(ctx context.Context, userID int, filter models.JobFilter) (int, error) {
	ret := _m.Called(ctx, userID, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetCount")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, models.JobFilter) (int, error)); ok {
		return rf(ctx, userID, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, models.JobFilter) int); ok {
		r0 = rf(ctx, userID, filter)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, models.JobFilter) error); ok {
		r1 = rf(ctx, userID, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockJobRepository_GetCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCount'
type MockJobRepository_GetCount_Call struct {
	*mock.Call
}

// GetCount is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - filter models.JobFilter
func (_e *MockJobRepository_Expecter) GetCount(ctx interface{}, userID interface{}, filter interface{}) *MockJobRepository_GetCount_Call {
	return &MockJobRepository_GetCount_Call{Call: _e.mock.On("GetCount", ctx, userID, filter)}
}

func (_c *MockJobRepository_GetCount_Call) Run(run func(ctx context.Context, userID int, filter models.JobFilter)) *MockJobRepository_GetCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(models.JobFilter))
	})
	return _c
}

func (_c *MockJobRepository_GetCount_Call) Return(_a0 int, _a1 error) *MockJobRepository_GetCount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockJobRepository_GetCount_Call) RunAndReturn(run func(context.Context, int, models.JobFilter) (int, error)) *MockJobRepository_GetCount_Call {
	_c.Call.Return(run)
	return _c
}

// GetJobMatchHistory provides a mock function with given fields: ctx, userID, jobID
func (_m *MockJobRepository) GetJobMatchHistory(ctx context.Context, userID int, jobID int) ([]*models.MatchResult, error) {
	ret := _m.Called(ctx, userID, jobID)

	if len(ret) == 0 {
		panic("no return value specified for GetJobMatchHistory")
	}

	var r0 []*models.MatchResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]*models.MatchResult, error)); ok {
		return rf(ctx, userID, jobID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []*models.MatchResult); ok {
		r0 = rf(ctx, userID, jobID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.MatchResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, userID, jobID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockJobRepository_GetJobMatchHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetJobMatchHistory'
type MockJobRepository_GetJobMatchHistory_Call struct {
	*mock.Call
}

// GetJobMatchHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - jobID int
func (_e *MockJobRepository_Expecter) GetJobMatchHistory(ctx interface{}, userID interface{}, jobID interface{}) *MockJobRepository_GetJobMatchHistory_Call {
	return &MockJobRepository_GetJobMatchHistory_Call{Call: _e.mock.On("GetJobMatchHistory", ctx, userID, jobID)}
}

func (_c *MockJobRepository_GetJobMatchHistory_Call) Run(run func(ctx context.Context, userID int, jobID int)) *MockJobRepository_GetJobMatchHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockJobRepository_GetJobMatchHistory_Call) Return(_a0 []*models.MatchResult, _a1 error) *MockJobRepository_GetJobMatchHistory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockJobRepository_GetJobMatchHistory_Call) RunAndReturn(run func(context.Context, int, int) ([]*models.MatchResult, error)) *MockJobRepository_GetJobMatchHistory_Call {
	_c.Call.Return(run)
	return _c
}

// GetJobStatsByStatus provides a mock function with given fields: ctx, userID
func (_m *MockJobRepository) GetJobStatsByStatus(ctx context.Context, userID int) (map[models.JobStatus]int, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetJobStatsByStatus")
	}

	var r0 map[models.JobStatus]int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (map[models.JobStatus]int, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) map[models.JobStatus]int); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[models.JobStatus]int)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockJobRepository_GetJobStatsByStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetJobStatsByStatus'
type MockJobRepository_GetJobStatsByStatus_Call struct {
	*mock.Call
}

// GetJobStatsByStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockJobRepository_Expecter) GetJobStatsByStatus(ctx interface{}, userID interface{}) *MockJobRepository_GetJobStatsByStatus_Call {
	return &MockJobRepository_GetJobStatsByStatus_Call{Call: _e.mock.On("GetJobStatsByStatus", ctx, userID)}
}

func (_c *MockJobRepository_GetJobStatsByStatus_Call) Run(run func(ctx context.Context, userID int)) *MockJobRepository_GetJobStatsByStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockJobRepository_GetJobStatsByStatus_Call) Return(_a0 map[models.JobStatus]int, _a1 error) *MockJobRepository_GetJobStatsByStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockJobRepository_GetJobStatsByStatus_Call) RunAndReturn(run func(context.Context, int) (map[models.JobStatus]int, error)) *MockJobRepository_GetJobStatsByStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetMonthlyAnalysisCount provides a mock function with given fields: ctx, userID
func (_m *MockJobRepository) GetMonthlyAnalysisCount(ctx context.Context, userID int) (int, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetMonthlyAnalysisCount")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (int, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) int); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockJobRepository_GetMonthlyAnalysisCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMonthlyAnalysisCount'
type MockJobRepository_GetMonthlyAnalysisCount_Call struct {
	*mock.Call
}

// GetMonthlyAnalysisCount is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockJobRepository_Expecter) GetMonthlyAnalysisCount(ctx interface{}, userID interface{}) *MockJobRepository_GetMonthlyAnalysisCount_Call {
	return &MockJobRepository_GetMonthlyAnalysisCount_Call{Call: _e.mock.On("GetMonthlyAnalysisCount", ctx, userID)}
}

func (_c *MockJobRepository_GetMonthlyAnalysisCount_Call) Run(run func(ctx context.Context, userID int)) *MockJobRepository_GetMonthlyAnalysisCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockJobRepository_GetMonthlyAnalysisCount_Call) Return(_a0 int, _a1 error) *MockJobRepository_GetMonthlyAnalysisCount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockJobRepository_GetMonthlyAnalysisCount_Call) RunAndReturn(run func(context.Context, int) (int, error)) *MockJobRepository_GetMonthlyAnalysisCount_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrCreate provides a mock function with given fields: ctx, userID, job
func (_m *MockJobRepository) GetOrCreate(ctx context.Context, userID int, job *models.Job) (*models.Job, bool, error) {
	ret := _m.Called(ctx, userID, job)

	if len(ret) == 0 {
		panic("no return value specified for GetOrCreate")
	}

	var r0 *models.Job
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, *models.Job) (*models.Job, bool, error)); ok {
		return rf(ctx, userID, job)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, *models.Job) *models.Job); ok {
		r0 = rf(ctx, userID, job)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Job)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, *models.Job) bool); ok {
		r1 = rf(ctx, userID, job)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, *models.Job) error); ok {
		r2 = rf(ctx, userID, job)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockJobRepository_GetOrCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrCreate'
type MockJobRepository_GetOrCreate_Call struct {
	*mock.Call
}

// GetOrCreate is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - job *models.Job
func (_e *MockJobRepository_Expecter) GetOrCreate(ctx interface{}, userID interface{}, job interface{}) *MockJobRepository_GetOrCreate_Call {
	return &MockJobRepository_GetOrCreate_Call{Call: _e.mock.On("GetOrCreate", ctx, userID, job)}
}

func (_c *MockJobRepository_GetOrCreate_Call) Run(run func(ctx context.Context, userID int, job *models.Job)) *MockJobRepository_GetOrCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(*models.Job))
	})
	return _c
}

func (_c *MockJobRepository_GetOrCreate_Call) Return(_a0 *models.Job, _a1 bool, _a2 error) *MockJobRepository_GetOrCreate_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockJobRepository_GetOrCreate_Call) RunAndReturn(run func(context.Context, int, *models.Job) (*models.Job, bool, error)) *MockJobRepository_GetOrCreate_Call {
	_c.Call.Return(run)
	return _c
}

// GetRecentJobsByUserID provides a mock function with given fields: ctx, userID, limit
func (_m *MockJobRepository) GetRecentJobsByUserID(ctx context.Context, userID int, limit int) ([]*models.Job, error) {
	ret := _m.Called(ctx, userID, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetRecentJobsByUserID")
	}

	var r0 []*models.Job
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]*models.Job, error)); ok {
		return rf(ctx, userID, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []*models.Job); ok {
		r0 = rf(ctx, userID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Job)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, userID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockJobRepository_GetRecentJobsByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRecentJobsByUserID'
type MockJobRepository_GetRecentJobsByUserID_Call struct {
	*mock.Call
}

// GetRecentJobsByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - limit int
func (_e *MockJobRepository_Expecter) GetRecentJobsByUserID(ctx interface{}, userID interface{}, limit interface{}) *MockJobRepository_GetRecentJobsByUserID_Call {
	return &MockJobRepository_GetRecentJobsByUserID_Call{Call: _e.mock.On("GetRecentJobsByUserID", ctx, userID, limit)}
}

func (_c *MockJobRepository_GetRecentJobsByUserID_Call) Run(run func(ctx context.Context, userID int, limit int)) *MockJobRepository_GetRecentJobsByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockJobRepository_GetRecentJobsByUserID_Call) Return(_a0 []*models.Job, _a1 error) *MockJobRepository_GetRecentJobsByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockJobRepository_GetRecentJobsByUserID_Call) RunAndReturn(run func(context.Context, int, int) ([]*models.Job, error)) *MockJobRepository_GetRecentJobsByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetRecentMatchResults provides a mock function with given fields: ctx, userID, limit
func (_m *MockJobRepository) GetRecentMatchResults(ctx context.Context, userID int, limit int) ([]*models.MatchResult, error) {
	ret := _m.Called(ctx, userID, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetRecentMatchResults")
	}

	var r0 []*models.MatchResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]*models.MatchResult, error)); ok {
		return rf(ctx, userID, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []*models.MatchResult); ok {
		r0 = rf(ctx, userID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.MatchResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, userID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockJobRepository_GetRecentMatchResults_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRecentMatchResults'
type MockJobRepository_GetRecentMatchResults_Call struct {
	*mock.Call
}

// GetRecentMatchResults is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - limit int
func (_e *MockJobRepository_Expecter) GetRecentMatchResults(ctx interface{}, userID interface{}, limit interface{}) *MockJobRepository_GetRecentMatchResults_Call {
	return &MockJobRepository_GetRecentMatchResults_Call{Call: _e.mock.On("GetRecentMatchResults", ctx, userID, limit)}
}

func (_c *MockJobRepository_GetRecentMatchResults_Call) Run(run func(ctx context.Context, userID int, limit int)) *MockJobRepository_GetRecentMatchResults_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockJobRepository_GetRecentMatchResults_Call) Return(_a0 []*models.MatchResult, _a1 error) *MockJobRepository_GetRecentMatchResults_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockJobRepository_GetRecentMatchResults_Call) RunAndReturn(run func(context.Context, int, int) ([]*models.MatchResult, error)) *MockJobRepository_GetRecentMatchResults_Call {
	_c.Call.Return(run)
	return _c
}

// GetRecentMatchResultsWithDetails provides a mock function with given fields: ctx, userID, limit, currentJobID
func (_m *MockJobRepository) GetRecentMatchResultsWithDetails(ctx context.Context, userID int, limit int, currentJobID int) ([]*models.MatchSummary, error) {
	ret := _m.Called(ctx, userID, limit, currentJobID)

	if len(ret) == 0 {
		panic("no return value specified for GetRecentMatchResultsWithDetails")
	}

	var r0 []*models.MatchSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int) ([]*models.MatchSummary, error)); ok {
		return rf(ctx, userID, limit, currentJobID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int) []*models.MatchSummary); ok {
		r0 = rf(ctx, userID, limit, currentJobID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.MatchSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, int) error); ok {
		r1 = rf(ctx, userID, limit, currentJobID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockJobRepository_GetRecentMatchResultsWithDetails_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRecentMatchResultsWithDetails'
type MockJobRepository_GetRecentMatchResultsWithDetails_Call struct {
	*mock.Call
}

// GetRecentMatchResultsWithDetails is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - limit int
//   - currentJobID int
func (_e *MockJobRepository_Expecter) GetRecentMatchResultsWithDetails(ctx interface{}, userID interface{}, limit interface{}, currentJobID interface{}) *MockJobRepository_GetRecentMatchResultsWithDetails_Call {
	return &MockJobRepository_GetRecentMatchResultsWithDetails_Call{Call: _e.mock.On("GetRecentMatchResultsWithDetails", ctx, userID, limit, currentJobID)}
}

func (_c *MockJobRepository_GetRecentMatchResultsWithDetails_Call) Run(run func(ctx context.Context, userID int, limit int, currentJobID int)) *MockJobRepository_GetRecentMatchResultsWithDetails_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockJobRepository_GetRecentMatchResultsWithDetails_Call) Return(_a0 []*models.MatchSummary, _a1 error) *MockJobRepository_GetRecentMatchResultsWithDetails_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockJobRepository_GetRecentMatchResultsWithDetails_Call) RunAndReturn(run func(context.Context, int, int, int) ([]*models.MatchSummary, error)) *MockJobRepository_GetRecentMatchResultsWithDetails_Call {
	_c.Call.Return(run)
	return _c
}

// GetStats provides a mock function with given fields: ctx, userID
func (_m *MockJobRepository) GetStats(ctx context.Context, userID int) (*models.JobStats, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetStats")
	}

	var r0 *models.JobStats
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*models.JobStats, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *models.JobStats); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.JobStats)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockJobRepository_GetStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStats'
type MockJobRepository_GetStats_Call struct {
	*mock.Call
}

// GetStats is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockJobRepository_Expecter) GetStats(ctx interface{}, userID interface{}) *MockJobRepository_GetStats_Call {
	return &MockJobRepository_GetStats_Call{Call: _e.mock.On("GetStats", ctx, userID)}
}

func (_c *MockJobRepository_GetStats_Call) Run(run func(ctx context.Context, userID int)) *MockJobRepository_GetStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockJobRepository_GetStats_Call) Return(_a0 *models.JobStats, _a1 error) *MockJobRepository_GetStats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockJobRepository_GetStats_Call) RunAndReturn(run func(context.Context, int) (*models.JobStats, error)) *MockJobRepository_GetStats_Call {
	_c.Call.Return(run)
	return _c
}

// GetStatsByUserID provides a mock function with given fields: ctx, userID
func (_m *MockJobRepository) GetStatsByUserID(ctx context.Context, userID int) (*models.JobStats, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetStatsByUserID")
	}

	var r0 *models.JobStats
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*models.JobStats, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *models.JobStats); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.JobStats)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockJobRepository_GetStatsByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatsByUserID'
type MockJobRepository_GetStatsByUserID_Call struct {
	*mock.Call
}

// GetStatsByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockJobRepository_Expecter) GetStatsByUserID(ctx interface{}, userID interface{}) *MockJobRepository_GetStatsByUserID_Call {
	return &MockJobRepository_GetStatsByUserID_Call{Call: _e.mock.On("GetStatsByUserID", ctx, userID)}
}

func (_c *MockJobRepository_GetStatsByUserID_Call) Run(run func(ctx context.Context, userID int)) *MockJobRepository_GetStatsByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockJobRepository_GetStatsByUserID_Call) Return(_a0 *models.JobStats, _a1 error) *MockJobRepository_GetStatsByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockJobRepository_GetStatsByUserID_Call) RunAndReturn(run func(context.Context, int) (*models.JobStats, error)) *MockJobRepository_GetStatsByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetTopMatchesByUserID provides a mock function with given fields: ctx, userID, limit
func (_m *MockJobRepository) GetTopMatchesByUserID(ctx context.Context, userID int, limit int) ([]*models.Job, error) {
	ret := _m.Called(ctx, userID, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetTopMatchesByUserID")
	}

	var r0 []*models.Job
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]*models.Job, error)); ok {
		return rf(ctx, userID, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []*models.Job); ok {
		r0 = rf(ctx, userID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Job)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, userID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockJobRepository_GetTopMatchesByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTopMatchesByUserID'
type MockJobRepository_GetTopMatchesByUserID_Call struct {
	*mock.Call
}

// GetTopMatchesByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - limit int
func (_e *MockJobRepository_Expecter) GetTopMatchesByUserID(ctx interface{}, userID interface{}, limit interface{}) *MockJobRepository_GetTopMatchesByUserID_Call {
	return &MockJobRepository_GetTopMatchesByUserID_Call{Call: _e.mock.On("GetTopMatchesByUserID", ctx, userID, limit)}
}

func (_c *MockJobRepository_GetTopMatchesByUserID_Call) Run(run func(ctx context.Context, userID int, limit int)) *MockJobRepository_GetTopMatchesByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockJobRepository_GetTopMatchesByUserID_Call) Return(_a0 []*models.Job, _a1 error) *MockJobRepository_GetTopMatchesByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockJobRepository_GetTopMatchesByUserID_Call) RunAndReturn(run func(context.Context, int, int) ([]*models.Job, error)) *MockJobRepository_GetTopMatchesByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// MatchResultBelongsToJob provides a mock function with given fields: ctx, userID, matchID, jobID
func (_m *MockJobRepository) MatchResultBelongsToJob(ctx context.Context, userID int, matchID int, jobID int) (bool, error) {
	ret := _m.Called(ctx, userID, matchID, jobID)

	if len(ret) == 0 {
		panic("no return value specified for MatchResultBelongsToJob")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int) (bool, error)); ok {
		return rf(ctx, userID, matchID, jobID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int) bool); ok {
		r0 = rf(ctx, userID, matchID, jobID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, int) error); ok {
		r1 = rf(ctx, userID, matchID, jobID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockJobRepository_MatchResultBelongsToJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MatchResultBelongsToJob'
type MockJobRepository_MatchResultBelongsToJob_Call struct {
	*mock.Call
}

// MatchResultBelongsToJob is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - matchID int
//   - jobID int
func (_e *MockJobRepository_Expecter) MatchResultBelongsToJob(ctx interface{}, userID interface{}, matchID interface{}, jobID interface{}) *MockJobRepository_MatchResultBelongsToJob_Call {
	return &MockJobRepository_MatchResultBelongsToJob_Call{Call: _e.mock.On("MatchResultBelongsToJob", ctx, userID, matchID, jobID)}
}

func (_c *MockJobRepository_MatchResultBelongsToJob_Call) Run(run func(ctx context.Context, userID int, matchID int, jobID int)) *MockJobRepository_MatchResultBelongsToJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockJobRepository_MatchResultBelongsToJob_Call) Return(_a0 bool, _a1 error) *MockJobRepository_MatchResultBelongsToJob_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockJobRepository_MatchResultBelongsToJob_Call) RunAndReturn(run func(context.Context, int, int, int) (bool, error)) *MockJobRepository_MatchResultBelongsToJob_Call {
	_c.Call.Return(run)
	return _c
}

// SetFirstAnalyzedAt provides a mock function with given fields: ctx, jobID
func (_m *MockJobRepository) SetFirstAnalyzedAt(ctx context.Context, jobID int) error {
	ret := _m.Called(ctx, jobID)

	if len(ret) == 0 {
		panic("no return value specified for SetFirstAnalyzedAt")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, jobID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockJobRepository_SetFirstAnalyzedAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetFirstAnalyzedAt'
type MockJobRepository_SetFirstAnalyzedAt_Call struct {
	*mock.Call
}

// SetFirstAnalyzedAt is a helper method to define mock.On call
//   - ctx context.Context
//   - jobID int
func (_e *MockJobRepository_Expecter) SetFirstAnalyzedAt(ctx interface{}, jobID interface{}) *MockJobRepository_SetFirstAnalyzedAt_Call {
	return &MockJobRepository_SetFirstAnalyzedAt_Call{Call: _e.mock.On("SetFirstAnalyzedAt", ctx, jobID)}
}

func (_c *MockJobRepository_SetFirstAnalyzedAt_Call) Run(run func(ctx context.Context, jobID int)) *MockJobRepository_SetFirstAnalyzedAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockJobRepository_SetFirstAnalyzedAt_Call) Return(_a0 error) *MockJobRepository_SetFirstAnalyzedAt_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockJobRepository_SetFirstAnalyzedAt_Call) RunAndReturn(run func(context.Context, int) error) *MockJobRepository_SetFirstAnalyzedAt_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, userID, job
func (_m *MockJobRepository) Update(ctx context.Context, userID int, job *models.Job) error {
	ret := _m.Called(ctx, userID, job)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, *models.Job) error); ok {
		r0 = rf(ctx, userID, job)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockJobRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockJobRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - job *models.Job
func (_e *MockJobRepository_Expecter) Update(ctx interface{}, userID interface{}, job interface{}) *MockJobRepository_Update_Call {
	return &MockJobRepository_Update_Call{Call: _e.mock.On("Update", ctx, userID, job)}
}

func (_c *MockJobRepository_Update_Call) Run(run func(ctx context.Context, userID int, job *models.Job)) *MockJobRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(*models.Job))
	})
	return _c
}

func (_c *MockJobRepository_Update_Call) Return(_a0 error) *MockJobRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockJobRepository_Update_Call) RunAndReturn(run func(context.Context, int, *models.Job) error) *MockJobRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMatchScore provides a mock function with given fields: ctx, userID, jobID, matchScore
func (_m *MockJobRepository) UpdateMatchScore(ctx context.Context, userID int, jobID int, matchScore *int) error {
	ret := _m.Called(ctx, userID, jobID, matchScore)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMatchScore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, *int) error); ok {
		r0 = rf(ctx, userID, jobID, matchScore)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockJobRepository_UpdateMatchScore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMatchScore'
type MockJobRepository_UpdateMatchScore_Call struct {
	*mock.Call
}

// UpdateMatchScore is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - jobID int
//   - matchScore *int
func (_e *MockJobRepository_Expecter) UpdateMatchScore(ctx interface{}, userID interface{}, jobID interface{}, matchScore interface{}) *MockJobRepository_UpdateMatchScore_Call {
	return &MockJobRepository_UpdateMatchScore_Call{Call: _e.mock.On("UpdateMatchScore", ctx, userID, jobID, matchScore)}
}

func (_c *MockJobRepository_UpdateMatchScore_Call) Run(run func(ctx context.Context, userID int, jobID int, matchScore *int)) *MockJobRepository_UpdateMatchScore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int), args[3].(*int))
	})
	return _c
}

func (_c *MockJobRepository_UpdateMatchScore_Call) Return(_a0 error) *MockJobRepository_UpdateMatchScore_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockJobRepository_UpdateMatchScore_Call) RunAndReturn(run func(context.Context, int, int, *int) error) *MockJobRepository_UpdateMatchScore_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: ctx, userID, id, status
func (_m *MockJobRepository) UpdateStatus(ctx context.Context, userID int, id int, status models.JobStatus) error {
	ret := _m.Called(ctx, userID, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, models.JobStatus) error); ok {
		r0 = rf(ctx, userID, id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockJobRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockJobRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - id int
//   - status models.JobStatus
func (_e *MockJobRepository_Expecter) UpdateStatus(ctx interface{}, userID interface{}, id interface{}, status interface{}) *MockJobRepository_UpdateStatus_Call {
	return &MockJobRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, userID, id, status)}
}

func (_c *MockJobRepository_UpdateStatus_Call) Run(run func(ctx context.Context, userID int, id int, status models.JobStatus)) *MockJobRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int), args[3].(models.JobStatus))
	})
	return _c
}

func (_c *MockJobRepository_UpdateStatus_Call) Return(_a0 error) *MockJobRepository_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockJobRepository_UpdateStatus_Call) RunAndReturn(run func(context.Context, int, int, models.JobStatus) error) *MockJobRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJobRepository creates a new instance of MockJobRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJobRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJobRepository {
	mock := &MockJobRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
