// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/benidevo/vega/internal/job/models"

	sql "database/sql"
)

// MockTransactionalCompanyRepository is an autogenerated mock type for the TransactionalCompanyRepository type
type MockTransactionalCompanyRepository struct {
	mock.Mock
}

type MockTransactionalCompanyRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionalCompanyRepository) EXPECT() *MockTransactionalCompanyRepository_Expecter {
	return &MockTransactionalCompanyRepository_Expecter{mock: &_m.Mock}
}

// BeginTx provides a mock function with given fields: ctx, opts
func (_m *MockTransactionalCompanyRepository) BeginTx(ctx context.Context, opts *sql.TxOptions) (*sql.Tx, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for BeginTx")
	}

	var r0 *sql.Tx
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sql.TxOptions) (*sql.Tx, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sql.TxOptions) *sql.Tx); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Tx)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sql.TxOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionalCompanyRepository_BeginTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginTx'
type MockTransactionalCompanyRepository_BeginTx_Call struct {
	*mock.Call
}

// BeginTx is a helper method to define mock.On call
//   - ctx context.Context
//   - opts *sql.TxOptions
func (_e *MockTransactionalCompanyRepository_Expecter) BeginTx(ctx interface{}, opts interface{}) *MockTransactionalCompanyRepository_BeginTx_Call {
	return &MockTransactionalCompanyRepository_BeginTx_Call{Call: _e.mock.On("BeginTx", ctx, opts)}
}

func (_c *MockTransactionalCompanyRepository_BeginTx_Call) Run(run func(ctx context.Context, opts *sql.TxOptions)) *MockTransactionalCompanyRepository_BeginTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sql.TxOptions))
	})
	return _c
}

func (_c *MockTransactionalCompanyRepository_BeginTx_Call) Return(_a0 *sql.Tx, _a1 error) *MockTransactionalCompanyRepository_BeginTx_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionalCompanyRepository_BeginTx_Call) RunAndReturn(run func(context.Context, *sql.TxOptions) (*sql.Tx, error)) *MockTransactionalCompanyRepository_BeginTx_Call {
	_c.Call.Return(run)
	return _c
}

// CommitTx provides a mock function with given fields: tx
func (_m *MockTransactionalCompanyRepository) CommitTx(tx *sql.Tx) error {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for CommitTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*sql.Tx) error); ok {
		r0 = rf(tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransactionalCompanyRepository_CommitTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CommitTx'
type MockTransactionalCompanyRepository_CommitTx_Call struct {
	*mock.Call
}

// CommitTx is a helper method to define mock.On call
//   - tx *sql.Tx
func (_e *MockTransactionalCompanyRepository_Expecter) CommitTx(tx interface{}) *MockTransactionalCompanyRepository_CommitTx_Call {
	return &MockTransactionalCompanyRepository_CommitTx_Call{Call: _e.mock.On("CommitTx", tx)}
}

func (_c *MockTransactionalCompanyRepository_CommitTx_Call) Run(run func(tx *sql.Tx)) *MockTransactionalCompanyRepository_CommitTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*sql.Tx))
	})
	return _c
}

func (_c *MockTransactionalCompanyRepository_CommitTx_Call) Return(_a0 error) *MockTransactionalCompanyRepository_CommitTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactionalCompanyRepository_CommitTx_Call) RunAndReturn(run func(*sql.Tx) error) *MockTransactionalCompanyRepository_CommitTx_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockTransactionalCompanyRepository) Delete(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransactionalCompanyRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTransactionalCompanyRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockTransactionalCompanyRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockTransactionalCompanyRepository_Delete_Call {
	return &MockTransactionalCompanyRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockTransactionalCompanyRepository_Delete_Call) Run(run func(ctx context.Context, id int)) *MockTransactionalCompanyRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockTransactionalCompanyRepository_Delete_Call) Return(_a0 error) *MockTransactionalCompanyRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactionalCompanyRepository_Delete_Call) RunAndReturn(run func(context.Context, int) error) *MockTransactionalCompanyRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: ctx
func (_m *MockTransactionalCompanyRepository) GetAll(ctx context.Context) ([]*models.Company, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*models.Company
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*models.Company, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*models.Company); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Company)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionalCompanyRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockTransactionalCompanyRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTransactionalCompanyRepository_Expecter) GetAll(ctx interface{}) *MockTransactionalCompanyRepository_GetAll_Call {
	return &MockTransactionalCompanyRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *MockTransactionalCompanyRepository_GetAll_Call) Run(run func(ctx context.Context)) *MockTransactionalCompanyRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockTransactionalCompanyRepository_GetAll_Call) Return(_a0 []*models.Company, _a1 error) *MockTransactionalCompanyRepository_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionalCompanyRepository_GetAll_Call) RunAndReturn(run func(context.Context) ([]*models.Company, error)) *MockTransactionalCompanyRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockTransactionalCompanyRepository) GetByID(ctx context.Context, id int) (*models.Company, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Company
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*models.Company, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *models.Company); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Company)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionalCompanyRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockTransactionalCompanyRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockTransactionalCompanyRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockTransactionalCompanyRepository_GetByID_Call {
	return &MockTransactionalCompanyRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockTransactionalCompanyRepository_GetByID_Call) Run(run func(ctx context.Context, id int)) *MockTransactionalCompanyRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockTransactionalCompanyRepository_GetByID_Call) Return(_a0 *models.Company, _a1 error) *MockTransactionalCompanyRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionalCompanyRepository_GetByID_Call) RunAndReturn(run func(context.Context, int) (*models.Company, error)) *MockTransactionalCompanyRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByName provides a mock function with given fields: ctx, name
func (_m *MockTransactionalCompanyRepository) GetByName(ctx context.Context, name string) (*models.Company, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 *models.Company
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Company, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Company); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Company)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionalCompanyRepository_GetByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByName'
type MockTransactionalCompanyRepository_GetByName_Call struct {
	*mock.Call
}

// GetByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockTransactionalCompanyRepository_Expecter) GetByName(ctx interface{}, name interface{}) *MockTransactionalCompanyRepository_GetByName_Call {
	return &MockTransactionalCompanyRepository_GetByName_Call{Call: _e.mock.On("GetByName", ctx, name)}
}

func (_c *MockTransactionalCompanyRepository_GetByName_Call) Run(run func(ctx context.Context, name string)) *MockTransactionalCompanyRepository_GetByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTransactionalCompanyRepository_GetByName_Call) Return(_a0 *models.Company, _a1 error) *MockTransactionalCompanyRepository_GetByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionalCompanyRepository_GetByName_Call) RunAndReturn(run func(context.Context, string) (*models.Company, error)) *MockTransactionalCompanyRepository_GetByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrCreate provides a mock function with given fields: ctx, name
func (_m *MockTransactionalCompanyRepository) GetOrCreate(ctx context.Context, name string) (*models.Company, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetOrCreate")
	}

	var r0 *models.Company
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Company, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Company); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Company)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionalCompanyRepository_GetOrCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrCreate'
type MockTransactionalCompanyRepository_GetOrCreate_Call struct {
	*mock.Call
}

// GetOrCreate is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockTransactionalCompanyRepository_Expecter) GetOrCreate(ctx interface{}, name interface{}) *MockTransactionalCompanyRepository_GetOrCreate_Call {
	return &MockTransactionalCompanyRepository_GetOrCreate_Call{Call: _e.mock.On("GetOrCreate", ctx, name)}
}

func (_c *MockTransactionalCompanyRepository_GetOrCreate_Call) Run(run func(ctx context.Context, name string)) *MockTransactionalCompanyRepository_GetOrCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTransactionalCompanyRepository_GetOrCreate_Call) Return(_a0 *models.Company, _a1 error) *MockTransactionalCompanyRepository_GetOrCreate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionalCompanyRepository_GetOrCreate_Call) RunAndReturn(run func(context.Context, string) (*models.Company, error)) *MockTransactionalCompanyRepository_GetOrCreate_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrCreateWithTx provides a mock function with given fields: ctx, tx, name
func (_m *MockTransactionalCompanyRepository) GetOrCreateWithTx(ctx context.Context, tx *sql.Tx, name string) (*models.Company, error) {
	ret := _m.Called(ctx, tx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetOrCreateWithTx")
	}

	var r0 *models.Company
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sql.Tx, string) (*models.Company, error)); ok {
		return rf(ctx, tx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sql.Tx, string) *models.Company); ok {
		r0 = rf(ctx, tx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Company)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sql.Tx, string) error); ok {
		r1 = rf(ctx, tx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionalCompanyRepository_GetOrCreateWithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrCreateWithTx'
type MockTransactionalCompanyRepository_GetOrCreateWithTx_Call struct {
	*mock.Call
}

// GetOrCreateWithTx is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sql.Tx
//   - name string
func (_e *MockTransactionalCompanyRepository_Expecter) GetOrCreateWithTx(ctx interface{}, tx interface{}, name interface{}) *MockTransactionalCompanyRepository_GetOrCreateWithTx_Call {
	return &MockTransactionalCompanyRepository_GetOrCreateWithTx_Call{Call: _e.mock.On("GetOrCreateWithTx", ctx, tx, name)}
}

func (_c *MockTransactionalCompanyRepository_GetOrCreateWithTx_Call) Run(run func(ctx context.Context, tx *sql.Tx, name string)) *MockTransactionalCompanyRepository_GetOrCreateWithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sql.Tx), args[2].(string))
	})
	return _c
}

func (_c *MockTransactionalCompanyRepository_GetOrCreateWithTx_Call) Return(_a0 *models.Company, _a1 error) *MockTransactionalCompanyRepository_GetOrCreateWithTx_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionalCompanyRepository_GetOrCreateWithTx_Call) RunAndReturn(run func(context.Context, *sql.Tx, string) (*models.Company, error)) *MockTransactionalCompanyRepository_GetOrCreateWithTx_Call {
	_c.Call.Return(run)
	return _c
}

// RollbackTx provides a mock function with given fields: tx
func (_m *MockTransactionalCompanyRepository) RollbackTx(tx *sql.Tx) error {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for RollbackTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*sql.Tx) error); ok {
		r0 = rf(tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransactionalCompanyRepository_RollbackTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RollbackTx'
type MockTransactionalCompanyRepository_RollbackTx_Call struct {
	*mock.Call
}

// RollbackTx is a helper method to define mock.On call
//   - tx *sql.Tx
func (_e *MockTransactionalCompanyRepository_Expecter) RollbackTx(tx interface{}) *MockTransactionalCompanyRepository_RollbackTx_Call {
	return &MockTransactionalCompanyRepository_RollbackTx_Call{Call: _e.mock.On("RollbackTx", tx)}
}

func (_c *MockTransactionalCompanyRepository_RollbackTx_Call) Run(run func(tx *sql.Tx)) *MockTransactionalCompanyRepository_RollbackTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*sql.Tx))
	})
	return _c
}

func (_c *MockTransactionalCompanyRepository_RollbackTx_Call) Return(_a0 error) *MockTransactionalCompanyRepository_RollbackTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactionalCompanyRepository_RollbackTx_Call) RunAndReturn(run func(*sql.Tx) error) *MockTransactionalCompanyRepository_RollbackTx_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, company
func (_m *MockTransactionalCompanyRepository) Update(ctx context.Context, company *models.Company) error {
	ret := _m.Called(ctx, company)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Company) error); ok {
		r0 = rf(ctx, company)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransactionalCompanyRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTransactionalCompanyRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - company *models.Company
func (_e *MockTransactionalCompanyRepository_Expecter) Update(ctx interface{}, company interface{}) *MockTransactionalCompanyRepository_Update_Call {
	return &MockTransactionalCompanyRepository_Update_Call{Call: _e.mock.On("Update", ctx, company)}
}

func (_c *MockTransactionalCompanyRepository_Update_Call) Run(run func(ctx context.Context, company *models.Company)) *MockTransactionalCompanyRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Company))
	})
	return _c
}

func (_c *MockTransactionalCompanyRepository_Update_Call) Return(_a0 error) *MockTransactionalCompanyRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactionalCompanyRepository_Update_Call) RunAndReturn(run func(context.Context, *models.Company) error) *MockTransactionalCompanyRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateWithTx provides a mock function with given fields: ctx, tx, company
func (_m *MockTransactionalCompanyRepository) UpdateWithTx(ctx context.Context, tx *sql.Tx, company *models.Company) error {
	ret := _m.Called(ctx, tx, company)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWithTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sql.Tx, *models.Company) error); ok {
		r0 = rf(ctx, tx, company)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransactionalCompanyRepository_UpdateWithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateWithTx'
type MockTransactionalCompanyRepository_UpdateWithTx_Call struct {
	*mock.Call
}

// UpdateWithTx is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sql.Tx
//   - company *models.Company
func (_e *MockTransactionalCompanyRepository_Expecter) UpdateWithTx(ctx interface{}, tx interface{}, company interface{}) *MockTransactionalCompanyRepository_UpdateWithTx_Call {
	return &MockTransactionalCompanyRepository_UpdateWithTx_Call{Call: _e.mock.On("UpdateWithTx", ctx, tx, company)}
}

func (_c *MockTransactionalCompanyRepository_UpdateWithTx_Call) Run(run func(ctx context.Context, tx *sql.Tx, company *models.Company)) *MockTransactionalCompanyRepository_UpdateWithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sql.Tx), args[2].(*models.Company))
	})
	return _c
}

func (_c *MockTransactionalCompanyRepository_UpdateWithTx_Call) Return(_a0 error) *MockTransactionalCompanyRepository_UpdateWithTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactionalCompanyRepository_UpdateWithTx_Call) RunAndReturn(run func(context.Context, *sql.Tx, *models.Company) error) *MockTransactionalCompanyRepository_UpdateWithTx_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransactionalCompanyRepository creates a new instance of MockTransactionalCompanyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionalCompanyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionalCompanyRepository {
	mock := &MockTransactionalCompanyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
