// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/benidevo/vega/internal/job/models"
)

// MockCompanyRepository is an autogenerated mock type for the CompanyRepository type
type MockCompanyRepository struct {
	mock.Mock
}

type MockCompanyRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCompanyRepository) EXPECT() *MockCompanyRepository_Expecter {
	return &MockCompanyRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockCompanyRepository) Delete(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCompanyRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCompanyRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockCompanyRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockCompanyRepository_Delete_Call {
	return &MockCompanyRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockCompanyRepository_Delete_Call) Run(run func(ctx context.Context, id int)) *MockCompanyRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockCompanyRepository_Delete_Call) Return(_a0 error) *MockCompanyRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCompanyRepository_Delete_Call) RunAndReturn(run func(context.Context, int) error) *MockCompanyRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: ctx
func (_m *MockCompanyRepository) GetAll(ctx context.Context) ([]*models.Company, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*models.Company
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*models.Company, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*models.Company); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Company)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCompanyRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockCompanyRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCompanyRepository_Expecter) GetAll(ctx interface{}) *MockCompanyRepository_GetAll_Call {
	return &MockCompanyRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *MockCompanyRepository_GetAll_Call) Run(run func(ctx context.Context)) *MockCompanyRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockCompanyRepository_GetAll_Call) Return(_a0 []*models.Company, _a1 error) *MockCompanyRepository_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCompanyRepository_GetAll_Call) RunAndReturn(run func(context.Context) ([]*models.Company, error)) *MockCompanyRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockCompanyRepository) GetByID(ctx context.Context, id int) (*models.Company, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Company
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*models.Company, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *models.Company); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Company)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCompanyRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockCompanyRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockCompanyRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockCompanyRepository_GetByID_Call {
	return &MockCompanyRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockCompanyRepository_GetByID_Call) Run(run func(ctx context.Context, id int)) *MockCompanyRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockCompanyRepository_GetByID_Call) Return(_a0 *models.Company, _a1 error) *MockCompanyRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCompanyRepository_GetByID_Call) RunAndReturn(run func(context.Context, int) (*models.Company, error)) *MockCompanyRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByName provides a mock function with given fields: ctx, name
func (_m *MockCompanyRepository) GetByName(ctx context.Context, name string) (*models.Company, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 *models.Company
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Company, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Company); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Company)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCompanyRepository_GetByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByName'
type MockCompanyRepository_GetByName_Call struct {
	*mock.Call
}

// GetByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockCompanyRepository_Expecter) GetByName(ctx interface{}, name interface{}) *MockCompanyRepository_GetByName_Call {
	return &MockCompanyRepository_GetByName_Call{Call: _e.mock.On("GetByName", ctx, name)}
}

func (_c *MockCompanyRepository_GetByName_Call) Run(run func(ctx context.Context, name string)) *MockCompanyRepository_GetByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCompanyRepository_GetByName_Call) Return(_a0 *models.Company, _a1 error) *MockCompanyRepository_GetByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCompanyRepository_GetByName_Call) RunAndReturn(run func(context.Context, string) (*models.Company, error)) *MockCompanyRepository_GetByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrCreate provides a mock function with given fields: ctx, name
func (_m *MockCompanyRepository) GetOrCreate(ctx context.Context, name string) (*models.Company, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetOrCreate")
	}

	var r0 *models.Company
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Company, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Company); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Company)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCompanyRepository_GetOrCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrCreate'
type MockCompanyRepository_GetOrCreate_Call struct {
	*mock.Call
}

// GetOrCreate is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockCompanyRepository_Expecter) GetOrCreate(ctx interface{}, name interface{}) *MockCompanyRepository_GetOrCreate_Call {
	return &MockCompanyRepository_GetOrCreate_Call{Call: _e.mock.On("GetOrCreate", ctx, name)}
}

func (_c *MockCompanyRepository_GetOrCreate_Call) Run(run func(ctx context.Context, name string)) *MockCompanyRepository_GetOrCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCompanyRepository_GetOrCreate_Call) Return(_a0 *models.Company, _a1 error) *MockCompanyRepository_GetOrCreate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCompanyRepository_GetOrCreate_Call) RunAndReturn(run func(context.Context, string) (*models.Company, error)) *MockCompanyRepository_GetOrCreate_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, company
func (_m *MockCompanyRepository) Update(ctx context.Context, company *models.Company) error {
	ret := _m.Called(ctx, company)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Company) error); ok {
		r0 = rf(ctx, company)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCompanyRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockCompanyRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - company *models.Company
func (_e *MockCompanyRepository_Expecter) Update(ctx interface{}, company interface{}) *MockCompanyRepository_Update_Call {
	return &MockCompanyRepository_Update_Call{Call: _e.mock.On("Update", ctx, company)}
}

func (_c *MockCompanyRepository_Update_Call) Run(run func(ctx context.Context, company *models.Company)) *MockCompanyRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Company))
	})
	return _c
}

func (_c *MockCompanyRepository_Update_Call) Return(_a0 error) *MockCompanyRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCompanyRepository_Update_Call) RunAndReturn(run func(context.Context, *models.Company) error) *MockCompanyRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCompanyRepository creates a new instance of MockCompanyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCompanyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCompanyRepository {
	mock := &MockCompanyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
