// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	sql "database/sql"
)

// MockTransactionalRepository is an autogenerated mock type for the TransactionalRepository type
type MockTransactionalRepository struct {
	mock.Mock
}

type MockTransactionalRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionalRepository) EXPECT() *MockTransactionalRepository_Expecter {
	return &MockTransactionalRepository_Expecter{mock: &_m.Mock}
}

// BeginTx provides a mock function with given fields: ctx, opts
func (_m *MockTransactionalRepository) BeginTx(ctx context.Context, opts *sql.TxOptions) (*sql.Tx, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for BeginTx")
	}

	var r0 *sql.Tx
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sql.TxOptions) (*sql.Tx, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sql.TxOptions) *sql.Tx); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Tx)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sql.TxOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionalRepository_BeginTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginTx'
type MockTransactionalRepository_BeginTx_Call struct {
	*mock.Call
}

// BeginTx is a helper method to define mock.On call
//   - ctx context.Context
//   - opts *sql.TxOptions
func (_e *MockTransactionalRepository_Expecter) BeginTx(ctx interface{}, opts interface{}) *MockTransactionalRepository_BeginTx_Call {
	return &MockTransactionalRepository_BeginTx_Call{Call: _e.mock.On("BeginTx", ctx, opts)}
}

func (_c *MockTransactionalRepository_BeginTx_Call) Run(run func(ctx context.Context, opts *sql.TxOptions)) *MockTransactionalRepository_BeginTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sql.TxOptions))
	})
	return _c
}

func (_c *MockTransactionalRepository_BeginTx_Call) Return(_a0 *sql.Tx, _a1 error) *MockTransactionalRepository_BeginTx_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionalRepository_BeginTx_Call) RunAndReturn(run func(context.Context, *sql.TxOptions) (*sql.Tx, error)) *MockTransactionalRepository_BeginTx_Call {
	_c.Call.Return(run)
	return _c
}

// CommitTx provides a mock function with given fields: tx
func (_m *MockTransactionalRepository) CommitTx(tx *sql.Tx) error {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for CommitTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*sql.Tx) error); ok {
		r0 = rf(tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransactionalRepository_CommitTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CommitTx'
type MockTransactionalRepository_CommitTx_Call struct {
	*mock.Call
}

// CommitTx is a helper method to define mock.On call
//   - tx *sql.Tx
func (_e *MockTransactionalRepository_Expecter) CommitTx(tx interface{}) *MockTransactionalRepository_CommitTx_Call {
	return &MockTransactionalRepository_CommitTx_Call{Call: _e.mock.On("CommitTx", tx)}
}

func (_c *MockTransactionalRepository_CommitTx_Call) Run(run func(tx *sql.Tx)) *MockTransactionalRepository_CommitTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*sql.Tx))
	})
	return _c
}

func (_c *MockTransactionalRepository_CommitTx_Call) Return(_a0 error) *MockTransactionalRepository_CommitTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactionalRepository_CommitTx_Call) RunAndReturn(run func(*sql.Tx) error) *MockTransactionalRepository_CommitTx_Call {
	_c.Call.Return(run)
	return _c
}

// RollbackTx provides a mock function with given fields: tx
func (_m *MockTransactionalRepository) RollbackTx(tx *sql.Tx) error {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for RollbackTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*sql.Tx) error); ok {
		r0 = rf(tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransactionalRepository_RollbackTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RollbackTx'
type MockTransactionalRepository_RollbackTx_Call struct {
	*mock.Call
}

// RollbackTx is a helper method to define mock.On call
//   - tx *sql.Tx
func (_e *MockTransactionalRepository_Expecter) RollbackTx(tx interface{}) *MockTransactionalRepository_RollbackTx_Call {
	return &MockTransactionalRepository_RollbackTx_Call{Call: _e.mock.On("RollbackTx", tx)}
}

func (_c *MockTransactionalRepository_RollbackTx_Call) Run(run func(tx *sql.Tx)) *MockTransactionalRepository_RollbackTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*sql.Tx))
	})
	return _c
}

func (_c *MockTransactionalRepository_RollbackTx_Call) Return(_a0 error) *MockTransactionalRepository_RollbackTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactionalRepository_RollbackTx_Call) RunAndReturn(run func(*sql.Tx) error) *MockTransactionalRepository_RollbackTx_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransactionalRepository creates a new instance of MockTransactionalRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionalRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionalRepository {
	mock := &MockTransactionalRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
