// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	sql "database/sql"

	models "github.com/benidevo/vega/internal/job/models"
	mock "github.com/stretchr/testify/mock"
)

// MockTransactionalJobRepository is an autogenerated mock type for the TransactionalJobRepository type
type MockTransactionalJobRepository struct {
	mock.Mock
}

type MockTransactionalJobRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionalJobRepository) EXPECT() *MockTransactionalJobRepository_Expecter {
	return &MockTransactionalJobRepository_Expecter{mock: &_m.Mock}
}

// BeginTx provides a mock function with given fields: ctx, opts
func (_m *MockTransactionalJobRepository) BeginTx(ctx context.Context, opts *sql.TxOptions) (*sql.Tx, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for BeginTx")
	}

	var r0 *sql.Tx
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sql.TxOptions) (*sql.Tx, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sql.TxOptions) *sql.Tx); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Tx)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sql.TxOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionalJobRepository_BeginTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginTx'
type MockTransactionalJobRepository_BeginTx_Call struct {
	*mock.Call
}

// BeginTx is a helper method to define mock.On call
//   - ctx context.Context
//   - opts *sql.TxOptions
func (_e *MockTransactionalJobRepository_Expecter) BeginTx(ctx interface{}, opts interface{}) *MockTransactionalJobRepository_BeginTx_Call {
	return &MockTransactionalJobRepository_BeginTx_Call{Call: _e.mock.On("BeginTx", ctx, opts)}
}

func (_c *MockTransactionalJobRepository_BeginTx_Call) Run(run func(ctx context.Context, opts *sql.TxOptions)) *MockTransactionalJobRepository_BeginTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sql.TxOptions))
	})
	return _c
}

func (_c *MockTransactionalJobRepository_BeginTx_Call) Return(_a0 *sql.Tx, _a1 error) *MockTransactionalJobRepository_BeginTx_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionalJobRepository_BeginTx_Call) RunAndReturn(run func(context.Context, *sql.TxOptions) (*sql.Tx, error)) *MockTransactionalJobRepository_BeginTx_Call {
	_c.Call.Return(run)
	return _c
}

// CommitTx provides a mock function with given fields: tx
func (_m *MockTransactionalJobRepository) CommitTx(tx *sql.Tx) error {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for CommitTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*sql.Tx) error); ok {
		r0 = rf(tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransactionalJobRepository_CommitTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CommitTx'
type MockTransactionalJobRepository_CommitTx_Call struct {
	*mock.Call
}

// CommitTx is a helper method to define mock.On call
//   - tx *sql.Tx
func (_e *MockTransactionalJobRepository_Expecter) CommitTx(tx interface{}) *MockTransactionalJobRepository_CommitTx_Call {
	return &MockTransactionalJobRepository_CommitTx_Call{Call: _e.mock.On("CommitTx", tx)}
}

func (_c *MockTransactionalJobRepository_CommitTx_Call) Run(run func(tx *sql.Tx)) *MockTransactionalJobRepository_CommitTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*sql.Tx))
	})
	return _c
}

func (_c *MockTransactionalJobRepository_CommitTx_Call) Return(_a0 error) *MockTransactionalJobRepository_CommitTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactionalJobRepository_CommitTx_Call) RunAndReturn(run func(*sql.Tx) error) *MockTransactionalJobRepository_CommitTx_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, userID, job
func (_m *MockTransactionalJobRepository) Create(ctx context.Context, userID int, job *models.Job) (*models.Job, error) {
	ret := _m.Called(ctx, userID, job)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.Job
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, *models.Job) (*models.Job, error)); ok {
		return rf(ctx, userID, job)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, *models.Job) *models.Job); ok {
		r0 = rf(ctx, userID, job)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Job)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, *models.Job) error); ok {
		r1 = rf(ctx, userID, job)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionalJobRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTransactionalJobRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - job *models.Job
func (_e *MockTransactionalJobRepository_Expecter) Create(ctx interface{}, userID interface{}, job interface{}) *MockTransactionalJobRepository_Create_Call {
	return &MockTransactionalJobRepository_Create_Call{Call: _e.mock.On("Create", ctx, userID, job)}
}

func (_c *MockTransactionalJobRepository_Create_Call) Run(run func(ctx context.Context, userID int, job *models.Job)) *MockTransactionalJobRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(*models.Job))
	})
	return _c
}

func (_c *MockTransactionalJobRepository_Create_Call) Return(_a0 *models.Job, _a1 error) *MockTransactionalJobRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionalJobRepository_Create_Call) RunAndReturn(run func(context.Context, int, *models.Job) (*models.Job, error)) *MockTransactionalJobRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateMatchResult provides a mock function with given fields: ctx, userID, matchResult
func (_m *MockTransactionalJobRepository) CreateMatchResult(ctx context.Context, userID int, matchResult *models.MatchResult) error {
	ret := _m.Called(ctx, userID, matchResult)

	if len(ret) == 0 {
		panic("no return value specified for CreateMatchResult")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, *models.MatchResult) error); ok {
		r0 = rf(ctx, userID, matchResult)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransactionalJobRepository_CreateMatchResult_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMatchResult'
type MockTransactionalJobRepository_CreateMatchResult_Call struct {
	*mock.Call
}

// CreateMatchResult is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - matchResult *models.MatchResult
func (_e *MockTransactionalJobRepository_Expecter) CreateMatchResult(ctx interface{}, userID interface{}, matchResult interface{}) *MockTransactionalJobRepository_CreateMatchResult_Call {
	return &MockTransactionalJobRepository_CreateMatchResult_Call{Call: _e.mock.On("CreateMatchResult", ctx, userID, matchResult)}
}

func (_c *MockTransactionalJobRepository_CreateMatchResult_Call) Run(run func(ctx context.Context, userID int, matchResult *models.MatchResult)) *MockTransactionalJobRepository_CreateMatchResult_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(*models.MatchResult))
	})
	return _c
}

func (_c *MockTransactionalJobRepository_CreateMatchResult_Call) Return(_a0 error) *MockTransactionalJobRepository_CreateMatchResult_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactionalJobRepository_CreateMatchResult_Call) RunAndReturn(run func(context.Context, int, *models.MatchResult) error) *MockTransactionalJobRepository_CreateMatchResult_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWithTx provides a mock function with given fields: ctx, tx, userID, job
func (_m *MockTransactionalJobRepository) CreateWithTx(ctx context.Context, tx *sql.Tx, userID int, job *models.Job) (*models.Job, error) {
	ret := _m.Called(ctx, tx, userID, job)

	if len(ret) == 0 {
		panic("no return value specified for CreateWithTx")
	}

	var r0 *models.Job
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sql.Tx, int, *models.Job) (*models.Job, error)); ok {
		return rf(ctx, tx, userID, job)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sql.Tx, int, *models.Job) *models.Job); ok {
		r0 = rf(ctx, tx, userID, job)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Job)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sql.Tx, int, *models.Job) error); ok {
		r1 = rf(ctx, tx, userID, job)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionalJobRepository_CreateWithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWithTx'
type MockTransactionalJobRepository_CreateWithTx_Call struct {
	*mock.Call
}

// CreateWithTx is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sql.Tx
//   - userID int
//   - job *models.Job
func (_e *MockTransactionalJobRepository_Expecter) CreateWithTx(ctx interface{}, tx interface{}, userID interface{}, job interface{}) *MockTransactionalJobRepository_CreateWithTx_Call {
	return &MockTransactionalJobRepository_CreateWithTx_Call{Call: _e.mock.On("CreateWithTx", ctx, tx, userID, job)}
}

func (_c *MockTransactionalJobRepository_CreateWithTx_Call) Run(run func(ctx context.Context, tx *sql.Tx, userID int, job *models.Job)) *MockTransactionalJobRepository_CreateWithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sql.Tx), args[2].(int), args[3].(*models.Job))
	})
	return _c
}

func (_c *MockTransactionalJobRepository_CreateWithTx_Call) Return(_a0 *models.Job, _a1 error) *MockTransactionalJobRepository_CreateWithTx_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionalJobRepository_CreateWithTx_Call) RunAndReturn(run func(context.Context, *sql.Tx, int, *models.Job) (*models.Job, error)) *MockTransactionalJobRepository_CreateWithTx_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, userID, id
func (_m *MockTransactionalJobRepository) Delete(ctx context.Context, userID int, id int) error {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransactionalJobRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTransactionalJobRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - id int
func (_e *MockTransactionalJobRepository_Expecter) Delete(ctx interface{}, userID interface{}, id interface{}) *MockTransactionalJobRepository_Delete_Call {
	return &MockTransactionalJobRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, userID, id)}
}

func (_c *MockTransactionalJobRepository_Delete_Call) Run(run func(ctx context.Context, userID int, id int)) *MockTransactionalJobRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockTransactionalJobRepository_Delete_Call) Return(_a0 error) *MockTransactionalJobRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactionalJobRepository_Delete_Call) RunAndReturn(run func(context.Context, int, int) error) *MockTransactionalJobRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteMatchResult provides a mock function with given fields: ctx, userID, matchID
func (_m *MockTransactionalJobRepository) DeleteMatchResult(ctx context.Context, userID int, matchID int) error {
	ret := _m.Called(ctx, userID, matchID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMatchResult")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, userID, matchID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransactionalJobRepository_DeleteMatchResult_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMatchResult'
type MockTransactionalJobRepository_DeleteMatchResult_Call struct {
	*mock.Call
}

// DeleteMatchResult is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - matchID int
func (_e *MockTransactionalJobRepository_Expecter) DeleteMatchResult(ctx interface{}, userID interface{}, matchID interface{}) *MockTransactionalJobRepository_DeleteMatchResult_Call {
	return &MockTransactionalJobRepository_DeleteMatchResult_Call{Call: _e.mock.On("DeleteMatchResult", ctx, userID, matchID)}
}

func (_c *MockTransactionalJobRepository_DeleteMatchResult_Call) Run(run func(ctx context.Context, userID int, matchID int)) *MockTransactionalJobRepository_DeleteMatchResult_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockTransactionalJobRepository_DeleteMatchResult_Call) Return(_a0 error) *MockTransactionalJobRepository_DeleteMatchResult_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactionalJobRepository_DeleteMatchResult_Call) RunAndReturn(run func(context.Context, int, int) error) *MockTransactionalJobRepository_DeleteMatchResult_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteWithTx provides a mock function with given fields: ctx, tx, userID, id
func (_m *MockTransactionalJobRepository) DeleteWithTx(ctx context.Context, tx *sql.Tx, userID int, id int) error {
	ret := _m.Called(ctx, tx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteWithTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sql.Tx, int, int) error); ok {
		r0 = rf(ctx, tx, userID, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransactionalJobRepository_DeleteWithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteWithTx'
type MockTransactionalJobRepository_DeleteWithTx_Call struct {
	*mock.Call
}

// DeleteWithTx is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sql.Tx
//   - userID int
//   - id int
func (_e *MockTransactionalJobRepository_Expecter) DeleteWithTx(ctx interface{}, tx interface{}, userID interface{}, id interface{}) *MockTransactionalJobRepository_DeleteWithTx_Call {
	return &MockTransactionalJobRepository_DeleteWithTx_Call{Call: _e.mock.On("DeleteWithTx", ctx, tx, userID, id)}
}

func (_c *MockTransactionalJobRepository_DeleteWithTx_Call) Run(run func(ctx context.Context, tx *sql.Tx, userID int, id int)) *MockTransactionalJobRepository_DeleteWithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sql.Tx), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockTransactionalJobRepository_DeleteWithTx_Call) Return(_a0 error) *MockTransactionalJobRepository_DeleteWithTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactionalJobRepository_DeleteWithTx_Call) RunAndReturn(run func(context.Context, *sql.Tx, int, int) error) *MockTransactionalJobRepository_DeleteWithTx_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: ctx, userID, filter
func (_m *MockTransactionalJobRepository) GetAll(ctx context.Context, userID int, filter models.JobFilter) ([]*models.Job, error) {
	ret := _m.Called(ctx, userID, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*models.Job
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, models.JobFilter) ([]*models.Job, error)); ok {
		return rf(ctx, userID, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, models.JobFilter) []*models.Job); ok {
		r0 = rf(ctx, userID, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Job)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, models.JobFilter) error); ok {
		r1 = rf(ctx, userID, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionalJobRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockTransactionalJobRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - filter models.JobFilter
func (_e *MockTransactionalJobRepository_Expecter) GetAll(ctx interface{}, userID interface{}, filter interface{}) *MockTransactionalJobRepository_GetAll_Call {
	return &MockTransactionalJobRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx, userID, filter)}
}

func (_c *MockTransactionalJobRepository_GetAll_Call) Run(run func(ctx context.Context, userID int, filter models.JobFilter)) *MockTransactionalJobRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(models.JobFilter))
	})
	return _c
}

func (_c *MockTransactionalJobRepository_GetAll_Call) Return(_a0 []*models.Job, _a1 error) *MockTransactionalJobRepository_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionalJobRepository_GetAll_Call) RunAndReturn(run func(context.Context, int, models.JobFilter) ([]*models.Job, error)) *MockTransactionalJobRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, userID, id
func (_m *MockTransactionalJobRepository) GetByID(ctx context.Context, userID int, id int) (*models.Job, error) {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Job
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) (*models.Job, error)); ok {
		return rf(ctx, userID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) *models.Job); ok {
		r0 = rf(ctx, userID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Job)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, userID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionalJobRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockTransactionalJobRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - id int
func (_e *MockTransactionalJobRepository_Expecter) GetByID(ctx interface{}, userID interface{}, id interface{}) *MockTransactionalJobRepository_GetByID_Call {
	return &MockTransactionalJobRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, userID, id)}
}

func (_c *MockTransactionalJobRepository_GetByID_Call) Run(run func(ctx context.Context, userID int, id int)) *MockTransactionalJobRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockTransactionalJobRepository_GetByID_Call) Return(_a0 *models.Job, _a1 error) *MockTransactionalJobRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionalJobRepository_GetByID_Call) RunAndReturn(run func(context.Context, int, int) (*models.Job, error)) *MockTransactionalJobRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetBySourceURL provides a mock function with given fields: ctx, userID, sourceURL
func (_m *MockTransactionalJobRepository) GetBySourceURL(ctx context.Context, userID int, sourceURL string) (*models.Job, error) {
	ret := _m.Called(ctx, userID, sourceURL)

	if len(ret) == 0 {
		panic("no return value specified for GetBySourceURL")
	}

	var r0 *models.Job
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string) (*models.Job, error)); ok {
		return rf(ctx, userID, sourceURL)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, string) *models.Job); ok {
		r0 = rf(ctx, userID, sourceURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Job)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, string) error); ok {
		r1 = rf(ctx, userID, sourceURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionalJobRepository_GetBySourceURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBySourceURL'
type MockTransactionalJobRepository_GetBySourceURL_Call struct {
	*mock.Call
}

// GetBySourceURL is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - sourceURL string
func (_e *MockTransactionalJobRepository_Expecter) GetBySourceURL(ctx interface{}, userID interface{}, sourceURL interface{}) *MockTransactionalJobRepository_GetBySourceURL_Call {
	return &MockTransactionalJobRepository_GetBySourceURL_Call{Call: _e.mock.On("GetBySourceURL", ctx, userID, sourceURL)}
}

func (_c *MockTransactionalJobRepository_GetBySourceURL_Call) Run(run func(ctx context.Context, userID int, sourceURL string)) *MockTransactionalJobRepository_GetBySourceURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(string))
	})
	return _c
}

func (_c *MockTransactionalJobRepository_GetBySourceURL_Call) Return(_a0 *models.Job, _a1 error) *MockTransactionalJobRepository_GetBySourceURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionalJobRepository_GetBySourceURL_Call) RunAndReturn(run func(context.Context, int, string) (*models.Job, error)) *MockTransactionalJobRepository_GetBySourceURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetCount provides a mock function with given fields: ctx, userID, filter
func (_m *MockTransactionalJobRepository) GetCount(ctx context.Context, userID int, filter models.JobFilter) (int, error) {
	ret := _m.Called(ctx, userID, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetCount")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, models.JobFilter) (int, error)); ok {
		return rf(ctx, userID, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, models.JobFilter) int); ok {
		r0 = rf(ctx, userID, filter)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, models.JobFilter) error); ok {
		r1 = rf(ctx, userID, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionalJobRepository_GetCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCount'
type MockTransactionalJobRepository_GetCount_Call struct {
	*mock.Call
}

// GetCount is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - filter models.JobFilter
func (_e *MockTransactionalJobRepository_Expecter) GetCount(ctx interface{}, userID interface{}, filter interface{}) *MockTransactionalJobRepository_GetCount_Call {
	return &MockTransactionalJobRepository_GetCount_Call{Call: _e.mock.On("GetCount", ctx, userID, filter)}
}

func (_c *MockTransactionalJobRepository_GetCount_Call) Run(run func(ctx context.Context, userID int, filter models.JobFilter)) *MockTransactionalJobRepository_GetCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(models.JobFilter))
	})
	return _c
}

func (_c *MockTransactionalJobRepository_GetCount_Call) Return(_a0 int, _a1 error) *MockTransactionalJobRepository_GetCount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionalJobRepository_GetCount_Call) RunAndReturn(run func(context.Context, int, models.JobFilter) (int, error)) *MockTransactionalJobRepository_GetCount_Call {
	_c.Call.Return(run)
	return _c
}

// GetJobMatchHistory provides a mock function with given fields: ctx, userID, jobID
func (_m *MockTransactionalJobRepository) GetJobMatchHistory(ctx context.Context, userID int, jobID int) ([]*models.MatchResult, error) {
	ret := _m.Called(ctx, userID, jobID)

	if len(ret) == 0 {
		panic("no return value specified for GetJobMatchHistory")
	}

	var r0 []*models.MatchResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]*models.MatchResult, error)); ok {
		return rf(ctx, userID, jobID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []*models.MatchResult); ok {
		r0 = rf(ctx, userID, jobID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.MatchResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, userID, jobID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionalJobRepository_GetJobMatchHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetJobMatchHistory'
type MockTransactionalJobRepository_GetJobMatchHistory_Call struct {
	*mock.Call
}

// GetJobMatchHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - jobID int
func (_e *MockTransactionalJobRepository_Expecter) GetJobMatchHistory(ctx interface{}, userID interface{}, jobID interface{}) *MockTransactionalJobRepository_GetJobMatchHistory_Call {
	return &MockTransactionalJobRepository_GetJobMatchHistory_Call{Call: _e.mock.On("GetJobMatchHistory", ctx, userID, jobID)}
}

func (_c *MockTransactionalJobRepository_GetJobMatchHistory_Call) Run(run func(ctx context.Context, userID int, jobID int)) *MockTransactionalJobRepository_GetJobMatchHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockTransactionalJobRepository_GetJobMatchHistory_Call) Return(_a0 []*models.MatchResult, _a1 error) *MockTransactionalJobRepository_GetJobMatchHistory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionalJobRepository_GetJobMatchHistory_Call) RunAndReturn(run func(context.Context, int, int) ([]*models.MatchResult, error)) *MockTransactionalJobRepository_GetJobMatchHistory_Call {
	_c.Call.Return(run)
	return _c
}

// GetJobStatsByStatus provides a mock function with given fields: ctx, userID
func (_m *MockTransactionalJobRepository) GetJobStatsByStatus(ctx context.Context, userID int) (map[models.JobStatus]int, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetJobStatsByStatus")
	}

	var r0 map[models.JobStatus]int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (map[models.JobStatus]int, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) map[models.JobStatus]int); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[models.JobStatus]int)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionalJobRepository_GetJobStatsByStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetJobStatsByStatus'
type MockTransactionalJobRepository_GetJobStatsByStatus_Call struct {
	*mock.Call
}

// GetJobStatsByStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockTransactionalJobRepository_Expecter) GetJobStatsByStatus(ctx interface{}, userID interface{}) *MockTransactionalJobRepository_GetJobStatsByStatus_Call {
	return &MockTransactionalJobRepository_GetJobStatsByStatus_Call{Call: _e.mock.On("GetJobStatsByStatus", ctx, userID)}
}

func (_c *MockTransactionalJobRepository_GetJobStatsByStatus_Call) Run(run func(ctx context.Context, userID int)) *MockTransactionalJobRepository_GetJobStatsByStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockTransactionalJobRepository_GetJobStatsByStatus_Call) Return(_a0 map[models.JobStatus]int, _a1 error) *MockTransactionalJobRepository_GetJobStatsByStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionalJobRepository_GetJobStatsByStatus_Call) RunAndReturn(run func(context.Context, int) (map[models.JobStatus]int, error)) *MockTransactionalJobRepository_GetJobStatsByStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetMonthlyAnalysisCount provides a mock function with given fields: ctx, userID
func (_m *MockTransactionalJobRepository) GetMonthlyAnalysisCount(ctx context.Context, userID int) (int, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetMonthlyAnalysisCount")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (int, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) int); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionalJobRepository_GetMonthlyAnalysisCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMonthlyAnalysisCount'
type MockTransactionalJobRepository_GetMonthlyAnalysisCount_Call struct {
	*mock.Call
}

// GetMonthlyAnalysisCount is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockTransactionalJobRepository_Expecter) GetMonthlyAnalysisCount(ctx interface{}, userID interface{}) *MockTransactionalJobRepository_GetMonthlyAnalysisCount_Call {
	return &MockTransactionalJobRepository_GetMonthlyAnalysisCount_Call{Call: _e.mock.On("GetMonthlyAnalysisCount", ctx, userID)}
}

func (_c *MockTransactionalJobRepository_GetMonthlyAnalysisCount_Call) Run(run func(ctx context.Context, userID int)) *MockTransactionalJobRepository_GetMonthlyAnalysisCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockTransactionalJobRepository_GetMonthlyAnalysisCount_Call) Return(_a0 int, _a1 error) *MockTransactionalJobRepository_GetMonthlyAnalysisCount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionalJobRepository_GetMonthlyAnalysisCount_Call) RunAndReturn(run func(context.Context, int) (int, error)) *MockTransactionalJobRepository_GetMonthlyAnalysisCount_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrCreate provides a mock function with given fields: ctx, userID, job
func (_m *MockTransactionalJobRepository) GetOrCreate(ctx context.Context, userID int, job *models.Job) (*models.Job, bool, error) {
	ret := _m.Called(ctx, userID, job)

	if len(ret) == 0 {
		panic("no return value specified for GetOrCreate")
	}

	var r0 *models.Job
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, *models.Job) (*models.Job, bool, error)); ok {
		return rf(ctx, userID, job)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, *models.Job) *models.Job); ok {
		r0 = rf(ctx, userID, job)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Job)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, *models.Job) bool); ok {
		r1 = rf(ctx, userID, job)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, *models.Job) error); ok {
		r2 = rf(ctx, userID, job)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockTransactionalJobRepository_GetOrCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrCreate'
type MockTransactionalJobRepository_GetOrCreate_Call struct {
	*mock.Call
}

// GetOrCreate is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - job *models.Job
func (_e *MockTransactionalJobRepository_Expecter) GetOrCreate(ctx interface{}, userID interface{}, job interface{}) *MockTransactionalJobRepository_GetOrCreate_Call {
	return &MockTransactionalJobRepository_GetOrCreate_Call{Call: _e.mock.On("GetOrCreate", ctx, userID, job)}
}

func (_c *MockTransactionalJobRepository_GetOrCreate_Call) Run(run func(ctx context.Context, userID int, job *models.Job)) *MockTransactionalJobRepository_GetOrCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(*models.Job))
	})
	return _c
}

func (_c *MockTransactionalJobRepository_GetOrCreate_Call) Return(_a0 *models.Job, _a1 bool, _a2 error) *MockTransactionalJobRepository_GetOrCreate_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockTransactionalJobRepository_GetOrCreate_Call) RunAndReturn(run func(context.Context, int, *models.Job) (*models.Job, bool, error)) *MockTransactionalJobRepository_GetOrCreate_Call {
	_c.Call.Return(run)
	return _c
}

// GetRecentJobsByUserID provides a mock function with given fields: ctx, userID, limit
func (_m *MockTransactionalJobRepository) GetRecentJobsByUserID(ctx context.Context, userID int, limit int) ([]*models.Job, error) {
	ret := _m.Called(ctx, userID, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetRecentJobsByUserID")
	}

	var r0 []*models.Job
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]*models.Job, error)); ok {
		return rf(ctx, userID, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []*models.Job); ok {
		r0 = rf(ctx, userID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Job)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, userID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionalJobRepository_GetRecentJobsByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRecentJobsByUserID'
type MockTransactionalJobRepository_GetRecentJobsByUserID_Call struct {
	*mock.Call
}

// GetRecentJobsByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - limit int
func (_e *MockTransactionalJobRepository_Expecter) GetRecentJobsByUserID(ctx interface{}, userID interface{}, limit interface{}) *MockTransactionalJobRepository_GetRecentJobsByUserID_Call {
	return &MockTransactionalJobRepository_GetRecentJobsByUserID_Call{Call: _e.mock.On("GetRecentJobsByUserID", ctx, userID, limit)}
}

func (_c *MockTransactionalJobRepository_GetRecentJobsByUserID_Call) Run(run func(ctx context.Context, userID int, limit int)) *MockTransactionalJobRepository_GetRecentJobsByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockTransactionalJobRepository_GetRecentJobsByUserID_Call) Return(_a0 []*models.Job, _a1 error) *MockTransactionalJobRepository_GetRecentJobsByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionalJobRepository_GetRecentJobsByUserID_Call) RunAndReturn(run func(context.Context, int, int) ([]*models.Job, error)) *MockTransactionalJobRepository_GetRecentJobsByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetRecentMatchResults provides a mock function with given fields: ctx, userID, limit
func (_m *MockTransactionalJobRepository) GetRecentMatchResults(ctx context.Context, userID int, limit int) ([]*models.MatchResult, error) {
	ret := _m.Called(ctx, userID, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetRecentMatchResults")
	}

	var r0 []*models.MatchResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]*models.MatchResult, error)); ok {
		return rf(ctx, userID, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []*models.MatchResult); ok {
		r0 = rf(ctx, userID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.MatchResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, userID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionalJobRepository_GetRecentMatchResults_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRecentMatchResults'
type MockTransactionalJobRepository_GetRecentMatchResults_Call struct {
	*mock.Call
}

// GetRecentMatchResults is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - limit int
func (_e *MockTransactionalJobRepository_Expecter) GetRecentMatchResults(ctx interface{}, userID interface{}, limit interface{}) *MockTransactionalJobRepository_GetRecentMatchResults_Call {
	return &MockTransactionalJobRepository_GetRecentMatchResults_Call{Call: _e.mock.On("GetRecentMatchResults", ctx, userID, limit)}
}

func (_c *MockTransactionalJobRepository_GetRecentMatchResults_Call) Run(run func(ctx context.Context, userID int, limit int)) *MockTransactionalJobRepository_GetRecentMatchResults_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockTransactionalJobRepository_GetRecentMatchResults_Call) Return(_a0 []*models.MatchResult, _a1 error) *MockTransactionalJobRepository_GetRecentMatchResults_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionalJobRepository_GetRecentMatchResults_Call) RunAndReturn(run func(context.Context, int, int) ([]*models.MatchResult, error)) *MockTransactionalJobRepository_GetRecentMatchResults_Call {
	_c.Call.Return(run)
	return _c
}

// GetRecentMatchResultsWithDetails provides a mock function with given fields: ctx, userID, limit, currentJobID
func (_m *MockTransactionalJobRepository) GetRecentMatchResultsWithDetails(ctx context.Context, userID int, limit int, currentJobID int) ([]*models.MatchSummary, error) {
	ret := _m.Called(ctx, userID, limit, currentJobID)

	if len(ret) == 0 {
		panic("no return value specified for GetRecentMatchResultsWithDetails")
	}

	var r0 []*models.MatchSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int) ([]*models.MatchSummary, error)); ok {
		return rf(ctx, userID, limit, currentJobID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int) []*models.MatchSummary); ok {
		r0 = rf(ctx, userID, limit, currentJobID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.MatchSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, int) error); ok {
		r1 = rf(ctx, userID, limit, currentJobID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionalJobRepository_GetRecentMatchResultsWithDetails_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRecentMatchResultsWithDetails'
type MockTransactionalJobRepository_GetRecentMatchResultsWithDetails_Call struct {
	*mock.Call
}

// GetRecentMatchResultsWithDetails is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - limit int
//   - currentJobID int
func (_e *MockTransactionalJobRepository_Expecter) GetRecentMatchResultsWithDetails(ctx interface{}, userID interface{}, limit interface{}, currentJobID interface{}) *MockTransactionalJobRepository_GetRecentMatchResultsWithDetails_Call {
	return &MockTransactionalJobRepository_GetRecentMatchResultsWithDetails_Call{Call: _e.mock.On("GetRecentMatchResultsWithDetails", ctx, userID, limit, currentJobID)}
}

func (_c *MockTransactionalJobRepository_GetRecentMatchResultsWithDetails_Call) Run(run func(ctx context.Context, userID int, limit int, currentJobID int)) *MockTransactionalJobRepository_GetRecentMatchResultsWithDetails_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockTransactionalJobRepository_GetRecentMatchResultsWithDetails_Call) Return(_a0 []*models.MatchSummary, _a1 error) *MockTransactionalJobRepository_GetRecentMatchResultsWithDetails_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionalJobRepository_GetRecentMatchResultsWithDetails_Call) RunAndReturn(run func(context.Context, int, int, int) ([]*models.MatchSummary, error)) *MockTransactionalJobRepository_GetRecentMatchResultsWithDetails_Call {
	_c.Call.Return(run)
	return _c
}

// GetStats provides a mock function with given fields: ctx, userID
func (_m *MockTransactionalJobRepository) GetStats(ctx context.Context, userID int) (*models.JobStats, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetStats")
	}

	var r0 *models.JobStats
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*models.JobStats, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *models.JobStats); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.JobStats)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionalJobRepository_GetStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStats'
type MockTransactionalJobRepository_GetStats_Call struct {
	*mock.Call
}

// GetStats is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockTransactionalJobRepository_Expecter) GetStats(ctx interface{}, userID interface{}) *MockTransactionalJobRepository_GetStats_Call {
	return &MockTransactionalJobRepository_GetStats_Call{Call: _e.mock.On("GetStats", ctx, userID)}
}

func (_c *MockTransactionalJobRepository_GetStats_Call) Run(run func(ctx context.Context, userID int)) *MockTransactionalJobRepository_GetStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockTransactionalJobRepository_GetStats_Call) Return(_a0 *models.JobStats, _a1 error) *MockTransactionalJobRepository_GetStats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionalJobRepository_GetStats_Call) RunAndReturn(run func(context.Context, int) (*models.JobStats, error)) *MockTransactionalJobRepository_GetStats_Call {
	_c.Call.Return(run)
	return _c
}

// GetStatsByUserID provides a mock function with given fields: ctx, userID
func (_m *MockTransactionalJobRepository) GetStatsByUserID(ctx context.Context, userID int) (*models.JobStats, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetStatsByUserID")
	}

	var r0 *models.JobStats
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*models.JobStats, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *models.JobStats); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.JobStats)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionalJobRepository_GetStatsByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatsByUserID'
type MockTransactionalJobRepository_GetStatsByUserID_Call struct {
	*mock.Call
}

// GetStatsByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockTransactionalJobRepository_Expecter) GetStatsByUserID(ctx interface{}, userID interface{}) *MockTransactionalJobRepository_GetStatsByUserID_Call {
	return &MockTransactionalJobRepository_GetStatsByUserID_Call{Call: _e.mock.On("GetStatsByUserID", ctx, userID)}
}

func (_c *MockTransactionalJobRepository_GetStatsByUserID_Call) Run(run func(ctx context.Context, userID int)) *MockTransactionalJobRepository_GetStatsByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockTransactionalJobRepository_GetStatsByUserID_Call) Return(_a0 *models.JobStats, _a1 error) *MockTransactionalJobRepository_GetStatsByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionalJobRepository_GetStatsByUserID_Call) RunAndReturn(run func(context.Context, int) (*models.JobStats, error)) *MockTransactionalJobRepository_GetStatsByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetTopMatchesByUserID provides a mock function with given fields: ctx, userID, limit
func (_m *MockTransactionalJobRepository) GetTopMatchesByUserID(ctx context.Context, userID int, limit int) ([]*models.Job, error) {
	ret := _m.Called(ctx, userID, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetTopMatchesByUserID")
	}

	var r0 []*models.Job
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]*models.Job, error)); ok {
		return rf(ctx, userID, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []*models.Job); ok {
		r0 = rf(ctx, userID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Job)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, userID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionalJobRepository_GetTopMatchesByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTopMatchesByUserID'
type MockTransactionalJobRepository_GetTopMatchesByUserID_Call struct {
	*mock.Call
}

// GetTopMatchesByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - limit int
func (_e *MockTransactionalJobRepository_Expecter) GetTopMatchesByUserID(ctx interface{}, userID interface{}, limit interface{}) *MockTransactionalJobRepository_GetTopMatchesByUserID_Call {
	return &MockTransactionalJobRepository_GetTopMatchesByUserID_Call{Call: _e.mock.On("GetTopMatchesByUserID", ctx, userID, limit)}
}

func (_c *MockTransactionalJobRepository_GetTopMatchesByUserID_Call) Run(run func(ctx context.Context, userID int, limit int)) *MockTransactionalJobRepository_GetTopMatchesByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockTransactionalJobRepository_GetTopMatchesByUserID_Call) Return(_a0 []*models.Job, _a1 error) *MockTransactionalJobRepository_GetTopMatchesByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionalJobRepository_GetTopMatchesByUserID_Call) RunAndReturn(run func(context.Context, int, int) ([]*models.Job, error)) *MockTransactionalJobRepository_GetTopMatchesByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// MatchResultBelongsToJob provides a mock function with given fields: ctx, userID, matchID, jobID
func (_m *MockTransactionalJobRepository) MatchResultBelongsToJob(ctx context.Context, userID int, matchID int, jobID int) (bool, error) {
	ret := _m.Called(ctx, userID, matchID, jobID)

	if len(ret) == 0 {
		panic("no return value specified for MatchResultBelongsToJob")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int) (bool, error)); ok {
		return rf(ctx, userID, matchID, jobID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int) bool); ok {
		r0 = rf(ctx, userID, matchID, jobID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, int) error); ok {
		r1 = rf(ctx, userID, matchID, jobID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionalJobRepository_MatchResultBelongsToJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MatchResultBelongsToJob'
type MockTransactionalJobRepository_MatchResultBelongsToJob_Call struct {
	*mock.Call
}

// MatchResultBelongsToJob is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - matchID int
//   - jobID int
func (_e *MockTransactionalJobRepository_Expecter) MatchResultBelongsToJob(ctx interface{}, userID interface{}, matchID interface{}, jobID interface{}) *MockTransactionalJobRepository_MatchResultBelongsToJob_Call {
	return &MockTransactionalJobRepository_MatchResultBelongsToJob_Call{Call: _e.mock.On("MatchResultBelongsToJob", ctx, userID, matchID, jobID)}
}

func (_c *MockTransactionalJobRepository_MatchResultBelongsToJob_Call) Run(run func(ctx context.Context, userID int, matchID int, jobID int)) *MockTransactionalJobRepository_MatchResultBelongsToJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockTransactionalJobRepository_MatchResultBelongsToJob_Call) Return(_a0 bool, _a1 error) *MockTransactionalJobRepository_MatchResultBelongsToJob_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionalJobRepository_MatchResultBelongsToJob_Call) RunAndReturn(run func(context.Context, int, int, int) (bool, error)) *MockTransactionalJobRepository_MatchResultBelongsToJob_Call {
	_c.Call.Return(run)
	return _c
}

// RollbackTx provides a mock function with given fields: tx
func (_m *MockTransactionalJobRepository) RollbackTx(tx *sql.Tx) error {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for RollbackTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*sql.Tx) error); ok {
		r0 = rf(tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransactionalJobRepository_RollbackTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RollbackTx'
type MockTransactionalJobRepository_RollbackTx_Call struct {
	*mock.Call
}

// RollbackTx is a helper method to define mock.On call
//   - tx *sql.Tx
func (_e *MockTransactionalJobRepository_Expecter) RollbackTx(tx interface{}) *MockTransactionalJobRepository_RollbackTx_Call {
	return &MockTransactionalJobRepository_RollbackTx_Call{Call: _e.mock.On("RollbackTx", tx)}
}

func (_c *MockTransactionalJobRepository_RollbackTx_Call) Run(run func(tx *sql.Tx)) *MockTransactionalJobRepository_RollbackTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*sql.Tx))
	})
	return _c
}

func (_c *MockTransactionalJobRepository_RollbackTx_Call) Return(_a0 error) *MockTransactionalJobRepository_RollbackTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactionalJobRepository_RollbackTx_Call) RunAndReturn(run func(*sql.Tx) error) *MockTransactionalJobRepository_RollbackTx_Call {
	_c.Call.Return(run)
	return _c
}

// SetFirstAnalyzedAt provides a mock function with given fields: ctx, jobID
func (_m *MockTransactionalJobRepository) SetFirstAnalyzedAt(ctx context.Context, jobID int) error {
	ret := _m.Called(ctx, jobID)

	if len(ret) == 0 {
		panic("no return value specified for SetFirstAnalyzedAt")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, jobID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransactionalJobRepository_SetFirstAnalyzedAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetFirstAnalyzedAt'
type MockTransactionalJobRepository_SetFirstAnalyzedAt_Call struct {
	*mock.Call
}

// SetFirstAnalyzedAt is a helper method to define mock.On call
//   - ctx context.Context
//   - jobID int
func (_e *MockTransactionalJobRepository_Expecter) SetFirstAnalyzedAt(ctx interface{}, jobID interface{}) *MockTransactionalJobRepository_SetFirstAnalyzedAt_Call {
	return &MockTransactionalJobRepository_SetFirstAnalyzedAt_Call{Call: _e.mock.On("SetFirstAnalyzedAt", ctx, jobID)}
}

func (_c *MockTransactionalJobRepository_SetFirstAnalyzedAt_Call) Run(run func(ctx context.Context, jobID int)) *MockTransactionalJobRepository_SetFirstAnalyzedAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockTransactionalJobRepository_SetFirstAnalyzedAt_Call) Return(_a0 error) *MockTransactionalJobRepository_SetFirstAnalyzedAt_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactionalJobRepository_SetFirstAnalyzedAt_Call) RunAndReturn(run func(context.Context, int) error) *MockTransactionalJobRepository_SetFirstAnalyzedAt_Call {
	_c.Call.Return(run)
	return _c
}

// SetFirstAnalyzedAtWithTx provides a mock function with given fields: ctx, tx, jobID
func (_m *MockTransactionalJobRepository) SetFirstAnalyzedAtWithTx(ctx context.Context, tx *sql.Tx, jobID int) error {
	ret := _m.Called(ctx, tx, jobID)

	if len(ret) == 0 {
		panic("no return value specified for SetFirstAnalyzedAtWithTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sql.Tx, int) error); ok {
		r0 = rf(ctx, tx, jobID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransactionalJobRepository_SetFirstAnalyzedAtWithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetFirstAnalyzedAtWithTx'
type MockTransactionalJobRepository_SetFirstAnalyzedAtWithTx_Call struct {
	*mock.Call
}

// SetFirstAnalyzedAtWithTx is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sql.Tx
//   - jobID int
func (_e *MockTransactionalJobRepository_Expecter) SetFirstAnalyzedAtWithTx(ctx interface{}, tx interface{}, jobID interface{}) *MockTransactionalJobRepository_SetFirstAnalyzedAtWithTx_Call {
	return &MockTransactionalJobRepository_SetFirstAnalyzedAtWithTx_Call{Call: _e.mock.On("SetFirstAnalyzedAtWithTx", ctx, tx, jobID)}
}

func (_c *MockTransactionalJobRepository_SetFirstAnalyzedAtWithTx_Call) Run(run func(ctx context.Context, tx *sql.Tx, jobID int)) *MockTransactionalJobRepository_SetFirstAnalyzedAtWithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sql.Tx), args[2].(int))
	})
	return _c
}

func (_c *MockTransactionalJobRepository_SetFirstAnalyzedAtWithTx_Call) Return(_a0 error) *MockTransactionalJobRepository_SetFirstAnalyzedAtWithTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactionalJobRepository_SetFirstAnalyzedAtWithTx_Call) RunAndReturn(run func(context.Context, *sql.Tx, int) error) *MockTransactionalJobRepository_SetFirstAnalyzedAtWithTx_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, userID, job
func (_m *MockTransactionalJobRepository) Update(ctx context.Context, userID int, job *models.Job) error {
	ret := _m.Called(ctx, userID, job)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, *models.Job) error); ok {
		r0 = rf(ctx, userID, job)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransactionalJobRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTransactionalJobRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - job *models.Job
func (_e *MockTransactionalJobRepository_Expecter) Update(ctx interface{}, userID interface{}, job interface{}) *MockTransactionalJobRepository_Update_Call {
	return &MockTransactionalJobRepository_Update_Call{Call: _e.mock.On("Update", ctx, userID, job)}
}

func (_c *MockTransactionalJobRepository_Update_Call) Run(run func(ctx context.Context, userID int, job *models.Job)) *MockTransactionalJobRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(*models.Job))
	})
	return _c
}

func (_c *MockTransactionalJobRepository_Update_Call) Return(_a0 error) *MockTransactionalJobRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactionalJobRepository_Update_Call) RunAndReturn(run func(context.Context, int, *models.Job) error) *MockTransactionalJobRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMatchScore provides a mock function with given fields: ctx, userID, jobID, matchScore
func (_m *MockTransactionalJobRepository) UpdateMatchScore(ctx context.Context, userID int, jobID int, matchScore *int) error {
	ret := _m.Called(ctx, userID, jobID, matchScore)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMatchScore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, *int) error); ok {
		r0 = rf(ctx, userID, jobID, matchScore)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransactionalJobRepository_UpdateMatchScore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMatchScore'
type MockTransactionalJobRepository_UpdateMatchScore_Call struct {
	*mock.Call
}

// UpdateMatchScore is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - jobID int
//   - matchScore *int
func (_e *MockTransactionalJobRepository_Expecter) UpdateMatchScore(ctx interface{}, userID interface{}, jobID interface{}, matchScore interface{}) *MockTransactionalJobRepository_UpdateMatchScore_Call {
	return &MockTransactionalJobRepository_UpdateMatchScore_Call{Call: _e.mock.On("UpdateMatchScore", ctx, userID, jobID, matchScore)}
}

func (_c *MockTransactionalJobRepository_UpdateMatchScore_Call) Run(run func(ctx context.Context, userID int, jobID int, matchScore *int)) *MockTransactionalJobRepository_UpdateMatchScore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int), args[3].(*int))
	})
	return _c
}

func (_c *MockTransactionalJobRepository_UpdateMatchScore_Call) Return(_a0 error) *MockTransactionalJobRepository_UpdateMatchScore_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactionalJobRepository_UpdateMatchScore_Call) RunAndReturn(run func(context.Context, int, int, *int) error) *MockTransactionalJobRepository_UpdateMatchScore_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: ctx, userID, id, status
func (_m *MockTransactionalJobRepository) UpdateStatus(ctx context.Context, userID int, id int, status models.JobStatus) error {
	ret := _m.Called(ctx, userID, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, models.JobStatus) error); ok {
		r0 = rf(ctx, userID, id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransactionalJobRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockTransactionalJobRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - id int
//   - status models.JobStatus
func (_e *MockTransactionalJobRepository_Expecter) UpdateStatus(ctx interface{}, userID interface{}, id interface{}, status interface{}) *MockTransactionalJobRepository_UpdateStatus_Call {
	return &MockTransactionalJobRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, userID, id, status)}
}

func (_c *MockTransactionalJobRepository_UpdateStatus_Call) Run(run func(ctx context.Context, userID int, id int, status models.JobStatus)) *MockTransactionalJobRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int), args[3].(models.JobStatus))
	})
	return _c
}

func (_c *MockTransactionalJobRepository_UpdateStatus_Call) Return(_a0 error) *MockTransactionalJobRepository_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactionalJobRepository_UpdateStatus_Call) RunAndReturn(run func(context.Context, int, int, models.JobStatus) error) *MockTransactionalJobRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateWithTx provides a mock function with given fields: ctx, tx, userID, job
func (_m *MockTransactionalJobRepository) UpdateWithTx(ctx context.Context, tx *sql.Tx, userID int, job *models.Job) error {
	ret := _m.Called(ctx, tx, userID, job)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWithTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sql.Tx, int, *models.Job) error); ok {
		r0 = rf(ctx, tx, userID, job)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransactionalJobRepository_UpdateWithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateWithTx'
type MockTransactionalJobRepository_UpdateWithTx_Call struct {
	*mock.Call
}

// UpdateWithTx is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sql.Tx
//   - userID int
//   - job *models.Job
func (_e *MockTransactionalJobRepository_Expecter) UpdateWithTx(ctx interface{}, tx interface{}, userID interface{}, job interface{}) *MockTransactionalJobRepository_UpdateWithTx_Call {
	return &MockTransactionalJobRepository_UpdateWithTx_Call{Call: _e.mock.On("UpdateWithTx", ctx, tx, userID, job)}
}

func (_c *MockTransactionalJobRepository_UpdateWithTx_Call) Run(run func(ctx context.Context, tx *sql.Tx, userID int, job *models.Job)) *MockTransactionalJobRepository_UpdateWithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sql.Tx), args[2].(int), args[3].(*models.Job))
	})
	return _c
}

func (_c *MockTransactionalJobRepository_UpdateWithTx_Call) Return(_a0 error) *MockTransactionalJobRepository_UpdateWithTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactionalJobRepository_UpdateWithTx_Call) RunAndReturn(run func(context.Context, *sql.Tx, int, *models.Job) error) *MockTransactionalJobRepository_UpdateWithTx_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransactionalJobRepository creates a new instance of MockTransactionalJobRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionalJobRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionalJobRepository {
	mock := &MockTransactionalJobRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
