// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockAuthServiceInterface is an autogenerated mock type for the AuthServiceInterface type
type MockAuthServiceInterface struct {
	mock.Mock
}

type MockAuthServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthServiceInterface) EXPECT() *MockAuthServiceInterface_Expecter {
	return &MockAuthServiceInterface_Expecter{mock: &_m.Mock}
}

// ChangePassword provides a mock function with given fields: ctx, userID, newPassword
func (_m *MockAuthServiceInterface) ChangePassword(ctx context.Context, userID int, newPassword string) error {
	ret := _m.Called(ctx, userID, newPassword)

	if len(ret) == 0 {
		panic("no return value specified for ChangePassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string) error); ok {
		r0 = rf(ctx, userID, newPassword)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthServiceInterface_ChangePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangePassword'
type MockAuthServiceInterface_ChangePassword_Call struct {
	*mock.Call
}

// ChangePassword is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - newPassword string
func (_e *MockAuthServiceInterface_Expecter) ChangePassword(ctx interface{}, userID interface{}, newPassword interface{}) *MockAuthServiceInterface_ChangePassword_Call {
	return &MockAuthServiceInterface_ChangePassword_Call{Call: _e.mock.On("ChangePassword", ctx, userID, newPassword)}
}

func (_c *MockAuthServiceInterface_ChangePassword_Call) Run(run func(ctx context.Context, userID int, newPassword string)) *MockAuthServiceInterface_ChangePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(string))
	})
	return _c
}

func (_c *MockAuthServiceInterface_ChangePassword_Call) Return(_a0 error) *MockAuthServiceInterface_ChangePassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthServiceInterface_ChangePassword_Call) RunAndReturn(run func(context.Context, int, string) error) *MockAuthServiceInterface_ChangePassword_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAccount provides a mock function with given fields: ctx, userID
func (_m *MockAuthServiceInterface) DeleteAccount(ctx context.Context, userID int) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthServiceInterface_DeleteAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAccount'
type MockAuthServiceInterface_DeleteAccount_Call struct {
	*mock.Call
}

// DeleteAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockAuthServiceInterface_Expecter) DeleteAccount(ctx interface{}, userID interface{}) *MockAuthServiceInterface_DeleteAccount_Call {
	return &MockAuthServiceInterface_DeleteAccount_Call{Call: _e.mock.On("DeleteAccount", ctx, userID)}
}

func (_c *MockAuthServiceInterface_DeleteAccount_Call) Run(run func(ctx context.Context, userID int)) *MockAuthServiceInterface_DeleteAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockAuthServiceInterface_DeleteAccount_Call) Return(_a0 error) *MockAuthServiceInterface_DeleteAccount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthServiceInterface_DeleteAccount_Call) RunAndReturn(run func(context.Context, int) error) *MockAuthServiceInterface_DeleteAccount_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyPassword provides a mock function with given fields: hashedPassword, password
func (_m *MockAuthServiceInterface) VerifyPassword(hashedPassword string, password string) bool {
	ret := _m.Called(hashedPassword, password)

	if len(ret) == 0 {
		panic("no return value specified for VerifyPassword")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(hashedPassword, password)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockAuthServiceInterface_VerifyPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyPassword'
type MockAuthServiceInterface_VerifyPassword_Call struct {
	*mock.Call
}

// VerifyPassword is a helper method to define mock.On call
//   - hashedPassword string
//   - password string
func (_e *MockAuthServiceInterface_Expecter) VerifyPassword(hashedPassword interface{}, password interface{}) *MockAuthServiceInterface_VerifyPassword_Call {
	return &MockAuthServiceInterface_VerifyPassword_Call{Call: _e.mock.On("VerifyPassword", hashedPassword, password)}
}

func (_c *MockAuthServiceInterface_VerifyPassword_Call) Run(run func(hashedPassword string, password string)) *MockAuthServiceInterface_VerifyPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockAuthServiceInterface_VerifyPassword_Call) Return(_a0 bool) *MockAuthServiceInterface_VerifyPassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthServiceInterface_VerifyPassword_Call) RunAndReturn(run func(string, string) bool) *MockAuthServiceInterface_VerifyPassword_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthServiceInterface creates a new instance of MockAuthServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthServiceInterface {
	mock := &MockAuthServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
